/* Flourish Anyway — Emergency Preparedness & Disasters
   Jackson + Josephine Counties, Oregon
   IMPORTANT: live incident conditions must always be opened at the official source.
   Last master verification: 2026-09-01
*/
window.FLOURISH_EMERGENCY_DATA = [
{id:"emergency-live-warning",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"⚠️ CHECK LIVE CONDITIONS — DO NOT RELY ON SAVED SCREENSHOTS",helps:"Evacuations, fires, smoke, roads, outages, shelters and weather can change within minutes. Open the current official source before acting.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://wildfire.oregon.gov/",sourceName:"Oregon Wildfire Response & Recovery",labels:["LIVE","CHECK NOW"],keywords:["live emergency","current conditions","do not rely on screenshot"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"jackson-alerts",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Jackson Alerts — Jackson County Emergency Notifications",helps:"Official Jackson County emergency notification system. Register locations you care about and keep contact information current.",audience:["Jackson County Residents","Families","Workers"],counties:["Jackson"],cost:"Free",website:"https://readyjacksonco.com/",sourceName:"Jackson County Emergency Management",labels:["LIVE","ALERTS","EVACUATION"],keywords:["Jackson Alerts","emergency alert","evacuation","school","work"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"josephine-citizen-alert",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Citizen Alert — Josephine County",helps:"Official Josephine County opt-in emergency notifications by phone, text or email for events such as fire, flood, road closures and evacuations.",audience:["Josephine County Residents","Families","Workers"],counties:["Josephine"],cost:"Free",website:"https://www.josephinecounty.gov/departments/emergency_management/citizen_alert.php",sourceName:"Josephine County Emergency Management",labels:["LIVE","ALERTS","EVACUATION"],keywords:["Citizen Alert","Josephine","evacuation","fire","flood"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"genasys-protect",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Genasys Protect — Know Your Zone / Evacuation Map",helps:"Open the current map for evacuation zones, hazard alerts and instructions from local officials. Alert registration and zone monitoring are separate tools, so use the county alert system too.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://protect.genasys.com/",sourceName:"Genasys Protect / Local Emergency Management",labels:["LIVE","EVACUATION ZONE","MAP"],keywords:["Genasys","Know Your Zone","evacuation map","GO NOW"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-fire-dashboard",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Oregon Wildfire Response & Recovery — Fire Dashboard",helps:"State gateway to current wildfire dashboards, evacuation information, ODF fire danger, air quality and TripCheck.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://wildfire.oregon.gov/",sourceName:"State of Oregon",labels:["LIVE","FIRE MAP"],keywords:["wildfire","fire map","active fire","evacuation"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"odf-fire-restrictions",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Oregon Department of Forestry — Fire Restrictions & Closures",helps:"Current public and industrial fire restrictions. Restrictions are prevention rules and are not the same thing as a map of active fires.",audience:["Everyone","Workers","Outdoor Recreation"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.oregon.gov/odf/fire/pages/restrictions.aspx",sourceName:"Oregon Department of Forestry",labels:["LIVE","FIRE RESTRICTIONS"],keywords:["fire danger","restrictions","burn ban","IFPL"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-deq-aqi",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Oregon DEQ — Live Air Quality Index",helps:"Open the live Oregon AQI map for current monitored air quality. Do not save or reuse an old AQI number.",audience:["Everyone","Children","Seniors","People with Health Risks"],counties:["Jackson","Josephine"],cost:"Free",website:"https://aqi.oregon.gov/",sourceName:"Oregon DEQ",labels:["LIVE","AIR QUALITY","SMOKE"],keywords:["AQI","smoke","PM2.5","air quality"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-smoke",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Oregon Smoke Information — Fire & Air Quality",helps:"Current Oregon wildfire-smoke information and fire/air-quality mapping. Smoke conditions can change rapidly.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.oregonsmoke.org/",sourceName:"Oregon DEQ and partner agencies",labels:["LIVE","SMOKE","AIR QUALITY"],keywords:["smoke forecast","wildfire smoke","AQI"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"tripcheck",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"TripCheck — Oregon Road Conditions & Closures",helps:"Primary statewide source for current highway closures, road conditions, incidents and travel impacts. Check immediately before traveling during emergencies.",audience:["Drivers","Travelers","Evacuees"],counties:["Jackson","Josephine"],cost:"Free",phone:"511 / 800-977-6368",website:"https://tripcheck.com/",sourceName:"Oregon Department of Transportation",labels:["LIVE","ROAD CLOSURES"],keywords:["TripCheck","511","road closure","I-5","US 199","evacuation route"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"pacific-power-outages",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Pacific Power — Outage Map",helps:"Check current outages and report a power outage. Treat downed power lines as dangerous and stay away.",audience:["Pacific Power Customers"],counties:["Jackson","Josephine"],cost:"Free",phone:"877-508-5088",website:"https://www.pacificpower.net/outages-safety.html",sourceName:"Pacific Power",labels:["LIVE","POWER OUTAGE"],keywords:["power outage","electric","downed line"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"pacific-power-psps",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"Pacific Power — Public Safety Power Shutoff (PSPS)",helps:"Separate live information for wildfire-safety shutoffs. The PSPS map distinguishes watch, warning, active and restored conditions.",audience:["Pacific Power Customers"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.pacificpower.net/outages-safety/wildfire-safety/public-safety-power-shutoff.html",sourceName:"Pacific Power",labels:["LIVE","PSPS","WILDFIRE"],keywords:["Public Safety Power Shutoff","de-energization","PSPS"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"live-shelter-centers-211",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"211info — Open Shelters, Cooling/Warming & Smoke Centers",helps:"Search current activated shelters and temporary cooling, warming or smoke-relief centers. Locations and hours may exist only for a specific incident or weather event.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",phone:"211 / 866-698-6155",website:"https://www.211info.org/",sourceName:"211info",labels:["LIVE","SHELTER","COOLING","WARMING"],keywords:["open shelter","cooling center","warming center","smoke shelter"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"redcross-shelter",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"American Red Cross — Find an Open Shelter",helps:"Use the live shelter finder during disasters. Disaster shelter sites are activated incident-by-incident; do not assume a previously used building is currently open.",audience:["Disaster Survivors","Evacuees"],counties:["Jackson","Josephine"],cost:"Free",phone:"800-733-2767",website:"https://www.redcross.org/get-help/disaster-relief-and-recovery-services/find-an-open-shelter.html",sourceName:"American Red Cross",labels:["LIVE","DISASTER SHELTER"],keywords:["Red Cross","open shelter","evacuation shelter"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"nws-medford",category:"emergency",section:"⚠️ LIVE — CHECK NOW",name:"National Weather Service Medford — Alerts & Forecasts",helps:"Current official weather warnings and forecasts for heat, freeze, snow/ice, flooding, wind, thunderstorms, lightning and fire weather.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.weather.gov/mfr/",sourceName:"National Weather Service Medford",labels:["LIVE","WEATHER"],keywords:["red flag","heat","snow","flood","wind","lightning","weather warning"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"evac-levels",category:"emergency",section:"Evacuation — know what to do",name:"Oregon Evacuation Levels — Be Ready, Be Set, Go Now",helps:"Level 1: BE READY. Level 2: BE SET and be ready to leave immediately; people needing extra time should leave early. Level 3: GO NOW—leave immediately and do not stop to gather belongings. You may leave earlier whenever you feel unsafe.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",website:"https://wildfire.oregon.gov/pages/evacuations.aspx",sourceName:"Oregon Department of Emergency Management",labels:["EVACUATION","LEVEL 1","LEVEL 2","LEVEL 3"],keywords:["Be Ready","Be Set","Go Now","leave early"],lastVerified:"2026-09-01"},
{id:"wireless-alerts",category:"emergency",section:"Evacuation — know what to do",name:"Wireless Emergency Alerts (WEA)",helps:"National emergency alerts can be sent to compatible phones in affected areas without a local sign-up. Keep county alert registration too because the systems serve different purposes.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"No subscription fee",website:"https://www.ready.gov/alerts",sourceName:"Ready.gov",labels:["ALERTS","PHONE"],keywords:["WEA","wireless emergency alert","phone alert"],lastVerified:"2026-09-01"},

{id:"school-emergency",category:"emergency",section:"Children, schools & family emergency plans",name:"School Closures & Emergency Messages — Check Your District",helps:"Use your child's school/district official emergency channel for closure, delay, reunification and transportation changes. Also register school locations in county alert tools when available.",audience:["Parents","Caregivers","Students"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.oregon.gov/ode/schools-and-districts/pages/institution-id-district-directory.aspx",sourceName:"Oregon Department of Education / Local Districts",labels:["SCHOOL","CLOSURE","FAMILY PLAN"],keywords:["school closure","snow day","reunification","district alert"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"pet-prep",category:"emergency",section:"Pets, livestock, disability & medical preparation",name:"Oregon — Build an Evacuation Kit for Pets",helps:"Prepare food, water, medications, identification, veterinary records, carriers/leashes and other supplies before an evacuation. Move animals early when conditions may make transport harder.",audience:["Pet Owners","Families"],counties:["Jackson","Josephine"],cost:"Preparedness information",website:"https://www.oregon.gov/oda/animal-health-feeds-livestock-id/emergency-preparedness/disaster-preparedness-animal-owners/pages/evacuation-kit-pets.aspx",sourceName:"Oregon Department of Agriculture",labels:["PETS","GO BAG"],keywords:["pet evacuation","carrier","pet medication","animal"],lastVerified:"2026-09-01"},
{id:"medical-prep",category:"emergency",section:"Pets, livestock, disability & medical preparation",name:"Disability & Medical Emergency Planning",helps:"Plan ahead for medications, mobility/communication needs, caregivers, accessible evacuation, backup power for medical equipment and extra time needed to leave.",audience:["People with Disabilities","Seniors","Caregivers","People Using Medical Equipment"],counties:["Jackson","Josephine"],cost:"Preparedness information",website:"https://www.ready.gov/disability",sourceName:"Ready.gov",labels:["DISABILITY","MEDICAL","ACCESS"],keywords:["oxygen","power dependent","wheelchair","medication","caregiver"],lastVerified:"2026-09-01"},


{id:"watch-duty",category:"emergency",section:"Local emergency information & eyes on the valley",name:"Watch Duty — Wildfire Map & Alerts",helps:"Fast wildfire incident maps and updates used widely in Southern Oregon. Use it as a supplemental wildfire-awareness tool; confirm evacuation orders and official instructions through county alerts and Genasys Protect.",audience:["Everyone","Families","Rural Residents"],counties:["Jackson","Josephine"],cost:"Free; optional paid features/donations",website:"https://app.watchduty.org/",sourceName:"Watch Duty",labels:["LIVE","WILDFIRE","SUPPLEMENTAL"],keywords:["Watch Duty","fire map","wildfire app","fire alerts"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"pulsepoint",category:"emergency",section:"Local emergency information & eyes on the valley",name:"PulsePoint Respond — Local 911-Connected Incident Information",helps:"911-connected incident information and notifications. Jackson County Community Long-Term Recovery Group lists participating local agencies including Medford Fire, Ashland Fire & Rescue and Jackson County Fire District 5. Useful for situational awareness; not a substitute for official evacuation orders.",audience:["Everyone","CPR-Trained Community Members"],counties:["Jackson"],cost:"Free",website:"https://www.pulsepoint.org/download",sourceName:"PulsePoint Foundation",labels:["LIVE","FIRE","MEDICAL","SUPPLEMENTAL"],keywords:["PulsePoint","dispatch","fire call","CPR","incident"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"roxy-ann-skycam",category:"emergency",section:"Local emergency information & eyes on the valley",name:"Roxy Ann Peak Skycam — Live Rogue Valley Camera & Scanner",helps:"Public live camera overlooking the Rogue Valley with scanner feeds covering ODF, fire agencies, law enforcement and other local public-safety traffic. Helpful for visual situational awareness, but camera/scanner feeds can go offline and are not official evacuation instructions.",audience:["Everyone","Jackson County Residents"],counties:["Jackson"],cost:"Free",website:"https://roxyannpeak.com/",sourceName:"Roxy Ann Peak Skycam",labels:["LIVE CAMERA","SCANNER","SUPPLEMENTAL"],keywords:["Roxy Ann","Roxanne Peak","skycam","camera","scanner","smoke","fire"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"rogue-weather",category:"emergency",section:"Local emergency information & eyes on the valley",name:"Rogue Weather — Southern Oregon Weather & Bulletins",helps:"Local Southern Oregon weather site with forecasts, road information and a weather-bulletin page that automatically updates National Weather Service bulletins. Use NWS Medford as the official warning source.",audience:["Everyone","Travelers","Rural Residents"],counties:["Jackson","Josephine"],cost:"Free",website:"https://www.rogueweather.com/",sourceName:"Rogue Weather",labels:["WEATHER","LOCAL","SUPPLEMENTAL"],keywords:["Rogue Weather","weather bulletin","storm","snow","heat","fire weather"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"ryan-weather",category:"emergency",section:"Local emergency information & eyes on the valley",name:"RyanWeather — Rogue Valley Live Weather Station",helps:"Medford-based live weather station with frequently updated local observations, forecast information and NWS Medford radar. Useful as an additional local observation source; use NWS for official watches and warnings.",audience:["Everyone","Jackson County Residents"],counties:["Jackson"],cost:"Free",website:"https://www.ryanweather.com/",sourceName:"RyanWeather",labels:["LIVE WEATHER","LOCAL","SUPPLEMENTAL"],keywords:["Ryan Weather","Medford weather","live weather station","radar"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"noaa-weather-radio",category:"emergency",section:"Local radio, TV & emergency news",name:"NOAA Weather Radio — Medford / Ashland",helps:"Official National Weather Service continuous weather radio for warnings and emergency information. Southern Oregon EAS planning identifies Medford WXL-85 on 162.400 MHz and Ashland WWF-97 on 162.475 MHz.",audience:["Everyone","Rural Residents","Preparedness"],counties:["Jackson","Josephine"],cost:"Broadcast is free; weather radio receiver required",website:"https://www.weather.gov/mfr/NOAA_Weather_Radio",sourceName:"National Weather Service Medford",labels:["OFFICIAL","RADIO","WEATHER ALERTS"],keywords:["NOAA weather radio","162.400","162.475","weather warning","SAME"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"jackson-emergency-radio",category:"emergency",section:"Local radio, TV & emergency news",name:"Jackson County — Emergency Information Radio Stations",helps:"Radio stations identified in Oregon emergency-preparedness resources for Jackson County: KBOY 95.7 FM, KAKT 105.0 FM, KCMX 880 AM / 101.9 FM, KCNA 97.7 FM, KDOV 91.7 FM, KMED 1440 AM and KRWQ 100.3 FM. Keep a battery-powered radio available for internet/cell outages.",audience:["Jackson County Residents","Everyone"],counties:["Jackson"],cost:"Free broadcast",website:"https://emergency.oregonstate.edu/emergency-management/useful-links/radio-stations",sourceName:"Oregon State University Emergency Management",labels:["RADIO","BACKUP INFORMATION"],keywords:["KBOY","KAKT","KCMX","KCNA","KDOV","KMED","KRWQ","emergency radio"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"josephine-emergency-radio",category:"emergency",section:"Local radio, TV & emergency news",name:"Josephine County — Emergency Information Radio Stations",helps:"Oregon emergency-preparedness resources identify KAJO and KLDR for Josephine County. KAJO currently broadcasts on 1270 AM / 99.7 FM; KLDR broadcasts 98.3 FM Grants Pass, 98.1 FM Medford and 104.5 FM Illinois Valley. Keep a battery-powered radio available for internet/cell outages.",audience:["Josephine County Residents","Everyone"],counties:["Josephine"],cost:"Free broadcast",website:"https://emergency.oregonstate.edu/emergency-management/useful-links/radio-stations",sourceName:"Oregon State University Emergency Management",labels:["RADIO","BACKUP INFORMATION"],keywords:["KAJO","1270 AM","99.7 FM","KLDR","98.3","98.1","104.5","Grants Pass","Illinois Valley"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"kajo",category:"emergency",section:"Local radio, TV & emergency news",name:"KAJO 1270 AM / 99.7 FM — Grants Pass",helps:"Grants Pass radio station and local information source. Its published contact information includes a weather phone and burn-day information line. Use county emergency alerts for official evacuation orders.",audience:["Josephine County Residents","Grants Pass Area"],counties:["Josephine"],cost:"Free broadcast",website:"https://www.kajo.com/",sourceName:"KAJO",labels:["LOCAL RADIO","NEWS"],keywords:["KAJO","Grants Pass radio","1270","99.7","weather","burn day"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"kldr",category:"emergency",section:"Local radio, TV & emergency news",name:"KLDR — Grants Pass / Medford / Illinois Valley",helps:"Southern Oregon radio and local-news source serving Grants Pass, Medford and the Illinois Valley. Useful as a backup local information channel during weather and community emergencies.",audience:["Josephine County Residents","Jackson County Residents"],counties:["Jackson","Josephine"],cost:"Free broadcast",website:"https://www.kldr.com/",sourceName:"KLDR",labels:["LOCAL RADIO","LOCAL NEWS"],keywords:["KLDR","98.3","98.1","104.5","Grants Pass","Illinois Valley"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"kobi5",category:"emergency",section:"Local radio, TV & emergency news",name:"KOBI-TV NBC5 — Local News & Emergency Information",helps:"Southern Oregon local television/news source. The Southern Oregon Emergency Alert System plan identifies KOBI-TV Channel 5 Medford as a local and state primary EAS station for the operational area.",audience:["Everyone","Southern Oregon Residents"],counties:["Jackson","Josephine"],cost:"Free news/broadcast",website:"https://kobi5.com/",sourceName:"KOBI-TV NBC5",labels:["LOCAL TV","EAS","NEWS"],keywords:["KOBI","NBC5","Channel 5","emergency alert system","news"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"kdrv12",category:"emergency",section:"Local radio, TV & emergency news",name:"KDRV NewsWatch 12 — Southern Oregon News & Weather",helps:"Local Southern Oregon news, breaking-news and weather coverage. Useful for incident reporting, weather coverage and community closure information; confirm evacuation orders with official county sources.",audience:["Everyone","Southern Oregon Residents"],counties:["Jackson","Josephine"],cost:"Free news",website:"https://www.kdrv.com/",sourceName:"KDRV NewsWatch 12",labels:["LOCAL TV","NEWS","WEATHER"],keywords:["KDRV","NewsWatch 12","ABC","StormTracker","breaking news"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"ktvl10",category:"emergency",section:"Local radio, TV & emergency news",name:"KTVL News 10 — Medford Local News",helps:"Medford-area local news and weather source for breaking events, closures and community information. Confirm official emergency instructions through county/state sources.",audience:["Everyone","Southern Oregon Residents"],counties:["Jackson","Josephine"],cost:"Free news",website:"https://ktvl.com/",sourceName:"KTVL News 10",labels:["LOCAL TV","NEWS"],keywords:["KTVL","News 10","Medford news","weather","closures"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"kmvu26",category:"emergency",section:"Local radio, TV & emergency news",name:"KMVU FOX 26 — Southern Oregon Local News",helps:"Southern Oregon television/news source that can provide local breaking-news and weather coverage. Use official emergency-management sources for evacuation zones and orders.",audience:["Everyone","Southern Oregon Residents"],counties:["Jackson","Josephine"],cost:"Free news",website:"https://fox26medford.com/",sourceName:"KMVU FOX 26",labels:["LOCAL TV","NEWS"],keywords:["KMVU","FOX 26","Medford","Southern Oregon news"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"snap-replacement",category:"emergency",section:"Food, money & immediate recovery",name:"Oregon SNAP — Replace Food Lost in a Disaster",helps:"If SNAP-purchased food is destroyed by fire, flood, storm or power outage, contact ODHS quickly. The normal reporting deadline is within 10 days of the food loss unless Oregon announces a disaster-specific extension.",audience:["SNAP Households","Families","Adults"],counties:["Jackson","Josephine"],cost:"Replacement benefit if eligible",phone:"800-699-9075",website:"https://www.oregon.gov/odhs/food/pages/snap-replacement.aspx",sourceName:"Oregon Department of Human Services",labels:["SNAP","LOST FOOD","POWER OUTAGE"],keywords:["food spoiled","EBT replacement","fire","flood","power outage"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"disaster-food-211",category:"emergency",section:"Food, money & immediate recovery",name:"211info — Emergency Food & Basic Needs",helps:"Search current food pantries, meals and other basic-needs assistance after an emergency or disaster.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free information and referral",phone:"211 / 866-698-6155",website:"https://www.211info.org/",sourceName:"211info",labels:["FOOD","BASIC NEEDS"],keywords:["emergency food","pantry","disaster food"],lastVerified:"2026-09-01",scheduleChangesOften:true},

{id:"oregon-disaster-recovery",category:"emergency",section:"Disaster recovery, housing & insurance",name:"Oregon Wildfire Response & Recovery — Recovery Resources",helps:"State gateway for personal recovery, housing, cleanup, renters/tenants, homeowners and other post-wildfire assistance.",audience:["Disaster Survivors","Renters","Homeowners","Families"],counties:["Jackson","Josephine"],cost:"Information; assistance depends on program/incident",website:"https://wildfire.oregon.gov/",sourceName:"State of Oregon",labels:["RECOVERY","HOUSING","CLEANUP"],keywords:["wildfire recovery","cleanup","temporary housing","renter"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-individual-assistance",category:"emergency",section:"Disaster recovery, housing & insurance",name:"Oregon OEM — Individual Assistance / FEMA Disaster Help",helps:"When federal or state disaster assistance is authorized, qualifying programs may help with housing and certain disaster-caused essential expenses. Availability depends on the specific declaration.",audience:["Disaster Survivors","Renters","Homeowners","Families"],counties:["Jackson","Josephine"],cost:"Eligibility and declaration dependent",website:"https://www.oregon.gov/oem/emresources/disasterassist/Pages/Individual-Assistance.aspx",sourceName:"Oregon Department of Emergency Management",labels:["FEMA","DISASTER ASSISTANCE","RECOVERY"],keywords:["FEMA","Individual Assistance","housing repair","medical dental","child care"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-insurance-disaster",category:"emergency",section:"Disaster recovery, housing & insurance",name:"Oregon Division of Financial Regulation — Wildfire Insurance Help",helps:"Insurance guidance for homeowners and renters. If evacuated, save receipts and document losses; applicable policies may cover additional living expenses such as lodging, food or pet boarding. Confirm coverage with the insurer.",audience:["Renters","Homeowners","Policyholders"],counties:["Jackson","Josephine"],cost:"State consumer information",website:"https://dfr.oregon.gov/insure/home/storm/pages/wildfires.aspx",sourceName:"Oregon Division of Financial Regulation",labels:["INSURANCE","RECEIPTS","DOCUMENTATION"],keywords:["claim","renters insurance","homeowners","additional living expenses","ALE"],lastVerified:"2026-09-01"},

{id:"ready-jackson",category:"emergency",section:"Prepare before the disaster",name:"Ready Jackson County — Local Preparedness Hub",helps:"Local Jackson County preparedness information and links to alerts, evacuation zones and emergency resources.",audience:["Everyone","Families"],counties:["Jackson"],cost:"Free",website:"https://readyjacksonco.com/",sourceName:"Jackson County Emergency Management",labels:["PREPARE","JACKSON COUNTY"],keywords:["go bag","emergency plan","preparedness","Jackson"],lastVerified:"2026-09-01"},
{id:"ready-gov-kit",category:"emergency",section:"Prepare before the disaster",name:"Ready.gov — Build a Household Emergency Kit",helps:"Use a household-specific emergency kit and plan. Include water, food, medications, communications, sanitation, important documents, chargers, lighting and supplies for children, pets, disability and medical needs.",audience:["Everyone","Families","Caregivers"],counties:["Jackson","Josephine"],cost:"Preparedness information",website:"https://www.ready.gov/kit",sourceName:"Ready.gov",labels:["GO BAG","EMERGENCY KIT","PLAN"],keywords:["two week supplies","water","documents","medications","go bag"],lastVerified:"2026-09-01"},

{id:"911",category:"emergency",section:"Crisis, violence & immediate safety",name:"911 — Immediate Emergency",helps:"Call for immediate danger, serious injury, fire, active violence, overdose or another life-threatening emergency.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Emergency service",phone:"911",website:"https://www.911.gov/",sourceName:"911.gov",labels:["IMMEDIATE DANGER"],keywords:["police","fire","ambulance","overdose"],lastVerified:"2026-09-01"},
{id:"988",category:"emergency",section:"Crisis, violence & immediate safety",name:"988 Suicide & Crisis Lifeline",helps:"24/7 call, text and chat support for suicidal thoughts, emotional distress, mental-health crisis or substance-use crisis.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free",phone:"988",website:"https://988lifeline.org/",sourceName:"988 Lifeline",labels:["24/7","MENTAL HEALTH"],keywords:["suicide","crisis","substance use"],lastVerified:"2026-09-01"},
{id:"community-works-helpline",category:"emergency",section:"Crisis, violence & immediate safety",name:"Community Works — 24/7 HelpLine",helps:"Confidential local crisis advocacy for domestic violence, sexual assault, stalking or trafficking, including safety planning and connection to available services.",audience:["Survivors","Women","Adults","Youth","Families"],counties:["Jackson","Josephine"],cost:"Free and confidential",phone:"541-779-4357",address:"Southern Oregon",website:"https://www.community-works.org/",sourceName:"Community Works",labels:["24/7","DOMESTIC VIOLENCE","SEXUAL ASSAULT"],keywords:["abuse","stalking","trafficking","safe shelter"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"wcst",category:"emergency",section:"Crisis, violence & immediate safety",name:"Women’s Crisis Support Team — Josephine County",helps:"Confidential domestic-violence and sexual-assault advocacy and crisis support for Josephine County survivors.",audience:["Survivors","Women","Families"],counties:["Josephine"],cost:"Free and confidential",phone:"541-479-9349 / 800-750-9278",address:"Grants Pass, OR",website:"https://wcstjoco.org/",sourceName:"Women’s Crisis Support Team",labels:["DOMESTIC VIOLENCE","SEXUAL ASSAULT"],keywords:["WCST","abuse","Grants Pass"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"ivsha",category:"emergency",section:"Crisis, violence & immediate safety",name:"Illinois Valley Safe House Alliance",helps:"Domestic-violence and sexual-assault advocacy with an Illinois Valley focus. Contact the program for current crisis and shelter-related services.",audience:["Survivors","Women","Families","Rural Residents"],counties:["Josephine"],cost:"Advocacy is free/confidential",phone:"541-592-2515",address:"Cave Junction, OR",website:"https://www.ivsha.org/",sourceName:"Illinois Valley Safe House Alliance",labels:["DOMESTIC VIOLENCE","RURAL"],keywords:["Cave Junction","Illinois Valley","safe house"],lastVerified:"2026-09-01",scheduleChangesOften:true},
{id:"oregon-child-abuse",category:"emergency",section:"Crisis, violence & immediate safety",name:"Oregon Child Abuse Hotline",helps:"Report suspected child abuse or neglect anywhere in Oregon. Call 911 when a child is in immediate danger.",audience:["Children","Families","Community"],counties:["Jackson","Josephine"],cost:"Free",phone:"855-503-7233",website:"https://www.oregon.gov/odhs/report-abuse/pages/default.aspx",sourceName:"Oregon DHS",labels:["CHILD SAFETY"],keywords:["child abuse","neglect","SAFE hotline"],lastVerified:"2026-09-01"},
{id:"oregon-adult-abuse",category:"emergency",section:"Crisis, violence & immediate safety",name:"Oregon Adult Protective Services / Abuse Reporting",helps:"Report suspected abuse, neglect, self-neglect or financial exploitation involving an older adult or qualifying adult with a disability.",audience:["Seniors","Adults with Disabilities","Community"],counties:["Jackson","Josephine"],cost:"Free",phone:"855-503-7233",website:"https://www.oregon.gov/odhs/report-abuse/pages/default.aspx",sourceName:"Oregon DHS",labels:["ELDER ABUSE","DISABILITY"],keywords:["APS","financial exploitation","neglect"],lastVerified:"2026-09-01"},
{id:"poison-center",category:"emergency",section:"Crisis, violence & immediate safety",name:"Oregon Poison Center",helps:"24/7 expert help for poisonings, medication mistakes, chemical exposures, bites and other possible toxic exposures. Call 911 for life-threatening symptoms.",audience:["Everyone","Parents","Caregivers"],counties:["Jackson","Josephine"],cost:"Free",phone:"800-222-1222",website:"https://www.ohsu.edu/oregon-poison-center",sourceName:"OHSU Oregon Poison Center",labels:["24/7","POISON"],keywords:["medication overdose","chemical","toxin"],lastVerified:"2026-09-01"}
];
