/* Flourish Anyway Community Resource Hub
   EMERGENCY HELP
   File name after upload: emergency-data.js
   Jackson + Josephine Counties, Oregon
   Immediate safety, crisis, shelter, youth/family crisis and statewide hotlines
   Last researched: 2026-08-30
*/

window.FLOURISH_EMERGENCY_DATA = [
  {
    id:"911",
    category:"emergency",
    name:"911 — Immediate Emergency",
    helps:"Call for immediate danger, serious injury, fire, active violence, overdose or another life-threatening emergency.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Emergency service",
    phone:"911",
    address:"United States",
    website:"https://www.911.gov/",
    labels:["IMMEDIATE DANGER","POLICE","FIRE","AMBULANCE"],
    keywords:["911","emergency","ambulance","police","fire","overdose","danger"],
    lastVerified:"2026-08-30"
  },
  {
    id:"988",
    category:"emergency",
    name:"988 Suicide & Crisis Lifeline",
    helps:"24/7 call, text and chat support for suicidal thoughts, emotional distress, mental-health crisis or substance-use crisis.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"988",
    address:"Nationwide",
    website:"https://988lifeline.org/",
    labels:["24/7","MENTAL HEALTH","SUICIDE","CRISIS"],
    keywords:["988","suicide","mental health crisis","emotional crisis","substance crisis"],
    lastVerified:"2026-08-30"
  },
  {
    id:"community-works-helpline",
    category:"emergency",
    name:"Community Works — 24/7 HelpLine",
    helps:"Free confidential crisis advocacy for people impacted by domestic violence, sexual assault, stalking or trafficking. Advocates are available 24/7 and interpreters are available in many languages including ASL.",
    audience:["Survivors","Women","Adults","Youth","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free and confidential",
    phone:"541-779-4357",
    address:"2594 E Barnett Rd, Suite C, Medford, OR 97504",
    website:"https://www.community-works.org/",
    labels:["24/7","DOMESTIC VIOLENCE","SEXUAL ASSAULT","TRAFFICKING"],
    keywords:["domestic violence","sexual assault","stalking","trafficking","abuse","shelter"],
    lastVerified:"2026-08-30"
  },
  {
    id:"dunn-house",
    category:"emergency",
    name:"Community Works — Dunn House Emergency Shelter",
    helps:"Confidential emergency shelter for adults and their children experiencing crisis or displacement, with advocacy and help planning next steps.",
    audience:["Adults","Parents","Children","Survivors"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"541-779-4357",
    address:"Confidential shelter location",
    website:"https://www.community-works.org/shelter/",
    labels:["EMERGENCY SHELTER","ADULTS + CHILDREN","CONFIDENTIAL"],
    keywords:["Dunn House","domestic violence shelter","emergency shelter","children","safe house"],
    lastVerified:"2026-08-30"
  },
  {
    id:"maslow-medford",
    category:"emergency",
    name:"Maslow Project — Medford Youth & Family Resource Center",
    helps:"Free low-barrier help for youth age 24 or younger and families with school-aged children or younger who are homeless, couch surfing, living in vehicles/hotels, facing homelessness or in unsafe housing. Offers food, hygiene supplies, clothing, case management, housing navigation and more.",
    audience:["Youth 24 and Under","Families with Children","Homeless Youth"],
    counties:["Jackson"],
    cost:"Free",
    phone:"541-608-6868",
    address:"500 Monroe St, Medford, OR 97501",
    website:"https://www.maslowproject.com/get-help/",
    labels:["YOUTH","FAMILIES","HOMELESSNESS","DROP-IN"],
    keywords:["homeless youth","family homelessness","couch surfing","car","Maslow","Medford"],
    lastVerified:"2026-08-30"
  },
  {
    id:"maslow-grants-pass",
    category:"emergency",
    name:"Maslow Project — Grants Pass Youth & Family Resource Center",
    helps:"Free help for eligible youth and families experiencing homelessness, unstable housing or unsafe living situations, including basic needs, case management and housing support.",
    audience:["Youth 24 and Under","Families with Children","Homeless Youth"],
    counties:["Josephine"],
    cost:"Free",
    phone:"541-841-1974",
    address:"223 SE M St, Grants Pass, OR 97526",
    website:"https://www.maslowproject.com/get-help/",
    labels:["YOUTH","FAMILIES","HOMELESSNESS","GRANTS PASS"],
    keywords:["Maslow","Grants Pass","homeless youth","family homelessness","couch surfing"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-child-abuse",
    category:"emergency",
    name:"Oregon Child Abuse Hotline",
    helps:"Report suspected child abuse or neglect anywhere in Oregon. Call 911 instead when a child is in immediate danger.",
    audience:["Children","Families","Community"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"855-503-7233",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odhs/report-abuse/pages/default.aspx",
    labels:["CHILD SAFETY","ABUSE","NEGLECT"],
    keywords:["child abuse","neglect","CPS","report abuse","SAFE hotline"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-adult-abuse",
    category:"emergency",
    name:"Oregon Adult Protective Services / Abuse Reporting",
    helps:"Report suspected abuse, neglect, self-neglect or financial exploitation involving an older adult or qualifying adult with a disability.",
    audience:["Seniors","Adults with Disabilities","Community"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"855-503-7233",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odhs/report-abuse/pages/default.aspx",
    labels:["ELDER ABUSE","DISABILITY","EXPLOITATION"],
    keywords:["elder abuse","adult abuse","financial exploitation","neglect","APS"],
    lastVerified:"2026-08-30"
  },
  {
    id:"poison-center",
    category:"emergency",
    name:"Oregon Poison Center",
    helps:"24/7 expert help for poisonings, medication mistakes, chemical exposures, bites and other possible toxic exposures. Call 911 for life-threatening symptoms.",
    audience:["Everyone","Parents","Caregivers"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"800-222-1222",
    address:"Oregon statewide",
    website:"https://www.ohsu.edu/oregon-poison-center",
    labels:["24/7","POISON","MEDICATION","EXPOSURE"],
    keywords:["poison","medication overdose","chemical","bite","toxin","poison control"],
    lastVerified:"2026-08-30"
  },
  {
    id:"national-dv-hotline",
    category:"emergency",
    name:"National Domestic Violence Hotline",
    helps:"24/7 confidential safety planning, crisis support and referrals for people experiencing relationship abuse.",
    audience:["Survivors","Adults","Teens"],
    counties:["Jackson","Josephine"],
    cost:"Free and confidential",
    phone:"800-799-7233",
    address:"Nationwide",
    website:"https://www.thehotline.org/",
    labels:["24/7","DOMESTIC VIOLENCE","SAFETY PLANNING"],
    keywords:["domestic violence","abusive relationship","safety plan","hotline"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rainn",
    category:"emergency",
    name:"RAINN — National Sexual Assault Hotline",
    helps:"Confidential 24/7 support and connection to local resources for survivors of sexual assault.",
    audience:["Survivors","Adults","Teens"],
    counties:["Jackson","Josephine"],
    cost:"Free and confidential",
    phone:"800-656-4673",
    address:"Nationwide",
    website:"https://rainn.org/",
    labels:["24/7","SEXUAL ASSAULT","CONFIDENTIAL"],
    keywords:["rape","sexual assault","RAINN","survivor","hotline"],
    lastVerified:"2026-08-30"
  },
  {
    id:"veterans-crisis",
    category:"emergency",
    name:"Veterans Crisis Line",
    helps:"24/7 crisis support for veterans, service members and their families. Call 988 and press 1.",
    audience:["Veterans","Service Members","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"988 press 1",
    address:"Nationwide",
    website:"https://www.veteranscrisisline.net/",
    labels:["VETERANS","24/7","CRISIS"],
    keywords:["veteran crisis","988 press 1","military","suicide"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-emergency",
    category:"emergency",
    name:"211info — Urgent Community Resource Help",
    helps:"Free referral help for shelter, food, utilities, transportation, health care and other urgent basic needs. 211 is not a substitute for 911 when someone is in immediate danger.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"211",
    text:"Text ZIP code to 898211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["211","SHELTER","FOOD","URGENT NEEDS"],
    keywords:["211","emergency shelter","food","utility shutoff","urgent help"],
    lastVerified:"2026-08-30"
  },
  {
    id:"community-works-help-line",
    category:"emergency",
    name:"Community Works — HelpLine & Domestic Violence Support",
    helps:"Southern Oregon support for people affected by domestic violence, sexual assault, stalking and related abuse. Use the HelpLine for safety planning and connection to available services. Call 911 for immediate danger.",
    audience:["Survivors","Women","Families","Teens"],
    counties:["Jackson","Josephine"],
    cost:"Crisis/support services are free",
    phone:"541-779-4357",
    address:"Southern Oregon",
    website:"https://www.community-works.org/",
    labels:["DOMESTIC VIOLENCE","SEXUAL ASSAULT","SAFETY"],
    keywords:["domestic violence","DV","abuse","sexual assault","stalking","safe shelter","HelpLine"],
    lastVerified:"2026-08-31"
  },
  {
    id:"988-oregon",
    category:"emergency",
    name:"988 Suicide & Crisis Lifeline — Oregon",
    helps:"Call, text or chat 988 for mental-health, suicide or substance-use crisis support. Use 911 when there is an immediate life-threatening emergency requiring emergency response.",
    audience:["Anyone in Crisis","Families","Friends"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"988",
    address:"24/7",
    website:"https://988lifeline.org/",
    labels:["24/7","MENTAL HEALTH CRISIS","SUICIDE"],
    keywords:["988","suicide","crisis","mental health emergency","someone to talk to"],
    lastVerified:"2026-08-31"
  },
  {
    id:"211-oregon-emergency",
    category:"emergency",
    name:"211info — Urgent Community Resource Navigation",
    helps:"When you do not know which local agency handles the problem, 211 can search changing community resources for food, housing, utilities, health, family support and other basic needs.",
    audience:["Adults","Families","Community"],
    counties:["Jackson","Josephine"],
    cost:"Free and confidential",
    phone:"211 / 866-698-6155",
    address:"Oregon",
    website:"https://www.211info.org/",
    labels:["211","START HERE","RESOURCE NAVIGATION"],
    keywords:["211","emergency resources","food","shelter","rent","utilities","help now"],
    lastVerified:"2026-08-31"
  },
  {
    id:"oregon-safe-line",
    category:"emergency",
    name:"Call to Safety — Oregon Statewide Crisis Line",
    helps:"Confidential statewide advocacy and crisis support for domestic and sexual violence. Useful when a local program is unavailable or someone wants another confidential option.",
    audience:["Survivors","Friends","Family"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"888-235-5333",
    address:"Oregon statewide",
    website:"https://calltosafety.org/",
    labels:["DOMESTIC VIOLENCE","SEXUAL VIOLENCE","STATEWIDE"],
    keywords:["abuse","DV","rape","sexual assault","crisis line","safety planning"],
    lastVerified:"2026-08-31"
  },
  {
    id:"womens-crisis-support-team",
    category:"emergency",
    name:"Women’s Crisis Support Team — Josephine County",
    helps:"Free and confidential domestic-violence and sexual-assault advocacy for Josephine County survivors, including crisis support and help regaining safety and stability.",
    audience:["Women","Survivors","Families"],
    counties:["Josephine"],
    cost:"Free and confidential",
    phone:"541-479-9349 | 800-750-9278",
    address:"560-A NE F St, Grants Pass, OR 97526",
    website:"https://wcstjoco.org/",
    labels:["DOMESTIC VIOLENCE","SEXUAL ASSAULT","24/7"],
    keywords:["women crisis","domestic violence","sexual assault","abuse","Grants Pass","safe shelter"],
    lastVerified:"2026-08-31"
  },
  {
    id:"illinois-valley-safe-house",
    category:"emergency",
    name:"Illinois Valley Safe House Alliance",
    helps:"Domestic-violence and sexual-assault advocacy serving all of Josephine County, with an advocacy center in Cave Junction and outreach in rural Illinois Valley communities.",
    audience:["Survivors","Women","Families","Rural Residents"],
    counties:["Josephine"],
    cost:"Survivor advocacy services are free/confidential",
    phone:"541-592-2515",
    address:"Cave Junction, OR",
    website:"https://www.ivsha.org/",
    labels:["DOMESTIC VIOLENCE","SEXUAL ASSAULT","RURAL"],
    keywords:["Illinois Valley","Cave Junction","domestic violence","sexual assault","safe house","abuse"],
    lastVerified:"2026-08-31"
  },
  {
    id:"jackson-protective-order-help",
    category:"emergency",
    name:"Jackson County — Protective Order Help",
    helps:"Official court page for protective-order forms and local assistance. Community Works can help survivors with restraining-order filing, safety planning, court accompaniment and referrals.",
    audience:["Survivors","People Seeking Protective Orders"],
    counties:["Jackson"],
    cost:"Advocacy is free; court rules/fees depend on proceeding",
    phone:"Community Works HelpLine: 541-779-4357",
    address:"Jackson County Circuit Court, Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/help/pages/protective-orders.aspx",
    labels:["RESTRAINING ORDER","COURT HELP","SAFETY"],
    keywords:["restraining order","protective order","FAPA","stalking order","domestic violence court"],
    lastVerified:"2026-08-31"
  }
];
