/* Flourish Anyway Community Resource Hub
   LOCAL EVENTS & CALENDARS
   File name after upload: events-data.js
   Jackson + Josephine Counties, Oregon
   Uses official/local calendars and a few verified upcoming anchors.
   Events change quickly: always confirm on the linked source.
   Last researched: 2026-08-30
*/

window.FLOURISH_EVENTS_DATA = [
  {
    id:"jcls-events-calendar",
    category:"events",
    name:"Jackson County Library Services — Events Calendar",
    helps:"Live calendar for free library events across 15 Jackson County branches, including storytimes, crafts, STEM, teen programs, clubs, family events and classes.",
    audience:["Children","Teens","Families","Adults","Seniors"],
    counties:["Jackson"],
    cost:"Mostly free",
    phone:"541-774-8679",
    address:"15 branches across Jackson County",
    website:"https://jcls.org/events/",
    labels:["LIVE CALENDAR","FREE","LIBRARY","FAMILY"],
    keywords:["events","calendar","storytime","craft","STEM","library","free","teen","family"],
    lastVerified:"2026-08-30"
  },
  {
    id:"josephine-library-events-calendar",
    category:"events",
    name:"Josephine Community Library — Events & Programs",
    helps:"Current programs and events through the Grants Pass, Illinois Valley, Williams and Wolf Creek library branches.",
    audience:["Children","Teens","Families","Adults","Seniors"],
    counties:["Josephine"],
    cost:"Mostly free",
    phone:"541-476-0571",
    address:"Josephine County library branches",
    website:"https://josephinelibrary.org/",
    labels:["LIVE PROGRAMS","FREE","LIBRARY","JOSEPHINE"],
    keywords:["events","library","Grants Pass","Illinois Valley","Williams","Wolf Creek","storytime"],
    lastVerified:"2026-08-30"
  },
  {
    id:"scienceworks-calendar",
    category:"events",
    name:"ScienceWorks — Event Calendar",
    helps:"Current ScienceWorks calendar for hands-on science activities, camps, special programs and family museum events in Ashland.",
    audience:["Children","Families","School-Age Kids"],
    counties:["Jackson","Josephine"],
    cost:"Some events included with admission; special-event prices vary",
    phone:"541-482-6767",
    address:"1500 E Main St, Ashland, OR 97520",
    website:"https://www.scienceworksmuseum.org/calendar",
    labels:["LIVE CALENDAR","SCIENCE","FAMILY","ASHLAND"],
    keywords:["ScienceWorks","calendar","science","STEM","camp","family event"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-events-calendar",
    category:"events",
    name:"City of Medford — Community Events",
    helps:"Official Medford event listing for community events, fundraisers, family programs and seasonal activities.",
    audience:["Families","Children","Adults","Community"],
    counties:["Jackson"],
    cost:"Varies; many city events are free",
    phone:"541-774-2400",
    address:"Medford, OR",
    website:"https://www.medfordoregon.gov/Events-directory",
    labels:["CITY CALENDAR","MEDFORD","FAMILY"],
    keywords:["Medford events","festival","family","community","parks","calendar"],
    lastVerified:"2026-08-30"
  },
  {
    id:"grants-pass-calendar",
    category:"events",
    name:"City of Grants Pass — Community Calendar",
    helps:"Official Grants Pass calendar with city and community happenings. Users can browse by date and subscribe to calendar notifications.",
    audience:["Families","Adults","Community"],
    counties:["Josephine"],
    cost:"Varies",
    phone:"541-450-6110",
    address:"Grants Pass, OR",
    website:"https://www.grantspassoregon.gov/calendar.aspx",
    labels:["CITY CALENDAR","GRANTS PASS","SUBSCRIBE"],
    keywords:["Grants Pass events","calendar","community","festival","parks"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-doodle-palooza-2026",
    category:"events",
    name:"Doodle Palooza — Medford Parks",
    helps:"Community dog event presented through Medford Parks, Recreation and Facilities.",
    audience:["Families","Adults","Dog Owners"],
    counties:["Jackson"],
    cost:"Check official event listing",
    phone:"541-774-2400",
    address:"Walkabout Brewing Company, 921 Mason Way, Medford, OR 97501",
    website:"https://www.medfordoregon.gov/Events-directory",
    eventDate:"2026-10-09",
    labels:["OCTOBER 2026","COMMUNITY EVENT","MEDFORD"],
    keywords:["October","dog","Doodle Palooza","Medford","family"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-howl-o-ween-2026",
    category:"events",
    name:"Howl-O-Ween Family Party — Medford",
    helps:"Seasonal family event at RogueX presented by Medford Parks, Recreation and Facilities.",
    audience:["Children","Families"],
    counties:["Jackson"],
    cost:"Check official event listing",
    phone:"541-774-2400",
    address:"RogueX, 901 Rossanley Dr, Medford, OR 97501",
    website:"https://www.medfordoregon.gov/Events-directory",
    eventDate:"2026-10-23",
    labels:["OCTOBER 2026","KIDS & FAMILY","MEDFORD"],
    keywords:["Halloween","Howl-O-Ween","family dance","RogueX","October"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-winter-lights-2026",
    category:"events",
    name:"Winter Lights Festival — Medford",
    helps:"Annual holiday-season community celebration at Pear Blossom Park.",
    audience:["Children","Families","Community"],
    counties:["Jackson"],
    cost:"Check official event listing",
    phone:"541-774-2400",
    address:"Pear Blossom Park, 204 N Bartlett St, Medford, OR 97501",
    website:"https://www.medfordoregon.gov/Events-directory",
    eventDate:"2026-12-05",
    labels:["DECEMBER 2026","HOLIDAY","COMMUNITY"],
    keywords:["Winter Lights","Christmas","holiday","festival","Medford","December"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-breakfast-santa-2026",
    category:"events",
    name:"Breakfast with Santa — Medford",
    helps:"Holiday family event at RogueX listed by the City of Medford.",
    audience:["Children","Families"],
    counties:["Jackson"],
    cost:"Check official event listing",
    phone:"541-774-2400",
    address:"RogueX, 901 Rossanley Dr, Medford, OR 97501",
    website:"https://www.medfordoregon.gov/Events-directory",
    eventDate:"2026-12-12",
    labels:["DECEMBER 2026","KIDS & FAMILY","HOLIDAY"],
    keywords:["Santa","breakfast","Christmas","kids","RogueX","December"],
    lastVerified:"2026-08-30"
  }
,
  {
    id:"facebook-events-local",
    category:"events",
    name:"Facebook Events — Local Discovery",
    helps:"Use Facebook's Events area as an extra discovery tool for current local events. Results can vary by your Facebook account and location, so confirm details with the organizer before going.",
    audience:["Adults","Families","Community"],
    counties:["Jackson","Josephine"],
    cost:"Varies",
    address:"Online",
    website:"https://www.facebook.com/events/",
    labels:["FACEBOOK","LIVE DISCOVERY","COMMUNITY"],
    keywords:["Facebook events","local events","Medford events","Grants Pass events","community events"],
    lastVerified:"2026-08-31"
  },
  {
    id:"medford-fall-activity-guide-2026",
    category:"events",
    name:"Medford Parks & Recreation — Fall 2026 Activity Guide",
    helps:"Current seasonal guide with youth art, sports and skating, aquatics/swimming, adult programs, facility rentals and seasonal community events.",
    audience:["Children","Teens","Families","Adults"],
    counties:["Jackson"],
    cost:"Mix of free and paid programs",
    phone:"541-774-2400",
    address:"Medford, OR",
    website:"https://www.medfordoregon.gov/News-Articles/Explore-Medford-Parks-and-Recreation%E2%80%99s-Fall-2026-Activity-Guide",
    labels:["CURRENT","FALL 2026","KIDS","RECREATION"],
    keywords:["fall","2026","activities","sports","swimming","skating","kids","Medford","recreation"],
    lastVerified:"2026-08-31"
  },
  {
    id:"oregon-dmv-help-videos",
    category:"events",
    name:"Oregon DMV — How-to Videos",
    helps:"Official DMV2U how-to videos for common tasks such as renewing/replacing a license or ID, vehicle title, trip permits and vehicle registration renewal.",
    audience:["Adults","Drivers","Parents Helping Teens"],
    counties:["Jackson","Josephine"],
    cost:"Free videos",
    address:"Online",
    website:"https://www.oregon.gov/odot/dmv/pages/videos.aspx",
    labels:["OFFICIAL VIDEO","DMV","HOW-TO"],
    keywords:["YouTube","video","DMV","registration","title","license","DMV2U","how to"],
    lastVerified:"2026-08-31"
  },
  {
    id:"oha-recovery-videos",
    category:"events",
    name:"Oregon Health Authority — Recovery Program Stories & Videos",
    helps:"Official Oregon Health Authority videos and stories about Behavioral Health Resource Networks, treatment and recovery programs.",
    audience:["People in Recovery","Families","Community"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    address:"Online",
    website:"https://www.oregon.gov/oha/hsd/amh/pages/m110-videos.aspx",
    labels:["OFFICIAL VIDEO","RECOVERY","OHA"],
    keywords:["YouTube","video","recovery","substance use","OHA","BHRN"],
    lastVerified:"2026-08-31"
  }

];
