/* Flourish Anyway Community Resource Hub
   HOUSING, RENT & UTILITIES
   File name after upload: housing-data.js
   Jackson + Josephine Counties, Oregon
   Backbone: 211info + official local/state/provider sources
   Last researched: 2026-08-30
*/

window.FLOURISH_HOUSING_DATA = [
  {
    id:"access-rental-assistance",
    category:"housing",
    name:"ACCESS — Rental Assistance & Tenant Education",
    helps:"Rental-assistance navigation plus tenant education for low-income renters facing barriers such as poor credit, limited rental history, prior evictions or housing instability.",
    audience:["Adults","Families","Low-income Renters"],
    counties:["Jackson"],
    cost:"Assistance/funding varies; classes may have reimbursement available",
    phone:"541-779-6691",
    address:"3630 Aviation Way, Medford, OR 97504",
    website:"https://accesshelps.org/rental-assistance/",
    apply:"https://accesshelps.org/rental-assistance/",
    source211:"https://www.211info.org/",
    labels:["RENT","TENANT EDUCATION","JACKSON"],
    keywords:["rent","rental assistance","tenant","eviction","credit","RentWell"],
    lastVerified:"2026-08-30"
  },
  {
    id:"access-energy",
    category:"housing",
    name:"ACCESS — Energy Assistance",
    helps:"Utility-bill assistance for eligible Jackson County households. ACCESS provides online appointment scheduling and document instructions.",
    audience:["Adults","Families","Seniors","Disability"],
    counties:["Jackson"],
    cost:"Income/household eligibility and funding apply",
    phone:"541-779-6691",
    address:"3630 Aviation Way, Medford, OR 97504",
    website:"https://accesshelps.org/energy-assistance/",
    apply:"https://accesshelps.org/energy-assistance/",
    source211:"https://www.211info.org/",
    labels:["UTILITIES","ENERGY","JACKSON"],
    keywords:["electric","gas","utility","power bill","energy","shutoff"],
    lastVerified:"2026-08-30"
  },
  {
    id:"access-veterans-ssvf",
    category:"housing",
    name:"ACCESS — Supportive Services for Veteran Families",
    helps:"Short-term housing intervention for veterans and veteran families, including case management, move-in costs, rental assistance, eviction prevention, benefits, employment/education support and housing-related legal aid.",
    audience:["Veterans","Veteran Families"],
    counties:["Jackson"],
    cost:"Free if eligible; funding-dependent",
    phone:"458-488-1340",
    address:"3630 Aviation Way, Medford, OR 97504",
    website:"https://accesshelps.org/",
    source211:"https://www.211info.org/get-help/housing-shelter/housing-related-coordinated-entry/?search_condition=143",
    labels:["VETERANS","RENT","MOVE-IN COSTS","EVICTION PREVENTION"],
    keywords:["veteran","SSVF","rent","deposit","housing","eviction"],
    lastVerified:"2026-08-30"
  },
  {
    id:"access-coordinated-entry",
    category:"housing",
    name:"ACCESS — Jackson County Coordinated Entry",
    helps:"Access point for Jackson County's centralized housing-interest list for people experiencing homelessness or severe housing instability.",
    audience:["Adults","Families","Unhoused"],
    counties:["Jackson"],
    cost:"Free assessment/navigation",
    phone:"541-779-6691",
    address:"Jackson County, Oregon",
    website:"https://accesshelps.org/",
    source211:"https://www.211info.org/get-help/housing-shelter/housing-related-coordinated-entry/?search_condition=143",
    labels:["COORDINATED ENTRY","HOMELESSNESS","JACKSON"],
    keywords:["coordinated entry","housing list","homeless","centralized interest list"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hajc-hcv",
    category:"housing",
    name:"Housing Authority of Jackson County — Housing Choice Voucher",
    helps:"Section 8/Housing Choice Voucher assistance for very low-income families in Jackson County. HAJC says the HCV waiting list is currently open.",
    audience:["Adults","Families","Seniors","Disability"],
    counties:["Jackson"],
    cost:"Income limits apply; participant generally pays a share of rent",
    phone:"541-779-5785",
    address:"2251 Table Rock Rd, Medford, OR 97501",
    website:"https://hajc.net/housing-programs/housing-choice-voucher/",
    apply:"https://hajc.net/housing-programs/housing-choice-voucher/",
    source211:"https://www.211info.org/",
    labels:["SECTION 8","OPEN WAITLIST","JACKSON"],
    keywords:["section 8","voucher","HCV","affordable housing","waitlist"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hajc-project-based",
    category:"housing",
    name:"Housing Authority of Jackson County — Project-Based Vouchers",
    helps:"Affordable housing where rental assistance is tied to specific units in Jackson County developments.",
    audience:["Adults","Families","Seniors","Disability"],
    counties:["Jackson"],
    cost:"Income limits apply",
    phone:"541-779-5785",
    address:"2251 Table Rock Rd, Medford, OR 97501",
    website:"https://hajc.net/housing-programs/housing-choice-voucher/",
    apply:"https://hajc.net/housing-programs/housing-choice-voucher/",
    source211:"https://www.211info.org/",
    labels:["PROJECT-BASED","AFFORDABLE HOUSING"],
    keywords:["project based voucher","PBV","apartment","affordable"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hajc-ned",
    category:"housing",
    name:"Housing Authority of Jackson County — Non-Elderly Disabled Vouchers",
    helps:"Special-purpose vouchers for eligible non-elderly adults with disabilities who are homeless, at risk of homelessness or transitioning from an institution.",
    audience:["Adults under 62","Disability"],
    counties:["Jackson"],
    cost:"Income and program eligibility apply",
    phone:"541-779-5785",
    address:"2251 Table Rock Rd, Medford, OR 97501",
    website:"https://hajc.net/housing-programs/housing-choice-voucher/",
    source211:"https://www.211info.org/",
    labels:["DISABILITY","VOUCHER","HOUSING"],
    keywords:["disabled","NED voucher","non elderly disabled","homeless"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medford-navigation-center",
    category:"housing",
    name:"Medford Navigation Center",
    helps:"24/7 emergency shelter with connections to health services, public benefits, permanent housing and other services for unhoused individuals and families.",
    audience:["Adults","Families","Seniors","Disability","Unhoused"],
    counties:["Jackson"],
    cost:"Emergency shelter program",
    phone:"",
    address:"Medford, OR",
    website:"https://www.medfordoregon.gov/Government/Departments/Planning/Housing-and-Community-Development/Addressing-Homelessness/Medford-Navigation-Center",
    source211:"https://www.211info.org/",
    labels:["24/7 SHELTER","FAMILIES","HOUSING NAVIGATION"],
    keywords:["shelter","navigation center","homeless","family","Medford"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rogue-retreat-kelly",
    category:"housing",
    name:"Rogue Retreat — Kelly Shelter",
    helps:"Congregate shelter for adults and couples with case management, meals, showers and laundry. 211 lists medical-respite capacity and notes dogs may enter with owners.",
    audience:["Adults 18+","Couples","Unhoused"],
    counties:["Jackson"],
    cost:"Shelter program",
    phone:"541-499-0880",
    address:"Medford, OR",
    website:"https://rogueretreat.org/get-help/",
    source211:"https://www.211info.org/get-help/housing-shelter/community-shelters/?search_condition=140",
    labels:["SHELTER","CASE MANAGEMENT","PETS"],
    keywords:["Kelly Shelter","Rogue Retreat","homeless","shelter","dogs"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rogue-retreat-housing",
    category:"housing",
    name:"Rogue Retreat — Housing & Community Living",
    helps:"Shelter, housing-first and supportive-housing programs intended to move people from homelessness toward stable housing.",
    audience:["Adults","Families","Unhoused"],
    counties:["Jackson"],
    cost:"Program-specific",
    phone:"541-499-0880",
    address:"711 E Main St #25, Medford, OR 97504",
    website:"https://rogueretreat.org/get-help/",
    apply:"https://rogueretreat.org/get-help/",
    source211:"https://www.211info.org/",
    labels:["HOUSING FIRST","SUPPORTIVE HOUSING"],
    keywords:["Rogue Retreat","housing first","supportive housing","community living"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ohra-ashland-shelter",
    category:"housing",
    name:"OHRA — Emergency Shelter",
    helps:"Low-barrier emergency shelter in Ashland for adults age 18+.",
    audience:["Adults 18+","Unhoused"],
    counties:["Jackson"],
    cost:"Shelter program",
    phone:"541-631-2235",
    address:"2350 Ashland St, Ashland, OR 97520",
    website:"https://helpingashland.org/",
    source211:"https://www.211info.org/get-help/housing-shelter/community-shelters/?search_condition=140",
    labels:["SHELTER","ASHLAND","LOW BARRIER"],
    keywords:["OHRA","Ashland","shelter","homeless"],
    lastVerified:"2026-08-30"
  },
  {
    id:"st-anthony-family-shelter",
    category:"housing",
    name:"St. Vincent de Paul Medford — St. Anthony Emergency Family Shelter",
    helps:"Emergency shelter for homeless families, including single parents and couples with children.",
    audience:["Families","Parents","Children"],
    counties:["Jackson"],
    cost:"Free shelter program",
    phone:"541-772-3828",
    address:"2424 N Pacific Hwy, Medford, OR 97501",
    website:"https://www.211info.org/get-help/housing-shelter/community-shelters-homeless-families/",
    source211:"https://www.211info.org/get-help/housing-shelter/community-shelters-homeless-families/",
    labels:["FAMILY SHELTER","CHILDREN","MEDFORD"],
    keywords:["family shelter","St Anthony","children","homeless family"],
    lastVerified:"2026-08-30"
  },
  {
    id:"st-vincent-medford-rent-utilities",
    category:"housing",
    name:"St. Vincent de Paul Medford — Rent & Utility Assistance",
    helps:"Help with rent and electric, gas or water bills as funding allows. 211 notes assistance may be available once every 24 months and does not cover eviction prevention.",
    audience:["Adults","Families","Housed Households"],
    counties:["Jackson"],
    cost:"Free assistance if eligible and funding is available",
    phone:"541-772-3828",
    address:"2424 N Pacific Hwy, Medford, OR 97501",
    website:"https://gethelp.211info.org/agency/8934/6612/",
    source211:"https://gethelp.211info.org/agency/8934/6612/",
    labels:["RENT","ELECTRIC","GAS","WATER"],
    keywords:["rent help","utility","St Vincent","water","gas","electric"],
    lastVerified:"2026-08-30"
  },

  {
    id:"jhcdc-section8",
    category:"housing",
    name:"Josephine Housing & Community Development Council — Section 8",
    helps:"Local Josephine County housing authority administering Housing Choice Voucher rental assistance.",
    audience:["Adults","Families","Seniors","Disability"],
    counties:["Josephine"],
    cost:"Income limits apply",
    phone:"541-479-5529",
    address:"1205 NE 7th St, Grants Pass, OR 97526",
    website:"https://www.jhcdc.net/applicants/",
    apply:"https://www.jhcdc.net/applicants/",
    source211:"https://www.211info.org/",
    labels:["SECTION 8","JOSEPHINE","HOUSING AUTHORITY"],
    keywords:["section 8","voucher","Josephine Housing Council","HCV","rent"],
    lastVerified:"2026-08-30"
  },
  {
    id:"jhcdc-harbeck",
    category:"housing",
    name:"Josephine Housing & Community Development Council — Harbeck Village",
    helps:"Affordable tax-credit housing owned by the Josephine Housing Council; contact the council for current availability and waiting-list status.",
    audience:["Families","Low-income Renters"],
    counties:["Josephine"],
    cost:"Income restrictions may apply",
    phone:"541-479-5529",
    address:"1760 Harbeck Rd, Grants Pass, OR",
    website:"https://www.jhcdc.net/",
    source211:"https://www.211info.org/",
    labels:["AFFORDABLE HOUSING","JOSEPHINE"],
    keywords:["Harbeck Village","affordable apartment","Josephine"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ucan-housing-homeless",
    category:"housing",
    name:"UCAN — Josephine County Housing & Homeless Services",
    helps:"Housing help for people who lack housing, need better housing or need help remaining housed.",
    audience:["Adults","Families","Unhoused"],
    counties:["Josephine"],
    cost:"Eligibility and funding vary",
    phone:"541-956-4050",
    address:"900 SE 8th St, Grants Pass, OR 97526",
    website:"https://www.ucancap.org/josephine-county-programs/",
    apply:"https://www.ucancap.org/josephine-county-programs/",
    source211:"https://www.211info.org/",
    labels:["HOUSING","HOMELESSNESS","JOSEPHINE"],
    keywords:["UCAN","housing","homeless","rent","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ucan-utility",
    category:"housing",
    name:"UCAN — Utility Assistance",
    helps:"Utility-bill assistance for eligible Josephine County households; UCAN schedules appointments and lists required documentation.",
    audience:["Adults","Families","Seniors","Disability"],
    counties:["Josephine"],
    cost:"Income guidelines and funding apply",
    phone:"800-301-8226",
    address:"900 SE 8th St, Grants Pass, OR 97526",
    website:"https://www.ucancap.org/utility-bill/",
    apply:"https://www.ucancap.org/utility-bill/",
    source211:"https://www.211info.org/",
    labels:["UTILITIES","JOSEPHINE","ENERGY"],
    keywords:["UCAN","utility","electric","energy","bill","shutoff"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ucan-weatherization",
    category:"housing",
    name:"UCAN — Weatherization",
    helps:"Free home weatherization for eligible Josephine County households to improve comfort and reduce energy use.",
    audience:["Adults","Families","Homeowners","Renters"],
    counties:["Josephine"],
    cost:"Free if eligible",
    phone:"541-956-4050",
    address:"900 SE 8th St, Grants Pass, OR 97526",
    website:"https://www.ucancap.org/josephine-county-programs/",
    apply:"https://www.ucancap.org/josephine-county-programs/",
    source211:"https://www.211info.org/",
    labels:["WEATHERIZATION","ENERGY","HOME REPAIR"],
    keywords:["weatherization","insulation","energy efficiency","UCAN","home"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ucan-veterans",
    category:"housing",
    name:"UCAN — Supportive Services for Veteran Families",
    helps:"Housing stabilization for veterans and veteran families, including case management, rapid rehousing, homelessness prevention and temporary financial assistance for urgent needs.",
    audience:["Veterans","Veteran Families"],
    counties:["Josephine"],
    cost:"Free if eligible; funding-dependent",
    phone:"541-956-4050",
    address:"900 SE 8th St, Grants Pass, OR 97526",
    website:"https://www.ucancap.org/josephine-county-programs/",
    source211:"https://www.211info.org/",
    labels:["VETERANS","SSVF","HOUSING"],
    keywords:["veteran","SSVF","rapid rehousing","rent","homeless"],
    lastVerified:"2026-08-30"
  },
  {
    id:"grants-pass-gospel-men",
    category:"housing",
    name:"Gospel Rescue Mission — Men's Residence",
    helps:"Shelter and pathway-to-independence services for homeless men in Grants Pass.",
    audience:["Men","Adults","Unhoused"],
    counties:["Josephine"],
    cost:"Shelter program",
    phone:"541-476-0082",
    address:"540 SW Foundry St, Grants Pass, OR 97526",
    website:"https://gospelrescuemissiongp.org/contact/",
    source211:"https://www.211info.org/",
    labels:["MEN","SHELTER","GRANTS PASS"],
    keywords:["Gospel Rescue Mission","men","shelter","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"fikso-family-center",
    category:"housing",
    name:"Gospel Rescue Mission — Fikso Family Center Women's Shelter",
    helps:"24/7 shelter for single women and women with children; 211 lists intake on weekday mornings.",
    audience:["Women","Women with Children","Families"],
    counties:["Josephine"],
    cost:"Shelter program",
    phone:"541-200-6242",
    address:"530 SW Foundry St, Grants Pass, OR 97526",
    website:"https://gospelrescuemissiongp.org/contact/",
    source211:"https://www.211info.org/get-help/housing-shelter/community-shelters-homeless-families/",
    labels:["WOMEN","CHILDREN","SHELTER","GRANTS PASS"],
    keywords:["Fikso","women shelter","children","family shelter","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hearts-grants-pass-shelter",
    category:"housing",
    name:"Hearts With A Mission — Grants Pass Youth Shelter",
    helps:"24-hour shelter and support for homeless or at-risk youth in Josephine County.",
    audience:["Youth","Teens"],
    counties:["Josephine"],
    cost:"Free/community program",
    phone:"541-956-4190",
    address:"1504 NE 9th St, Grants Pass, OR",
    website:"https://heartswithamission.org/",
    source211:"https://www.grantspassoregon.gov/1808/Homeless-Assistance--Shelters-Showers-Cl",
    labels:["YOUTH SHELTER","24/7","GRANTS PASS"],
    keywords:["teen shelter","youth homeless","Hearts With A Mission"],
    lastVerified:"2026-08-30"
  },
  {
    id:"maslow-grants-pass-housing",
    category:"housing",
    name:"Maslow Project — Grants Pass Housing Support",
    helps:"Housing and basic-needs support for homeless or housing-insecure youth and families.",
    audience:["Youth","Young Adults","Families","Parents"],
    counties:["Josephine"],
    cost:"Free for eligible participants",
    phone:"541-841-1974",
    address:"223 SE M St, Grants Pass, OR 97526",
    website:"https://www.maslowproject.com/get-help/",
    source211:"https://www.grantspassoregon.gov/1808/Homeless-Assistance--Shelters-Showers-Cl",
    labels:["YOUTH","FAMILIES","HOUSING"],
    keywords:["Maslow","homeless youth","family housing","Grants Pass"],
    lastVerified:"2026-08-30"
  },

  {
    id:"community-works-dv-housing",
    category:"housing",
    name:"Community Works — Domestic Violence Safety & Shelter",
    helps:"Confidential safety planning and emergency support for people fleeing domestic violence, sexual assault, stalking or trafficking; call the 24/7 HelpLine for current shelter/housing options.",
    audience:["Women","Adults","Youth","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free and confidential",
    phone:"541-779-4357",
    address:"Southern Oregon",
    website:"https://www.community-works.org/",
    source211:"https://www.211info.org/",
    labels:["DOMESTIC VIOLENCE","CONFIDENTIAL","SHELTER"],
    keywords:["domestic violence","abuse","safe shelter","women","trafficking"],
    lastVerified:"2026-08-30"
  },
  {
    id:"odhs-dv-medford-housing",
    category:"housing",
    name:"ODHS Medford — Temporary Assistance for Domestic Violence Survivors",
    helps:"Short-term financial assistance that may help eligible families with rent or utility deposits, moving costs, locks, security items and essential household replacement.",
    audience:["Pregnant People","Parents","Families","Domestic Violence Survivors"],
    counties:["Jackson"],
    cost:"TANF income eligibility applies",
    phone:"",
    address:"673 Market St, Medford, OR 97504",
    website:"https://www.211info.org/agency/6614/16767/",
    source211:"https://www.211info.org/agency/6614/16767/",
    labels:["DOMESTIC VIOLENCE","DEPOSIT","MOVING COSTS"],
    keywords:["domestic violence","rent deposit","utility deposit","moving","TANF"],
    lastVerified:"2026-08-30"
  },
  {
    id:"odhs-dv-grants-pass-housing",
    category:"housing",
    name:"ODHS Grants Pass — Temporary Assistance for Domestic Violence Survivors",
    helps:"Short-term financial assistance that may help eligible families with rent or utility deposits, moving costs, locks, security items and essential household replacement.",
    audience:["Pregnant People","Parents","Families","Domestic Violence Survivors"],
    counties:["Josephine"],
    cost:"TANF income eligibility applies",
    phone:"",
    address:"2101 NW Hawthorne Ave, Suite B, Grants Pass, OR 97526",
    website:"https://www.211info.org/agency/28337/16767/",
    source211:"https://www.211info.org/agency/28337/16767/",
    labels:["DOMESTIC VIOLENCE","DEPOSIT","MOVING COSTS"],
    keywords:["domestic violence","rent deposit","utility deposit","moving","TANF"],
    lastVerified:"2026-08-30"
  },
  {
    id:"fair-housing-council",
    category:"housing",
    name:"Fair Housing Council of Oregon",
    helps:"Information and help related to illegal housing discrimination across Oregon.",
    audience:["Renters","Homebuyers","People with Disabilities","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free information/advocacy services",
    phone:"800-424-3247",
    address:"Statewide Oregon",
    website:"https://fhco.org/",
    source211:"https://www.211info.org/",
    labels:["FAIR HOUSING","DISCRIMINATION","TENANT RIGHTS"],
    keywords:["housing discrimination","fair housing","disability","landlord"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ohcs-housing-support",
    category:"housing",
    name:"Oregon Housing & Community Services",
    helps:"State housing agency funding rental assistance, homelessness services, affordable housing, utility help, weatherization, homebuyer programs and wildfire/disaster housing recovery through local partners.",
    audience:["Adults","Families","Renters","Homeowners"],
    counties:["Jackson","Josephine"],
    cost:"Program-specific",
    phone:"503-986-2000",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/ohcs/",
    source211:"https://www.211info.org/agency/4074/3079/",
    labels:["STATE HOUSING","RENT","UTILITIES","HOMEOWNERSHIP"],
    keywords:["OHCS","rent assistance","affordable housing","weatherization","homebuyer"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ohp-flex-housing",
    category:"housing",
    name:"Oregon Health Plan / CCO Flexible Services — Housing Support",
    helps:"Some Oregon Health Plan coordinated care organizations may approve flexible services such as rent, rental deposits, utility bills or temporary motel stays when the request supports health needs.",
    audience:["OHP Members","Families","People with Health Needs"],
    counties:["Jackson","Josephine"],
    cost:"Covered only when approved by the member's CCO",
    phone:"",
    address:"Oregon Health Plan / local CCO",
    website:"https://www.211info.org/agency/13455/24583/",
    source211:"https://www.211info.org/agency/13455/24583/",
    labels:["OHP","RENT","DEPOSIT","MOTEL","UTILITIES"],
    keywords:["OHP","flex funds","rent","deposit","motel","utility","CCO"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-housing-search",
    category:"housing",
    name:"211info — Housing, Rent, Shelter & Utility Search",
    helps:"Search Oregon's larger live directory for rental assistance, emergency shelter, affordable housing, deposits, utility help and coordinated-entry programs not yet individually listed in the Flourish hub.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    apply:"https://www.211info.org/get-help/housing-shelter/",
    labels:["211","LIVE DIRECTORY","CATCH-ALL"],
    keywords:["211","housing","rent","shelter","utility","deposit","homeless"],
    lastVerified:"2026-08-30"
  },
  {
    id:"access-get-help-directory",
    category:"housing",
    name:"ACCESS — Jackson County Get Help Directory",
    helps:"One starting page for Jackson County food, energy, rental assistance, housing/shelter, Veterans help, affordable housing and resource navigation.",
    audience:["Adults","Families","Seniors","Veterans","People with Disabilities"],
    counties:["Jackson"],
    cost:"Varies by program and funding",
    phone:"541-779-6691",
    address:"3630 Aviation Way, Medford, OR 97504",
    website:"https://accesshelps.org/get-help/",
    labels:["START HERE","JACKSON","HOUSING","UTILITIES"],
    keywords:["ACCESS","rent","utility","shelter","food","housing","Jackson County"],
    lastVerified:"2026-08-31"
  },
  {
    id:"access-outreach-navigation",
    category:"housing",
    name:"ACCESS — Homeless Outreach & Resource Navigation",
    helps:"Jackson County outreach and resource navigation for people who are homeless or unstably housed. ACCESS can connect people with shelter pathways, housing stabilization, food, health care, clothing, peer support and other services.",
    audience:["Unhoused Adults","Families","People in Crisis"],
    counties:["Jackson"],
    cost:"Free navigation; program eligibility varies",
    phone:"541-200-3684",
    address:"Walk-In Wednesdays: 110 N Ivy St, Medford, OR",
    website:"https://accesshelps.org/resource-navigation/",
    labels:["HOMELESS OUTREACH","WALK-IN","RESOURCE NAVIGATION"],
    keywords:["homeless","shelter","outreach","resource navigation","Medford","walk in","pet friendly","family friendly"],
    lastVerified:"2026-08-31"
  },
  {
    id:"ucan-josephine-service-center",
    category:"housing",
    name:"UCAN — Josephine County Service Center",
    helps:"Josephine County starting point for housing/homeless services, Veterans housing, utility assistance and weatherization. UCAN also operates food, family-development and other anti-poverty programs.",
    audience:["Adults","Families","Veterans","Low-Income Households"],
    counties:["Josephine"],
    cost:"Program eligibility and funding vary",
    phone:"541-956-4050",
    address:"900 SE 8th St, Grants Pass, OR 97526",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["START HERE","JOSEPHINE","HOUSING","UTILITIES"],
    keywords:["UCAN","Grants Pass","rent","homeless","utility","weatherization","veteran housing"],
    lastVerified:"2026-08-31"
  },
  {
    id:"medford-community-resource-directory",
    category:"housing",
    name:"City of Medford — Community Resource Directory",
    helps:"City-maintained resource page linking local rental/housing help, legal/fair-housing services, senior/disability resources, youth/family services and broader community guides.",
    audience:["Adults","Families","Community Navigators"],
    counties:["Jackson"],
    cost:"Directory is free; linked programs vary",
    address:"Medford, OR",
    website:"https://www.medfordoregon.gov/Government/Departments/Planning/Housing-and-Community-Development/Community-Resources",
    labels:["DIRECTORY","MEDFORD","COMMUNITY RESOURCES"],
    keywords:["community directory","housing list","rent help","youth services","senior services","Medford resources"],
    lastVerified:"2026-08-31"
  }
];
