/* Flourish Anyway Community Resource Hub
   HOUSING, RENT & UTILITIES — SEPTEMBER 2026 VERIFIED REBUILD
   Upload as: housing-data.js
   Jackson + Josephine Counties, Oregon
   Structure: situation-based sections; one real program/provider per card unless clearly labeled as a directory.
   Closed programs are not presented as active.
*/

window.FLOURISH_HOUSING_DATA = [
  {
    id:"access-rental-assistance",
    category:"housing",
    section:"Rent & Staying Housed",
    name:"ACCESS — Rental Assistance & Eviction Prevention",
    helps:"Jackson County rental assistance, case management and eviction-prevention help for qualifying households. Funding is limited, so apply early and do not wait until the final court date.",
    audience:["Renters", "Families", "Adults", "Seniors"],
    counties:["Jackson"],
    cost:"Eligibility and funding apply",
    phone:"541-414-0317",
    address:"3630 Aviation Way, Medford",
    website:"https://accesshelps.org/rental-assistance/",
    labels:["RENT", "EVICTION PREVENTION", "JACKSON"],
    keywords:["rent assistance", "eviction", "past due rent", "housing stability", "ACCESS"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ucan-housing-homeless",
    category:"housing",
    section:"Rent & Staying Housed",
    name:"UCAN — Josephine County Housing & Homeless Services",
    helps:"Josephine County front door for people who need help remaining housed, need better housing, or are homeless. Housing services may include rent assistance and housing navigation depending on current funding and eligibility.",
    audience:["Renters", "Families", "Adults", "Unhoused"],
    counties:["Josephine"],
    cost:"Eligibility and funding vary",
    phone:"541-956-4050",
    address:"900 SE 8th Street, Grants Pass",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["RENT", "HOUSING STABILITY", "JOSEPHINE"],
    keywords:["UCAN", "rent assistance", "housing help", "Grants Pass", "homeless"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-rent-well",
    category:"housing",
    section:"Deposits, Moving In & Rental Barriers",
    name:"ACCESS — Rent Well Tenant Education",
    helps:"Tenant-education program for people facing rental barriers such as poor credit, past evictions, criminal history, no rental history or homelessness. Graduates receive an OHCS Rent Well certificate that can be shown to landlords and property managers.",
    audience:["Renters", "People with Rental Barriers"],
    counties:["Jackson"],
    cost:"Low-cost/free depending on program; ask ACCESS",
    phone:"541-779-6691",
    address:"Medford",
    website:"https://accesshelps.org/rental-assistance/",
    labels:["RENT WELL", "BAD CREDIT", "PAST EVICTION", "RENTAL BARRIERS"],
    keywords:["Rent Well", "deposit", "bad credit", "eviction history", "criminal history", "rental approval"],
    lastVerified:"2026-09-04"
  },
  {
    id:"maslow-medford-housing",
    category:"housing",
    section:"Families, Youth & Couch Surfing",
    name:"Maslow Project — Medford Resource Center",
    helps:"Housing navigation and support for young people age 24 and younger and for parents/guardians of school-age children or younger who are homeless, couch surfing, living in motels, cars, trailers, shelters, camping or unsafe temporary housing. Deposit/fee help may be available when eligible.",
    audience:["Youth 24 and Under", "Young Parents", "Families with School-Age Children"],
    counties:["Jackson"],
    cost:"Free",
    phone:"541-608-6868",
    address:"500 Monroe Street, Medford",
    website:"https://www.maslowproject.com/",
    labels:["YOUTH", "FAMILIES", "COUCH SURFING", "MOTEL", "CAR"],
    keywords:["Maslow", "couch surfing", "motel", "living in car", "young parent", "deposit", "family homelessness"],
    lastVerified:"2026-09-04"
  },
  {
    id:"maslow-grants-pass-housing",
    category:"housing",
    section:"Families, Youth & Couch Surfing",
    name:"Maslow Project — Grants Pass Resource Center",
    helps:"Josephine County support for young people age 24 and younger and parents/guardians with school-age children or younger who are couch surfing, in motels, cars, trailers, shelters, camping or otherwise unstably housed.",
    audience:["Youth 24 and Under", "Young Parents", "Families with School-Age Children"],
    counties:["Josephine"],
    cost:"Free",
    phone:"541-841-1974",
    address:"223 SE M Street, Grants Pass",
    website:"https://www.maslowproject.com/",
    labels:["YOUTH", "FAMILIES", "COUCH SURFING", "JOSEPHINE"],
    keywords:["Maslow", "Grants Pass", "couch surfing", "family homelessness", "motel", "car"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-hcv",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — Housing Choice Voucher / Section 8",
    helps:"Tenant-based rental assistance for eligible households. Participants generally pay a share based on income and the Housing Authority pays the approved subsidy directly to the landlord. Current wait times are long, so this is long-term housing help, not emergency rent assistance.",
    audience:["Low-Income Households", "Families", "Seniors", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Income-qualified; waitlist applies",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["SECTION 8", "HCV", "LONG WAIT", "LONG-TERM"],
    keywords:["Housing Choice Voucher", "Section 8", "voucher", "waitlist", "HAJC"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-project-based",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — Project-Based Voucher Housing",
    helps:"Project-based voucher apartments tie the rental subsidy to a specific property rather than to the tenant. Applications and waitlists are property-specific.",
    audience:["Low-Income Households", "Families", "Seniors", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Income-qualified; property waitlists apply",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["PROJECT-BASED VOUCHER", "AFFORDABLE HOUSING"],
    keywords:["PBV", "project based voucher", "subsidized apartment", "income based housing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-ned",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — Non-Elderly Disabled Vouchers",
    helps:"Voucher pathway for qualifying non-elderly adults with disabilities. Availability and waitlist rules can change; use HAJC's current voucher information.",
    audience:["Adults with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Income and program eligibility apply",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["DISABILITY", "VOUCHER", "NED"],
    keywords:["non elderly disabled", "NED voucher", "disability housing", "Section 8"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-vash",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — HUD-VASH Veteran Vouchers",
    helps:"Housing voucher pathway coordinated with VA case management for eligible veterans experiencing homelessness or serious housing instability.",
    audience:["Veterans", "Veteran Families"],
    counties:["Jackson", "Josephine"],
    cost:"Program eligibility applies",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["VETERANS", "HUD-VASH", "VOUCHER"],
    keywords:["HUD VASH", "veteran housing voucher", "VA housing", "homeless veteran"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-properties",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — Affordable Rental Properties",
    helps:"HAJC owns or manages a large portfolio of affordable apartments across Southern Oregon. Some are income-restricted or subsidized; others are simply priced below market, so rent is not always calculated as a percentage of household income.",
    audience:["Low-Income Households", "Workforce Households", "Seniors", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Property-specific rents, income limits and waitlists",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["AFFORDABLE APARTMENTS", "PROPERTY WAITLISTS"],
    keywords:["affordable apartments", "HAJC properties", "income based", "below market rent", "rural development"],
    lastVerified:"2026-09-04"
  },
  {
    id:"hajc-portability",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Housing Authority of Jackson County — Voucher Portability",
    helps:"For households that already have a Housing Choice Voucher and need to move it into or out of the HAJC service area. Portability is different from applying for a new voucher.",
    audience:["Current Housing Choice Voucher Holders"],
    counties:["Jackson", "Josephine"],
    cost:"No new voucher; existing-voucher rules apply",
    address:"Southern Oregon",
    website:"https://hajc.net/",
    labels:["PORTABILITY", "EXISTING VOUCHER"],
    keywords:["port voucher", "move Section 8", "portable voucher", "HAJC"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-housing-authority",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Josephine Housing & Community Development Council",
    helps:"Local Josephine County housing authority/community development organization. The City of Grants Pass identifies it as a local affordable-housing and voucher resource.",
    audience:["Low-Income Households", "Families", "Seniors", "People with Disabilities"],
    counties:["Josephine"],
    cost:"Program-specific",
    phone:"541-479-5529",
    address:"1205 NE 7th Street, Grants Pass",
    website:"https://www.jhcdc.net/",
    labels:["JOSEPHINE", "HOUSING AUTHORITY", "AFFORDABLE HOUSING"],
    keywords:["Josephine housing authority", "JHCDC", "voucher", "affordable apartment", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"allen-creek-open-now",
    category:"housing",
    section:"Affordable Housing & Section 8",
    name:"Allen Creek Apartments — Lottery Waitlist OPEN Sept. 1–15, 2026",
    helps:"Time-sensitive affordable housing opportunity in Grants Pass. HAJC's current notice says the initial lottery waitlist is open September 1 at 8:00 a.m. through September 15 at 4:30 p.m. Current listed rents are $870 for 1 bedroom, $1,040 for 2 bedrooms and $1,200 for 3 bedrooms, with income limits.",
    audience:["Income-Qualified Renters", "Families"],
    counties:["Josephine"],
    cost:"Income limits apply; listed rents vary by bedroom",
    address:"Grants Pass",
    website:"https://hajc.net/",
    labels:["OPEN NOW", "LOTTERY", "SEPTEMBER 1–15", "GRANTS PASS"],
    keywords:["Allen Creek", "open waitlist", "lottery", "September 2026", "affordable apartment"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-energy",
    category:"housing",
    section:"Utilities — Electric, Gas, Propane, Oil & Wood",
    name:"ACCESS — Energy Assistance",
    helps:"Jackson County energy assistance for qualifying renters and homeowners. The program is fuel-blind and can help with electric, natural gas, propane, oil and wood. You do not have to already have a shutoff notice.",
    audience:["Renters", "Homeowners", "Families", "Seniors"],
    counties:["Jackson"],
    cost:"Income eligibility and funding apply",
    phone:"541-779-9020",
    address:"Jackson County",
    website:"https://accesshelps.org/energy-assistance/",
    labels:["ELECTRIC", "GAS", "PROPANE", "OIL", "WOOD"],
    keywords:["utility", "electric", "gas", "propane", "oil", "wood", "shutoff", "ACCESS"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ucan-utility",
    category:"housing",
    section:"Utilities — Electric, Gas, Propane, Oil & Wood",
    name:"UCAN — Utility Assistance",
    helps:"Josephine County utility assistance for eligible households. UCAN's current program guides applicants through required identification, utility/fuel documentation and household income information.",
    audience:["Renters", "Homeowners", "Families", "Seniors"],
    counties:["Josephine"],
    cost:"Income eligibility and funding apply",
    phone:"855-935-2542",
    address:"900 SE 8th Street, Grants Pass",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["UTILITIES", "JOSEPHINE", "SHUTOFF PREVENTION"],
    keywords:["utility assistance", "UCAN", "electric", "gas", "fuel", "shutoff", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ashland-utility-assistance",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Ashland — Utility Assistance Programs",
    helps:"Ashland-specific help for city electric, water and sewer customers. Current programs include a year-round 30% low-income discount with a maximum annual benefit and emergency HEAT assistance for qualifying households with a disconnect notice.",
    audience:["Ashland Utility Customers", "Low-Income Households"],
    counties:["Jackson"],
    cost:"Income and program rules apply",
    phone:"541-488-5306",
    address:"Ashland",
    website:"https://ashlandoregon.gov/utilityassistance",
    labels:["ASHLAND", "ELECTRIC", "WATER", "SEWER", "DISCOUNT"],
    keywords:["Ashland utility assistance", "HEAT", "30 percent discount", "disconnect notice", "water bill"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ashland-utilities",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Ashland — Utility Customer Service",
    helps:"Ashland combines city electricity, water and sewer on one monthly statement. Use this page for account questions, payment arrangements, starting/stopping service and billing support.",
    audience:["Ashland Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    address:"Ashland",
    website:"https://ashlandoregon.gov/utilities",
    labels:["ASHLAND", "UTILITY BILLING"],
    keywords:["Ashland utility bill", "payment plan", "electric", "water", "sewer"],
    lastVerified:"2026-09-04"
  },
  {
    id:"medford-utility-billing",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Medford — Utility Billing",
    helps:"Medford city utility billing for city service charges including sewer, storm-drain, streets, parks and public-safety-related fees. Use for account questions, payment options and city-bill issues.",
    audience:["Medford Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    phone:"541-774-2140",
    address:"411 W 8th Street, Medford",
    website:"https://www.medfordoregon.gov/Government/Departments/Finance/Utility-Billing",
    labels:["MEDFORD", "CITY UTILITIES"],
    keywords:["Medford utility bill", "sewer", "stormwater", "payment", "city bill"],
    lastVerified:"2026-09-04"
  },
  {
    id:"central-point-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Central Point — Utility Billing",
    helps:"Central Point bills city water, street and stormwater services. The city also identifies Pacific Power, Avista and Rogue Valley Sewer Services as separate utility providers.",
    audience:["Central Point Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    phone:"541-664-3321",
    address:"140 S 3rd Street, Central Point",
    website:"https://centralpointoregon.gov/172/Utility-Billing",
    labels:["CENTRAL POINT", "WATER", "STORMWATER"],
    keywords:["Central Point utility", "water bill", "street fee", "stormwater", "Pacific Power", "Avista"],
    lastVerified:"2026-09-04"
  },
  {
    id:"talent-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Talent — Utility Billing",
    helps:"Talent city water billing, account setup and billing support. Talent identifies Pacific Power for electricity, Avista for natural gas and Rogue Valley Sewer Services for sewer.",
    audience:["Talent Residents"],
    counties:["Jackson"],
    cost:"Utility charges and deposits apply",
    phone:"541-535-1566",
    address:"110 E Main Street, Talent",
    website:"https://www.cityoftalent.org/utility",
    labels:["TALENT", "WATER", "CITY UTILITIES"],
    keywords:["Talent utility bill", "water deposit", "Pacific Power", "Avista", "sewer"],
    lastVerified:"2026-09-04"
  },
  {
    id:"eagle-point-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Eagle Point — Utility Billing",
    helps:"Eagle Point provides water, street and stormwater service and bills for sewer service provided by Rogue Valley Sewer Services.",
    audience:["Eagle Point Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    phone:"541-826-4212",
    address:"17 Buchanan Avenue, Eagle Point",
    website:"https://www.cityofeaglepoint.org/156/Utility-Billing",
    labels:["EAGLE POINT", "WATER", "SEWER"],
    keywords:["Eagle Point utility bill", "water", "sewer", "stormwater"],
    lastVerified:"2026-09-04"
  },
  {
    id:"phoenix-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Phoenix — Water & Utility Billing",
    helps:"Phoenix municipal water billing and shutoff rules. The city may extend payment timing when hardship or extenuating circumstances are shown to the city manager or finance director; contact Utility Billing directly for current options.",
    audience:["Phoenix Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    phone:"541-535-1955",
    address:"Phoenix",
    website:"https://www.phoenixoregon.gov/",
    labels:["PHOENIX", "WATER", "PAYMENT HELP"],
    keywords:["Phoenix utility billing", "water bill", "shutoff", "hardship"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rogue-river-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Rogue River — Utility Billing",
    helps:"City administration handles Rogue River utility billing. Use the city contact page for account, payment and utility-billing questions.",
    audience:["Rogue River Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    phone:"541-582-4401",
    address:"133 Broadway Street, Rogue River",
    website:"https://cityofrogueriver.org/administration/",
    labels:["ROGUE RIVER", "CITY UTILITIES"],
    keywords:["Rogue River utility bill", "water", "city billing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jacksonville-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Jacksonville — Utility & City Service Questions",
    helps:"Jacksonville city contact point for local utility and municipal-service questions. Use the city site for current water, sewer and billing contacts.",
    audience:["Jacksonville Residents"],
    counties:["Jackson"],
    cost:"Utility charges apply",
    address:"Jacksonville",
    website:"https://www.jacksonvilleor.us/",
    labels:["JACKSONVILLE", "CITY UTILITIES"],
    keywords:["Jacksonville water", "utility bill", "sewer", "city service"],
    lastVerified:"2026-09-04"
  },
  {
    id:"grants-pass-utility",
    category:"housing",
    section:"Utilities — City Programs",
    name:"City of Grants Pass — Water & Wastewater Customer Service",
    helps:"Grants Pass water and sewer account information, payment/start-stop service and utility-bill customer service. The city identifies Pacific Power for electricity and Avista for natural gas.",
    audience:["Grants Pass Residents"],
    counties:["Josephine"],
    cost:"Utility charges and deposits apply",
    phone:"541-450-6035",
    address:"Grants Pass",
    website:"https://www.grantspassoregon.gov/983/Water-and-Wastewater-Information",
    labels:["GRANTS PASS", "WATER", "SEWER"],
    keywords:["Grants Pass utility", "water bill", "sewer", "Pacific Power", "Avista"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-weatherization",
    category:"housing",
    section:"Weatherization, Repairs & Home Safety",
    name:"ACCESS — Weatherization",
    helps:"Jackson County weatherization for qualifying homes to lower energy use and improve safety and comfort. Work may include insulation, air sealing, duct work, heating-system servicing and related energy improvements.",
    audience:["Renters", "Homeowners", "Manufactured Home Residents", "Families"],
    counties:["Jackson"],
    cost:"Free if eligible; funding rules apply",
    phone:"541-779-6691",
    address:"Jackson County",
    website:"https://accesshelps.org/",
    labels:["WEATHERIZATION", "ENERGY SAVINGS", "HOME SAFETY"],
    keywords:["weatherization", "insulation", "ducts", "furnace", "air sealing", "ACCESS"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ucan-weatherization",
    category:"housing",
    section:"Weatherization, Repairs & Home Safety",
    name:"UCAN — Weatherization",
    helps:"Josephine County weatherization for eligible renters, homeowners, manufactured homes and duplex residents. Work can include insulation, air sealing, duct improvements, heating-equipment servicing, ventilation, smoke/CO alarms and some health/safety repairs.",
    audience:["Renters", "Homeowners", "Manufactured Home Residents"],
    counties:["Josephine"],
    cost:"Free if eligible",
    phone:"541-956-4050",
    address:"900 SE 8th Street, Grants Pass",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["WEATHERIZATION", "JOSEPHINE", "HOME REPAIR"],
    keywords:["weatherization", "insulation", "furnace", "ducts", "manufactured home", "UCAN"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-weatherization",
    category:"housing",
    section:"Weatherization, Repairs & Home Safety",
    name:"Oregon Weatherization Assistance — State Program",
    helps:"State weatherization program delivered through local agencies. Services can include insulation, air sealing, heating-system work, duct improvements and energy-related minor repairs, with priority often given to high-burden households, seniors, people with disabilities and families with children.",
    audience:["Low-Income Households", "Seniors", "People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free if eligible",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ohcs/energy-weatherization/pages/weatherization-services.aspx",
    labels:["STATE WEATHERIZATION", "ENERGY"],
    keywords:["weatherization", "200 percent poverty", "insulation", "furnace", "energy burden"],
    lastVerified:"2026-09-04"
  },
  {
    id:"healthy-homes",
    category:"housing",
    section:"Weatherization, Repairs & Home Safety",
    name:"Oregon Health Authority — Healthy Homes",
    helps:"State Healthy Homes programs fund participating organizations to address housing-related health and safety hazards such as mold, lead, radon, indoor air quality, accessibility and other unhealthy-home conditions. Individuals apply through participating organizations rather than directly to the state.",
    audience:["Renters", "Homeowners", "Families", "People with Health Risks"],
    counties:["Jackson", "Josephine"],
    cost:"Program and local-provider rules vary",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/ph/healthyenvironments/healthyneighborhoods/healthyhomes/pages/index.aspx",
    labels:["MOLD", "LEAD", "RADON", "ACCESSIBILITY", "HEALTHY HOMES"],
    keywords:["mold", "lead", "radon", "unsafe home", "accessibility", "home repair"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-law-help-eviction",
    category:"housing",
    section:"Eviction, Lockout & Tenant Rights",
    name:"Oregon Law Help — Eviction & Renter Rights",
    helps:"Current Oregon renter guides on nonpayment notices, termination notices, eviction court, lockouts, landlord shutoffs and other tenant rights. A landlord generally cannot remove a tenant by simply changing locks, shutting off utilities or putting belongings outside without using the legal eviction process.",
    audience:["Renters", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free legal information",
    address:"Oregon statewide",
    website:"https://oregonlawhelp.org/topics/housing/rental-housing",
    labels:["EVICTION", "LOCKOUT", "TENANT RIGHTS"],
    keywords:["eviction notice", "lockout", "landlord shutoff", "nonpayment", "termination notice"],
    lastVerified:"2026-09-04"
  },
  {
    id:"cnpls-housing-crosslink",
    category:"housing",
    section:"Eviction, Lockout & Tenant Rights",
    name:"Center for NonProfit Legal Services — Jackson County Housing Law",
    helps:"Jackson County civil legal aid for eligible tenants facing eviction, landlord disputes and other housing-law problems.",
    audience:["Low-Income Renters", "Families"],
    counties:["Jackson"],
    cost:"Free/eligibility-based legal help",
    phone:"541-779-7292",
    address:"225 W Main Street, Medford",
    website:"https://cnpls.org/",
    labels:["LEGAL AID", "EVICTION", "JACKSON"],
    keywords:["tenant lawyer", "eviction legal aid", "landlord", "Jackson County"],
    lastVerified:"2026-09-04"
  },
  {
    id:"olc-housing-crosslink",
    category:"housing",
    section:"Eviction, Lockout & Tenant Rights",
    name:"Oregon Law Center — Josephine County Housing Law",
    helps:"Josephine County civil legal aid that prioritizes housing-law problems for eligible low-income residents, including eviction and other landlord-tenant issues.",
    audience:["Low-Income Renters", "Families"],
    counties:["Josephine"],
    cost:"Free for eligible clients",
    phone:"541-476-1058",
    address:"873 NE 7th Street, Suite A, Grants Pass",
    website:"https://oregonlawcenter.org/how-to-get-help/olc-offices/grants-pass/",
    labels:["LEGAL AID", "EVICTION", "JOSEPHINE"],
    keywords:["tenant lawyer", "eviction", "housing law", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"resolve-landlord-tenant",
    category:"housing",
    section:"Eviction, Lockout & Tenant Rights",
    name:"Resolve — Jackson County Landlord-Tenant Mediation",
    helps:"Mediation can be available for Jackson County residential landlord-tenant disputes, including cases referred through the Circuit Court. Mediation is different from legal representation and does not replace urgent court deadlines.",
    audience:["Renters", "Landlords"],
    counties:["Jackson"],
    cost:"Program-specific; court-connected mediation may be available",
    address:"Jackson County",
    website:"https://www.resolvecenter.org/",
    labels:["MEDIATION", "LANDLORD-TENANT", "JACKSON"],
    keywords:["Resolve", "mediation", "landlord tenant dispute", "eviction court"],
    lastVerified:"2026-09-04"
  },
  {
    id:"fhco",
    category:"housing",
    section:"Housing Discrimination & Disability Accommodations",
    name:"Fair Housing Council of Oregon",
    helps:"Fair-housing education and advocacy for people who believe they experienced housing discrimination. FHCO also provides guidance and forms for disability-related reasonable accommodations/modifications and assistance animals.",
    audience:["Renters", "Homebuyers", "People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and advocacy",
    phone:"800-424-3247",
    address:"Oregon statewide",
    website:"https://fhco.org/",
    labels:["FAIR HOUSING", "DISABILITY ACCOMMODATION", "ASSISTANCE ANIMALS"],
    keywords:["housing discrimination", "reasonable accommodation", "service animal", "assistance animal", "protected class"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-fair-housing-housing",
    category:"housing",
    section:"Housing Discrimination & Disability Accommodations",
    name:"BOLI — Fair Housing Complaints",
    helps:"Official Oregon civil-rights enforcement for housing discrimination. BOLI can investigate formal complaints involving protected-class discrimination in housing.",
    audience:["Renters", "Homebuyers", "People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free complaint process",
    phone:"971-245-3844",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/civil-rights/Pages/fair-housing.aspx",
    labels:["DISCRIMINATION", "COMPLAINT", "BOLI"],
    keywords:["fair housing complaint", "disability discrimination", "race", "family status", "retaliation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"medford-navigation-center",
    category:"housing",
    section:"Homeless, Shelter & Somewhere Safe Tonight",
    name:"Medford Navigation Center — 24/7 Emergency Shelter",
    helps:"24/7 emergency shelter operated by Rogue Retreat with connections to health care, public benefits and permanent housing. The facility includes family rooms and accommodations for people with medical needs, seniors, disabilities and service dogs.",
    audience:["Unhoused Adults", "Families", "Seniors", "People with Disabilities"],
    counties:["Jackson"],
    cost:"Emergency shelter; call/confirm current intake",
    address:"Medford",
    website:"https://www.medfordoregon.gov/Government/Departments/Planning/Housing-and-Community-Development/Addressing-Homelessness/Medford-Navigation-Center",
    labels:["24/7 SHELTER", "FAMILIES", "DISABILITY", "SERVICE DOG"],
    keywords:["shelter tonight", "Navigation Center", "Rogue Retreat", "family shelter", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rogue-retreat",
    category:"housing",
    section:"Homeless, Shelter & Somewhere Safe Tonight",
    name:"Rogue Retreat — Housing & Shelter Programs",
    helps:"Jackson County shelter, community-living and longer-term housing programs for people experiencing homelessness or serious housing instability. Intake and openings change, so confirm current availability.",
    audience:["Unhoused Adults", "Families"],
    counties:["Jackson"],
    cost:"Program-specific",
    address:"Medford",
    website:"https://www.rogueretreat.com/",
    labels:["HOMELESSNESS", "SHELTER", "HOUSING"],
    keywords:["Rogue Retreat", "shelter", "homeless", "housing application", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-severe-weather",
    category:"housing",
    section:"Homeless, Shelter & Somewhere Safe Tonight",
    name:"ACCESS — Medford Severe Weather Shelter",
    helps:"Emergency shelter activated during qualifying severe weather such as extreme cold, heat, smoke or storms. This is weather-dependent, so check current activation before going.",
    audience:["People Without Safe Shelter"],
    counties:["Jackson"],
    cost:"Free when activated",
    address:"Medford",
    website:"https://accesshelps.org/shelter/",
    labels:["SEVERE WEATHER", "EMERGENCY SHELTER", "LIVE STATUS"],
    keywords:["cold shelter", "heat shelter", "smoke", "storm", "severe weather"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ucan-shelter-navigation",
    category:"housing",
    section:"Homeless, Shelter & Somewhere Safe Tonight",
    name:"UCAN — Josephine County Homeless Services & Shelter Navigation",
    helps:"Josephine County housing/homeless-services front door for people without stable housing. UCAN can help connect people to current local shelter and housing pathways; actual bed availability changes.",
    audience:["Unhoused Adults", "Families"],
    counties:["Josephine"],
    cost:"Free navigation; programs vary",
    phone:"541-956-4050",
    address:"900 SE 8th Street, Grants Pass",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["HOMELESSNESS", "JOSEPHINE", "NAVIGATION"],
    keywords:["shelter", "homeless", "Grants Pass", "UCAN", "coordinated housing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"211-housing-live",
    category:"housing",
    section:"Homeless, Shelter & Somewhere Safe Tonight",
    name:"211info — Live Shelter, Housing & Utility Search",
    helps:"Use 211 for current emergency shelter, motel, rent, deposit, utility and homelessness resources when availability is changing too fast for a static directory. Confirm bed availability before traveling.",
    audience:["Everyone"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["LIVE DIRECTORY", "SHELTER AVAILABILITY", "211"],
    keywords:["shelter bed", "housing", "rent", "deposit", "motel", "utility", "homeless"],
    lastVerified:"2026-09-04"
  },
  {
    id:"community-works-dunn-house",
    category:"housing",
    section:"Domestic Violence, Sexual Violence & Trafficking",
    name:"Community Works — Dunn House Emergency Shelter",
    helps:"Confidential emergency shelter for adults and children experiencing crisis or displacement related to violence. Families may stay up to 30 days, with 24-hour advocates and help with safety, housing, court, health care and benefits.",
    audience:["Survivors", "Adults with Children"],
    counties:["Jackson"],
    cost:"Free and confidential",
    phone:"541-779-4357",
    address:"Confidential shelter; call HelpLine",
    website:"https://www.community-works.org/shelter/",
    labels:["DOMESTIC VIOLENCE", "EMERGENCY SHELTER", "24/7"],
    keywords:["Dunn House", "domestic violence shelter", "sexual assault", "stalking", "trafficking"],
    lastVerified:"2026-09-04"
  },
  {
    id:"community-works-marys-haven",
    category:"housing",
    section:"Domestic Violence, Sexual Violence & Trafficking",
    name:"Community Works — Mary's Haven Transitional Housing",
    helps:"Longer-term transitional housing for survivors and their children, with stays up to two years while families work toward stability and permanent housing.",
    audience:["Survivors", "Parents", "Children"],
    counties:["Jackson"],
    cost:"Free/confidential program; eligibility applies",
    phone:"541-779-4357",
    address:"Southern Oregon",
    website:"https://www.community-works.org/housing/",
    labels:["TRANSITIONAL HOUSING", "SURVIVORS", "UP TO 2 YEARS"],
    keywords:["Mary's Haven", "survivor housing", "domestic violence", "transitional housing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"wcst-josephine",
    category:"housing",
    section:"Domestic Violence, Sexual Violence & Trafficking",
    name:"Women's Crisis Support Team — Josephine County",
    helps:"Josephine County domestic-violence and sexual-assault support. Call for current safety planning, advocacy and shelter/housing options.",
    audience:["Survivors", "Families"],
    counties:["Josephine"],
    cost:"Free/confidential services",
    phone:"541-479-9349",
    address:"Josephine County",
    website:"https://www.wcstjoco.org/",
    labels:["DOMESTIC VIOLENCE", "SEXUAL ASSAULT", "JOSEPHINE"],
    keywords:["Women's Crisis Support Team", "WCST", "domestic violence", "shelter", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-ssvf",
    category:"housing",
    section:"Veterans & Veteran Families",
    name:"ACCESS — Supportive Services for Veteran Families (SSVF)",
    helps:"Southern Oregon veteran housing support that may include security deposits, utilities, temporary rental assistance, eviction prevention, housing placement, landlord mediation, rapid rehousing, motel/shelter placement and case management.",
    audience:["Veterans", "Veteran Families"],
    counties:["Jackson", "Josephine"],
    cost:"Eligibility applies",
    phone:"541-774-4322",
    address:"Southern Oregon",
    website:"https://accesshelps.org/shelter/",
    labels:["VETERANS", "SSVF", "DEPOSIT", "RENT", "RAPID REHOUSING"],
    keywords:["veteran housing", "SSVF", "deposit", "eviction", "motel", "rent", "utilities"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ucan-ssvf",
    category:"housing",
    section:"Veterans & Veteran Families",
    name:"UCAN — Veteran Housing Services",
    helps:"Josephine County veteran services include housing stabilization and SSVF-related support for eligible veteran households that are homeless or at risk of homelessness.",
    audience:["Veterans", "Veteran Families"],
    counties:["Josephine"],
    cost:"Eligibility applies",
    phone:"541-956-4050",
    address:"900 SE 8th Street, Grants Pass",
    website:"https://www.ucancap.org/josephine-county-programs/",
    labels:["VETERANS", "JOSEPHINE", "HOUSING"],
    keywords:["UCAN veteran", "SSVF", "homeless veteran", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohp-hrsn-housing",
    category:"housing",
    section:"OHP, Disability & Health-Related Housing Support",
    name:"Oregon Health Plan — HRSN Housing Benefits",
    helps:"Some eligible OHP members can receive Health-Related Social Needs housing benefits such as rent help, utilities, tenancy support, storage fees and certain home changes. This is not emergency eviction assistance, approval takes time, and rent/utility assistance is generally a one-time household benefit.",
    audience:["Eligible OHP Members", "Families", "Seniors", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Covered benefit if eligible",
    phone:"800-273-0557",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/hsd/ohp/pages/housing.aspx",
    labels:["OHP", "HRSN", "RENT", "UTILITIES", "NOT EMERGENCY"],
    keywords:["OHP housing", "HRSN", "rent benefit", "utility benefit", "AllCare", "Jackson Care Connect"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohp-flex-services-housing",
    category:"housing",
    section:"OHP, Disability & Health-Related Housing Support",
    name:"OHP CCO Flexible Services — Short-Term Housing Supports",
    helps:"A coordinated care organization may sometimes approve flexible services that support health, such as a rental deposit, short-term rental help, utility setup fees or temporary housing. Flexible services are optional and separate from standard OHP benefits.",
    audience:["OHP CCO Members"],
    counties:["Jackson", "Josephine"],
    cost:"Only if approved by the member's CCO",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/OHP/Members/pages/flexible-services.aspx",
    labels:["OHP", "CCO", "DEPOSIT", "SHORT-TERM HOUSING"],
    keywords:["flex services", "AllCare", "Jackson Care Connect", "rental deposit", "utility setup"],
    lastVerified:"2026-09-04"
  },
  {
    id:"adrc-home-modifications",
    category:"housing",
    section:"OHP, Disability & Health-Related Housing Support",
    name:"ADRC — Home Modification & Long-Term Support Navigation",
    helps:"Older adults and people with disabilities can use ADRC to explore Medicaid long-term services, in-home supports and possible accessibility/home-modification pathways. Eligibility depends on the person's care program and needs.",
    audience:["Seniors", "People with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free navigation; services have eligibility rules",
    phone:"541-618-7572",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/what-we-do/",
    labels:["DISABILITY", "ACCESSIBILITY", "HOME MODIFICATION"],
    keywords:["ramp", "grab bar", "home modification", "Medicaid", "ADRC", "disability"],
    lastVerified:"2026-09-04"
  },
  {
    id:"mmcrc",
    category:"housing",
    section:"Manufactured-Home Parks",
    name:"Oregon Manufactured Home & Marina Communities Resource Center",
    helps:"Official park-specific resource for manufactured-home residents and landlords. Helps with park laws, disputes, mediation, park sales/closures, replacement programs, utility-charge questions and other manufactured-home park issues.",
    audience:["Manufactured-Home Residents", "Park Landlords", "Seniors"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and mediation",
    phone:"800-453-5511 option 2",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ohcs/mmcrc",
    labels:["MANUFACTURED HOME", "PARK LAW", "MEDIATION"],
    keywords:["mobile home park", "manufactured home", "park closure", "park sale", "mediation", "water sewer charge"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohcs-foreclosure",
    category:"housing",
    section:"Homeowners, Mortgage & Foreclosure",
    name:"Oregon Foreclosure Avoidance Program",
    helps:"State foreclosure-prevention pathway for homeowners who are behind on a mortgage or facing foreclosure. Housing counselors can help organize financial documents, communicate with lenders and prepare for Oregon's foreclosure-resolution process.",
    audience:["Homeowners", "Borrowers"],
    counties:["Jackson", "Josephine"],
    cost:"Free/low-cost state-supported help",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ohcs/homeownership/pages/foreclosure-default-prevention.aspx",
    labels:["MORTGAGE", "FORECLOSURE", "HOUSING COUNSELOR"],
    keywords:["missed mortgage", "foreclosure notice", "lender", "housing counselor", "default"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohcs-housing-counselor",
    category:"housing",
    section:"Homeowners, Mortgage & Foreclosure",
    name:"OHCS — Find a Certified Housing Counselor",
    helps:"Certified housing counselors can help homeowners and homebuyers with mortgage trouble, foreclosure prevention, housing stability and affordable-homeownership questions.",
    audience:["Homeowners", "Homebuyers"],
    counties:["Jackson", "Josephine"],
    cost:"Counseling is generally free or low-cost depending on provider",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ohcs/homeownership/pages/housing-counseling.aspx",
    labels:["HOUSING COUNSELOR", "HOMEOWNER", "FORECLOSURE"],
    keywords:["housing counselor", "mortgage", "foreclosure", "homebuyer", "property taxes"],
    lastVerified:"2026-09-04"
  },
  {
    id:"access-wildfire",
    category:"housing",
    section:"Wildfire & Disaster Housing Recovery",
    name:"ACCESS — Center for Community Resilience",
    helps:"Jackson County housing and recovery support for households impacted by the 2020 wildfires. Current support focuses on long-term housing recovery and stability rather than closed temporary-rent programs.",
    audience:["2020 Wildfire Survivors", "Families", "Homeowners", "Renters"],
    counties:["Jackson"],
    cost:"Program-specific",
    phone:"541-779-6691",
    address:"Jackson County",
    website:"https://accesshelps.org/shelter/",
    labels:["WILDFIRE", "2020 FIRES", "HOUSING RECOVERY"],
    keywords:["Almeda fire", "wildfire survivor", "Center for Community Resilience", "recovery housing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"reoregon-harp",
    category:"housing",
    section:"Wildfire & Disaster Housing Recovery",
    name:"ReOregon — Homeowner Assistance & Reconstruction Program (HARP)",
    helps:"For qualifying homeowners whose primary residence was damaged or destroyed in Oregon's 2020 disasters. HARP can support rehabilitation, reconstruction or manufactured-home replacement depending on eligibility and remaining damage.",
    audience:["2020 Disaster-Impacted Homeowners"],
    counties:["Jackson", "Josephine"],
    cost:"Disaster-recovery eligibility applies",
    phone:"877-510-6800",
    address:"Oregon",
    website:"https://www.oregon.gov/ohcs/disaster-recovery/reoregon/harp/Pages/default.aspx",
    labels:["REOREGON", "HARP", "REBUILD", "MANUFACTURED HOME"],
    keywords:["2020 wildfire", "HARP", "rebuild", "repair", "manufactured home replacement"],
    lastVerified:"2026-09-04"
  },
  {
    id:"reoregon-housing-support",
    category:"housing",
    section:"Wildfire & Disaster Housing Recovery",
    name:"ReOregon — Housing Support Services",
    helps:"Current ReOregon housing-support information for qualifying 2020 disaster survivors, including housing counseling and down-payment assistance. The prior Intermediate Housing Assistance rent/utility program closed to new applications July 1, 2026 and is not presented here as active.",
    audience:["2020 Disaster Survivors"],
    counties:["Jackson", "Josephine"],
    cost:"Program-specific",
    address:"Oregon",
    website:"https://www.oregon.gov/ohcs/disaster-recovery/reoregon/pages/default.aspx",
    labels:["DISASTER RECOVERY", "HOUSING COUNSELING", "DOWN PAYMENT"],
    keywords:["ReOregon", "wildfire", "housing counseling", "down payment", "closed program"],
    lastVerified:"2026-09-04"
  }
];
