/* Flourish Anyway Community Resource Hub
   JOBS, EDUCATION & SKILLS
   File name after upload: jobs-data.js
   Jackson + Josephine Counties, Oregon
   Backbone: official local/state/provider sources + 211info
   Last researched: 2026-08-30
*/

window.FLOURISH_JOBS_DATA = [
  {
    id:"worksource-medford",
    category:"jobs",
    name:"WorkSource Rogue Valley — Medford",
    helps:"Job-search help, career planning, resume support, iMatchSkills assistance, training connections and employment services for Jackson County job seekers.",
    audience:["Adults","Youth","Veterans","Disability","Job Seekers"],
    counties:["Jackson"],
    cost:"Free",
    phone:"541-734-7533",
    address:"119 N Oakdale Ave, Medford, OR 97501",
    website:"https://worksourcerogue.org/intro-to-workforce/",
    labels:["JOB SEARCH","TRAINING","MEDFORD"],
    keywords:["WorkSource","job search","resume","career","iMatchSkills","Medford"],
    lastVerified:"2026-08-30"
  },
  {
    id:"worksource-grants-pass",
    category:"jobs",
    name:"WorkSource Rogue Valley — Grants Pass",
    helps:"Job-search help, career planning, resume support, iMatchSkills assistance, training connections and employment services for Josephine County job seekers.",
    audience:["Adults","Youth","Veterans","Disability","Job Seekers"],
    counties:["Josephine"],
    cost:"Free",
    phone:"541-471-3811",
    address:"1569 NE F St, Grants Pass, OR 97526",
    website:"https://worksourcerogue.org/intro-to-workforce/",
    labels:["JOB SEARCH","TRAINING","GRANTS PASS"],
    keywords:["WorkSource","job search","resume","career","iMatchSkills","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"worksource-vocational-training",
    category:"jobs",
    name:"WorkSource Rogue Valley — Vocational Training Connections",
    helps:"Connects job seekers to local career training such as CNA, allied health, wildland firefighting, forestry, heavy equipment, CDL/truck driving, diesel technology and other vocational programs.",
    audience:["Adults","Dislocated Workers","Career Changers","Youth"],
    counties:["Jackson","Josephine"],
    cost:"Training costs vary; workforce funding may be available for eligible participants",
    phone:"541-734-7533",
    address:"Medford + Grants Pass WorkSource centers",
    website:"https://worksourcerogue.org/job-seekers/training-opportunities/vocational-training-opportunities/",
    labels:["CAREER TRAINING","CDL","CNA","TRADES"],
    keywords:["vocational training","CNA","CDL","truck driving","firefighter","heavy equipment","medical training"],
    lastVerified:"2026-08-30"
  },
  {
    id:"worksource-financial-support",
    category:"jobs",
    name:"WorkSource Rogue Valley — Financial & Documentation Support",
    helps:"Resource connections for barriers that can interfere with employment, including unemployment insurance, food/housing support, transportation, documentation and community assistance.",
    audience:["Job Seekers","Adults","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free navigation; individual programs vary",
    phone:"541-734-7533",
    address:"Medford + Grants Pass",
    website:"https://worksourcerogue.org/job-seekers/financialsupport/",
    labels:["JOB BARRIERS","FINANCIAL HELP","DOCUMENTS"],
    keywords:["work documents","transportation","job barriers","unemployment","financial help"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-ged",
    category:"jobs",
    name:"Rogue Community College — GED Program",
    helps:"GED preparation for adults and eligible youth who do not have a high-school diploma, with learning centers in Grants Pass, Medford and White City.",
    audience:["Adults","Youth 16+","College-Bound","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"Contact RCC for current class/testing costs; admission/orientation support available",
    phone:"541-956-7490",
    address:"Medford, White City + Grants Pass learning centers",
    website:"https://www.roguecc.edu/degrees-and-programs/ged-and-pre-college-education/ged/index.php",
    apply:"https://roguecc.edu/admissions/steps-to-become-a-student/ged-and-pre-college-education-admission/getting-started-with-ged.php",
    labels:["GED","ADULT EDUCATION","3 LOCATIONS"],
    keywords:["GED","high school diploma","adult education","math","reading","college prep"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-ged-spanish",
    category:"jobs",
    name:"Rogue Community College — GED en Español",
    helps:"Spanish-language GED preparation through RCC’s GED and Pre-College Education program.",
    audience:["Spanish-Speaking Adults","Youth 16+"],
    counties:["Jackson","Josephine"],
    cost:"Call for current program/testing costs",
    phone:"541-956-7169",
    address:"RCC Jackson + Josephine County campuses",
    website:"https://www.roguecc.edu/degrees-and-programs/ged-and-pre-college-education/ged/index.php",
    labels:["GED","SPANISH","ADULT EDUCATION"],
    keywords:["GED español","Spanish GED","educación","RCC"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-precollege",
    category:"jobs",
    name:"Rogue Community College — Pre-College Education",
    helps:"Helps adult learners strengthen reading, writing and math skills before college, career training or GED completion.",
    audience:["Adults","College-Bound","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"Call for current class costs and placement information",
    phone:"541-956-7490",
    address:"RCC Medford, White City + Grants Pass",
    website:"https://www.roguecc.edu/degrees-and-programs/ged-and-pre-college-education/ged/index.php",
    labels:["BASIC SKILLS","COLLEGE PREP","ADULT LEARNING"],
    keywords:["reading","math","writing","adult basic education","college readiness"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-workforce-training",
    category:"jobs",
    name:"Rogue Community College — Community & Workforce Training",
    helps:"Short-term workforce certifications, professional development, career skills and community education designed for practical job advancement.",
    audience:["Adults","Workers","Career Changers","Employers"],
    counties:["Jackson","Josephine"],
    cost:"Course-specific",
    phone:"541-956-7500",
    address:"RCC campuses in Grants Pass, Medford + White City",
    website:"https://www.roguecc.edu/community-and-workforce-training/index.php",
    labels:["CERTIFICATIONS","WORKFORCE","SHORT-TERM TRAINING"],
    keywords:["certificate","workforce training","CPR","professional development","skills"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-employment-skills",
    category:"jobs",
    name:"Rogue Community College — Employment Skills Training",
    helps:"One- to two-term certificate combining college coursework with supervised training at a local worksite. Training plans are individualized around local employment opportunities.",
    audience:["Adults","Students","Career Changers","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"College tuition/financial aid rules apply",
    phone:"541-956-7380",
    address:"Rogue Community College",
    website:"https://www.roguecc.edu/degrees-and-programs/degrees-and-certificates/employment-skills-training/index.php",
    apply:"https://www.roguecc.edu/degrees-and-programs/degrees-and-certificates/employment-skills-training/application-process.php",
    labels:["CERTIFICATE","HANDS-ON","WORKSITE TRAINING"],
    keywords:["employment skills","construction","administrative assistant","job coach","building maintenance"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-occupational-skills",
    category:"jobs",
    name:"Rogue Community College — Occupational Skills Training",
    helps:"Customized certificate program combining coursework and substantial supervised field training in a chosen occupational area.",
    audience:["Adults","Students","Career Changers"],
    counties:["Jackson","Josephine"],
    cost:"College tuition/financial aid rules apply",
    phone:"541-956-7500",
    address:"Rogue Community College",
    website:"https://roguecc.edu/degrees-and-programs/degrees-and-certificates/occupational-skills-training/index.php",
    labels:["CAREER CERTIFICATE","FIELD TRAINING","RCC"],
    keywords:["occupational skills","career certificate","internship","worksite","training"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-career-connections",
    category:"jobs",
    name:"Rogue Community College — Career Connections",
    helps:"Connects RCC students and graduates with employers, jobs, work-study opportunities and career-development resources.",
    audience:["RCC Students","Graduates","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"Student/community service",
    phone:"541-956-7500",
    address:"Rogue Community College",
    website:"https://www.roguecc.edu/community-and-workforce-training/index.php",
    labels:["JOBS","EMPLOYERS","STUDENTS"],
    keywords:["career connections","job board","work study","RCC jobs"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-cooperative-work",
    category:"jobs",
    name:"Rogue Community College — Cooperative Work Experience",
    helps:"Lets students earn college credit while gaining supervised real-world work experience related to their education and career goals.",
    audience:["RCC Students"],
    counties:["Jackson","Josephine"],
    cost:"College enrollment/tuition rules apply",
    phone:"541-956-7500",
    address:"Rogue Community College + local worksites",
    website:"https://www.roguecc.edu/community-and-workforce-training/index.php",
    labels:["WORK EXPERIENCE","COLLEGE CREDIT","CAREER EXPLORATION"],
    keywords:["internship","CWE","work experience","college credit","career"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rcc-lifelong-learning",
    category:"jobs",
    name:"Rogue Community College — Lifelong Learners 62+",
    helps:"Educational opportunities for adults age 62+ who want to continue learning, build skills or explore classes.",
    audience:["Seniors 62+"],
    counties:["Jackson","Josephine"],
    cost:"Program-specific",
    phone:"541-956-7500",
    address:"Rogue Community College",
    website:"https://www.roguecc.edu/admissions/index.php",
    labels:["SENIORS","EDUCATION","62+"],
    keywords:["senior classes","lifelong learner","62","college"],
    lastVerified:"2026-08-30"
  },
  {
    id:"soesd-cte",
    category:"jobs",
    name:"Southern Oregon ESD — Career & Technical Education",
    helps:"Career-connected learning, technical skill development, industry credentials and work-based learning for students across Southern Oregon.",
    audience:["Middle School Students","High School Students","Families","Educators"],
    counties:["Jackson","Josephine"],
    cost:"School/program-specific",
    phone:"",
    address:"Jackson + Josephine County school districts",
    website:"https://www.soesd.k12.or.us/cte-new/",
    labels:["CTE","YOUTH","CAREER PATHWAYS","CREDENTIALS"],
    keywords:["CTE","career technical education","high school trades","credentials","work based learning"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-apprenticeship",
    category:"jobs",
    name:"Oregon Apprenticeship — Paid Career Training",
    helps:"Official Oregon resource for registered apprenticeships that combine paid on-the-job training with classroom instruction in skilled occupations.",
    audience:["Adults","Young Adults","Career Changers"],
    counties:["Jackson","Josephine"],
    cost:"Apprentices are paid; entry requirements vary by program",
    phone:"",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/boli/apprenticeship/pages/default.aspx",
    labels:["APPRENTICESHIP","PAID TRAINING","TRADES"],
    keywords:["apprenticeship","electrician","plumber","construction","trades","paid training"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-unemployment",
    category:"jobs",
    name:"Oregon Employment Department — Unemployment Insurance",
    helps:"Temporary income replacement for eligible Oregon workers who lose work or experience qualifying reductions in hours.",
    audience:["Workers","Unemployed Adults"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"877-345-3484",
    address:"Statewide Oregon",
    website:"https://unemployment.oregon.gov/",
    apply:"https://unemployment.oregon.gov/",
    labels:["UNEMPLOYMENT","INCOME","WORKERS"],
    keywords:["unemployment","UI","lost job","layoff","claim"],
    lastVerified:"2026-08-30"
  },
  {
    id:"vocational-rehab-oregon",
    category:"jobs",
    name:"Oregon Vocational Rehabilitation",
    helps:"Helps eligible people with disabilities prepare for, obtain, maintain or advance in employment through individualized vocational services.",
    audience:["Adults with Disabilities","Youth with Disabilities","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"Eligibility-based public service",
    phone:"",
    address:"Local Oregon VR offices serve Southern Oregon",
    website:"https://www.oregon.gov/odhs/vr/pages/default.aspx",
    labels:["DISABILITY","EMPLOYMENT","CAREER SUPPORT"],
    keywords:["vocational rehab","VR","disabled worker","job help","employment disability"],
    lastVerified:"2026-08-30"
  },
  {
    id:"unete-workforce",
    category:"jobs",
    name:"Unete Center for Farm Worker Advocacy — Worker & Community Support",
    helps:"Southern Oregon resource navigation and advocacy for farmworkers and Hispanic/Latino community members, including employment-related and community supports.",
    audience:["Farmworkers","Spanish-Speaking Families","Immigrant Families"],
    counties:["Jackson","Josephine"],
    cost:"Community nonprofit services",
    phone:"541-245-1625",
    address:"Southern Oregon",
    website:"https://worksourcerogue.org/job-seekers/financialsupport/",
    labels:["FARMWORKERS","SPANISH","RESOURCE NAVIGATION"],
    keywords:["Unete","farmworker","Spanish","Latino","employment","resources"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-employment-search",
    category:"jobs",
    name:"211info — Employment, Education & Training Search",
    helps:"Search Oregon’s larger live resource directory for employment programs, job training, GED help, vocational rehabilitation, apprenticeships and education resources not yet individually listed in the Flourish hub.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["211","LIVE DIRECTORY","CATCH-ALL"],
    keywords:["211","job","employment","GED","training","education","career","apprenticeship"],
    lastVerified:"2026-08-30"
  },
  {
    id:"worksource-rogue-valley",
    category:"jobs",
    name:"WorkSource Rogue Valley — Job & Training Help",
    helps:"Local workforce system for job search, resumes, training pathways, unemployment-related reemployment services and connections to employers. Ask about training funds and barriers such as transportation or child care.",
    audience:["Job Seekers","Adults","Youth","Career Changers"],
    counties:["Jackson","Josephine"],
    cost:"Most core workforce services are free",
    address:"Jackson & Josephine Counties",
    website:"https://www.rogueworkforce.org/",
    labels:["JOBS","TRAINING","TWO COUNTIES"],
    keywords:["WorkSource","job search","resume","training","career","employment","Rogue Workforce"],
    lastVerified:"2026-08-31"
  },
  {
    id:"vocational-rehabilitation-oregon",
    category:"jobs",
    name:"Oregon Vocational Rehabilitation — Disability Employment Help",
    helps:"Employment support for people with disabilities whose disability creates barriers to getting or keeping a job. Services are individualized after eligibility and planning.",
    audience:["People with Disabilities","Job Seekers"],
    counties:["Jackson","Josephine"],
    cost:"State vocational-rehabilitation program; eligibility applies",
    address:"Local offices serve Southern Oregon",
    website:"https://www.oregon.gov/odhs/vr/pages/default.aspx",
    labels:["DISABILITY","EMPLOYMENT","VOCATIONAL REHAB"],
    keywords:["disability job","voc rehab","VR","employment disability","job accommodation"],
    lastVerified:"2026-08-31"
  },
  {
    id:"jackson-veteran-services",
    category:"jobs",
    name:"Jackson County Veteran Services Office",
    helps:"County Veteran Services Officer help with VA benefits and claims. Jackson County's office is in Medford and operates by appointment; ask about compensation, pension, health-care and other veteran benefits that may affect housing/employment stability.",
    audience:["Veterans","Veteran Families"],
    counties:["Jackson"],
    cost:"County veteran-service assistance is free",
    phone:"541-774-8214",
    address:"140 S Holly St, Medford, OR 97501",
    website:"https://www.oregon.gov/ODVA/Services/Pages/Counties/Jackson.aspx",
    labels:["VETERANS","BENEFITS","JACKSON"],
    keywords:["veteran","VA benefits","VSO","Medford","military","claim"],
    lastVerified:"2026-08-31"
  },
  {
    id:"josephine-veteran-services",
    category:"jobs",
    name:"Josephine County Veteran Services Office",
    helps:"County Veteran Services Officer help with VA benefits and claims. The Grants Pass office also notes outreach and in-home visit capabilities—call to confirm what is available.",
    audience:["Veterans","Veteran Families"],
    counties:["Josephine"],
    cost:"County veteran-service assistance is free",
    phone:"541-474-5454",
    address:"500 NW 6th St, Dept. 15, Grants Pass, OR 97527",
    website:"https://www.oregon.gov/odva/services/pages/counties/josephine.aspx",
    labels:["VETERANS","BENEFITS","JOSEPHINE"],
    keywords:["veteran","VA benefits","VSO","Grants Pass","military","claim"],
    lastVerified:"2026-08-31"
  },
  {
    id:"golden-rule-reentry",
    category:"jobs",
    name:"Golden Rule ReEntry — Reentry Navigation",
    helps:"Local peer/case-management support for people rebuilding after incarceration, including resource navigation, DMV privilege restoration, transportation, goals and problem solving. Call to confirm current programs and intake.",
    audience:["People Returning from Incarceration","Adults Rebuilding Stability"],
    counties:["Jackson"],
    cost:"Contact program",
    phone:"541-930-8933",
    address:"715 W Main St, Medford, OR 97501",
    labels:["REENTRY","DMV","PEER SUPPORT"],
    keywords:["reentry","prison release","felony","DMV restoration","job after incarceration","Golden Rule"],
    lastVerified:"2026-08-31"
  }
];
