/* Flourish Anyway Community Resource Hub
   LEGAL & GOVERNMENT HELP — SEPTEMBER 2026 VERIFIED REBUILD
   Upload as: legal-data.js
   Jackson + Josephine Counties, Oregon
   Rule: one real resource/agency per card. Broad landing pages are used deliberately to reduce stale-link risk.
   This directory is information/referral only, not legal advice.
*/

window.FLOURISH_LEGAL_DATA = [
  {
    id:"cnpls-jackson",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Center for NonProfit Legal Services — Jackson County",
    helps:"Local nonprofit legal aid for eligible Jackson County residents. Handles non-criminal matters including family, housing, consumer/debt, employment, public benefits, immigration, disability, wills/life planning, criminal-record issues and protective-services cases.",
    audience:["Low-Income Adults", "Families", "Seniors", "Survivors", "Immigrants", "Veterans"],
    counties:["Jackson"],
    cost:"Free or eligibility-based civil legal help",
    phone:"541-779-7292",
    address:"225 W Main Street, Medford",
    website:"https://cnpls.org/",
    labels:["LOCAL LEGAL AID", "JACKSON", "START HERE"],
    keywords:["legal aid", "lawyer", "family", "housing", "debt", "benefits", "immigration", "wills", "employment", "records"],
    lastVerified:"2026-09-04"
  },
  {
    id:"olc-grants-pass",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Oregon Law Center — Grants Pass Regional Office",
    helps:"Civil legal aid for eligible low-income Josephine County residents. The office accepts calls about any civil legal problem, with priority areas including family law, housing, disability, discrimination and Oregon Health Plan issues.",
    audience:["Low-Income Adults", "Families", "Seniors"],
    counties:["Josephine"],
    cost:"Free for eligible clients",
    phone:"541-476-1058",
    address:"873 NE 7th Street, Suite A, Grants Pass",
    website:"https://oregonlawcenter.org/how-to-get-help/olc-offices/grants-pass/",
    labels:["LOCAL LEGAL AID", "JOSEPHINE", "START HERE"],
    keywords:["legal aid", "Grants Pass", "family law", "housing", "disability", "discrimination", "OHP"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-law-help",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Oregon Law Help — Civil Legal Information & Help Finder",
    helps:"Attorney-reviewed Oregon civil legal information plus a directory for free and low-cost legal help. Strong starting point for family, housing, money/debt, benefits, immigration and other civil problems.",
    audience:["Everyone", "Self-Represented People"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://oregonlawhelp.org/",
    labels:["LEGAL INFORMATION", "HELP FINDER", "STATEWIDE"],
    keywords:["legal information", "find lawyer", "civil law", "forms", "rights"],
    lastVerified:"2026-09-04"
  },
  {
    id:"osbar-referral",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Oregon State Bar — Lawyer Referral & Public Legal Information",
    helps:"Find an Oregon lawyer and review public legal information. The State Bar also links to reduced-cost and special referral programs when available.",
    audience:["Adults", "Families", "Businesses"],
    counties:["Jackson", "Josephine"],
    cost:"Referral service; attorney fees vary",
    phone:"503-684-3763",
    address:"Oregon statewide",
    website:"https://www.osbar.org/public/ris/",
    labels:["FIND A LAWYER", "STATE BAR"],
    keywords:["lawyer referral", "attorney", "modest means", "legal consultation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-courts-self-help",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Oregon Courts — Self-Help Center",
    helps:"Official Oregon court self-help hub for family law, landlord-tenant, debt collection, small claims, court forms and other common court processes for people without lawyers.",
    audience:["Self-Represented People", "Parents", "Tenants", "Residents"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; filing fees may apply",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/help/pages/default.aspx",
    labels:["COURT FORMS", "SELF-HELP", "OFFICIAL"],
    keywords:["court forms", "self represented", "small claims", "family law", "eviction", "debt"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-circuit-court",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Jackson County Circuit Court",
    helps:"Official Jackson County state trial court page for family, civil, criminal, probate, protective-order and other court matters.",
    audience:["Residents", "Litigants", "Families"],
    counties:["Jackson"],
    cost:"Court fees vary; waiver/deferral may be available",
    phone:"541-776-7171",
    address:"100 S Oakdale Avenue, Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/",
    labels:["COURT", "JACKSON"],
    keywords:["Jackson County court", "Medford courthouse", "family", "criminal", "civil", "probate"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-circuit-court",
    category:"legal",
    section:"Start Here — Legal Aid & Courts",
    name:"Josephine County Circuit Court",
    helps:"Official Josephine County state trial court page for family, civil, criminal, probate, protective-order and other court matters.",
    audience:["Residents", "Litigants", "Families"],
    counties:["Josephine"],
    cost:"Court fees vary; waiver/deferral may be available",
    phone:"541-476-2309",
    address:"500 NW 6th Street, Grants Pass",
    website:"https://www.courts.oregon.gov/courts/josephine/",
    labels:["COURT", "JOSEPHINE"],
    keywords:["Josephine County court", "Grants Pass courthouse", "family", "criminal", "civil", "probate"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-family-law-center",
    category:"legal",
    section:"Family, Custody & Child Support",
    name:"Jackson County — Family Law Self-Represented Center",
    helps:"Free court-facilitator help for people representing themselves in divorce, custody and parenting-time cases. Facilitators explain procedures, review approved forms and point to resources; they do not give legal advice.",
    audience:["Parents", "Self-Represented Litigants"],
    counties:["Jackson"],
    cost:"Free court service",
    phone:"541-776-7171 option 4",
    address:"100 S Oakdale Avenue, Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/programs-services/pages/fl-selfrepresented.aspx",
    labels:["FAMILY LAW", "CUSTODY", "DIVORCE", "FREE HELP"],
    keywords:["custody", "divorce", "parenting time", "family law facilitator", "forms"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-family-facilitator",
    category:"legal",
    section:"Family, Custody & Child Support",
    name:"Josephine County — Family Law Facilitator",
    helps:"Free help with family-law paperwork for people without attorneys, including document review and family-law form questions. The facilitator cannot give legal advice.",
    audience:["Parents", "Self-Represented Litigants"],
    counties:["Josephine"],
    cost:"Free court service",
    phone:"541-476-2309 ext. 37025",
    address:"301 NW F Street, Grants Pass",
    website:"https://www.courts.oregon.gov/courts/josephine/help/Pages/fl-facilitator.aspx",
    labels:["FAMILY LAW", "CUSTODY", "DIVORCE", "FREE HELP"],
    keywords:["custody", "divorce", "parenting time", "facilitator", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-family-law",
    category:"legal",
    section:"Family, Custody & Child Support",
    name:"Oregon Courts — Family Law Information",
    helps:"Statewide family-law information and free court-facilitator connections for divorce, custody, parenting time, parentage and related cases.",
    audience:["Parents", "Families", "Self-Represented People"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/programs/family/courtinfo/pages/default.aspx",
    labels:["FAMILY LAW", "STATEWIDE"],
    keywords:["custody", "parenting time", "paternity", "parentage", "divorce", "family court"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-child-support",
    category:"legal",
    section:"Family, Custody & Child Support",
    name:"Oregon Child Support Program",
    helps:"Government program for establishing parentage and child-support orders, enforcing support, reviewing qualifying orders for modification and helping with interstate support cases.",
    audience:["Parents", "Caregivers", "Children"],
    counties:["Jackson", "Josephine"],
    cost:"Government service",
    phone:"800-850-0228",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/child-support/",
    labels:["CHILD SUPPORT", "PARENTAGE", "ENFORCEMENT"],
    keywords:["child support", "paternity", "parentage", "modify support", "arrears", "enforcement"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-protective-orders",
    category:"legal",
    section:"Safety, Protective Orders & Child Welfare",
    name:"Oregon Courts — Protective Orders",
    helps:"Official information and forms for Family Abuse restraining orders, elder/disabled-person abuse orders, stalking orders, sexual-abuse protection orders and extreme-risk protection orders.",
    audience:["Survivors", "Seniors", "People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Court information and forms are free",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/programs/family/domestic-violence/pages/default.aspx",
    labels:["PROTECTIVE ORDERS", "SAFETY", "OFFICIAL"],
    keywords:["restraining order", "FAPA", "stalking", "sexual abuse", "elder abuse", "EPPDAPA"],
    lastVerified:"2026-09-04"
  },
  {
    id:"odhs-complaints",
    category:"legal",
    section:"Safety, Protective Orders & Child Welfare",
    name:"ODHS — Complaints, Concerns & Advocacy",
    helps:"State complaint and advocacy hub for concerns involving Oregon Department of Human Services programs, including child welfare, foster care, discrimination and customer-service problems. It does not replace court appeals or abuse reporting.",
    audience:["Parents", "Families", "Foster Youth", "ODHS Clients"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/about/pages/gao.aspx",
    labels:["ODHS", "CHILD WELFARE", "COMPLAINTS"],
    keywords:["DHS", "ODHS", "child welfare", "foster care", "complaint", "ombuds", "civil rights"],
    lastVerified:"2026-09-04"
  },
  {
    id:"foster-care-ombuds",
    category:"legal",
    section:"Safety, Protective Orders & Child Welfare",
    name:"Oregon Foster Care Ombuds",
    helps:"Independent resource for complaints, concerns and rights violations involving children in ODHS custody. Receives concerns from foster youth, parents, relatives, attorneys, CASAs and others.",
    audience:["Foster Youth", "Parents", "Relatives", "Advocates"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"855-840-6036",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/about/Pages/foster-care-ombuds.aspx",
    labels:["FOSTER CARE", "RIGHTS", "OMBUDS"],
    keywords:["foster care complaint", "foster child rights", "ODHS custody", "YES line"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-landlord-tenant",
    category:"legal",
    section:"Renters, Housing & Homelessness",
    name:"Oregon Courts — Landlord & Tenant Self-Help",
    helps:"Official court information for evictions and landlord-tenant cases, including statewide forms and links for tenants and landlords.",
    audience:["Renters", "Landlords", "Self-Represented People"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; filing fees may apply",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/help/pages/landlord-tenant.aspx",
    labels:["EVICTION", "RENTERS", "COURT FORMS"],
    keywords:["eviction", "landlord", "tenant", "notice", "lockout", "rental"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-law-help-rental",
    category:"legal",
    section:"Renters, Housing & Homelessness",
    name:"Oregon Law Help — Rental Housing Rights",
    helps:"Attorney-reviewed Oregon renter information on repairs, landlord entry, rent increases, deposits, moving, evictions, discrimination, disability accommodations, immigrant protections and survivor protections.",
    audience:["Renters", "Families", "People with Disabilities", "Immigrants", "Survivors"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://oregonlawhelp.org/topics/housing/rental-housing",
    labels:["RENTER RIGHTS", "EVICTION", "HOUSING"],
    keywords:["repairs", "deposit", "rent increase", "eviction", "housing discrimination", "service animal", "reasonable accommodation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohcs-renter-resources",
    category:"legal",
    section:"Renters, Housing & Homelessness",
    name:"Oregon Housing & Community Services — Renter Resources",
    helps:"State renter-rights and housing-resource landing page that points to eviction legal help, fair-housing complaint options, Fair Housing Council guidance and housing assistance.",
    audience:["Renters", "People Facing Housing Instability"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ohcs/housing-assistance/pages/renter-resources.aspx",
    labels:["RENTERS", "FAIR HOUSING", "HOUSING HELP"],
    keywords:["renter rights", "fair housing", "eviction", "housing assistance", "discrimination"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-fair-housing",
    category:"legal",
    section:"Renters, Housing & Homelessness",
    name:"BOLI — Fair Housing Rights & Complaints",
    helps:"Official Oregon civil-rights enforcement for housing discrimination. BOLI can take formal fair-housing complaints and investigate discrimination claims.",
    audience:["Renters", "Homebuyers", "People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free complaint process",
    phone:"971-245-3844",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/civil-rights/Pages/fair-housing.aspx",
    labels:["FAIR HOUSING", "DISCRIMINATION", "COMPLAINT"],
    keywords:["housing discrimination", "reasonable accommodation", "protected class", "BOLI"],
    lastVerified:"2026-09-04"
  },
  {
    id:"opdc-unrepresented",
    category:"legal",
    section:"Criminal, Public Defense & Recovery Court",
    name:"Oregon Public Defense Commission — Waiting for Appointed Counsel",
    helps:"Official information and resources for people charged with crimes who are entitled to appointed counsel but do not currently have an attorney.",
    audience:["People Charged with Crimes", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free public-defense information",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/opdc/general/pages/unrepresented.aspx",
    labels:["PUBLIC DEFENSE", "WAITING FOR LAWYER", "CRIMINAL"],
    keywords:["public defender", "appointed counsel", "unrepresented", "criminal charge"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-treatment-courts",
    category:"legal",
    section:"Criminal, Public Defense & Recovery Court",
    name:"Jackson County Circuit Court — Treatment Courts",
    helps:"Jackson County treatment-court information for eligible adults facing serious criminal charges, including Recovery Opportunity Court and Wellness Court pathways tied to substance use and serious mental illness.",
    audience:["Justice-Involved Adults", "People in Recovery"],
    counties:["Jackson"],
    cost:"Court/program rules apply",
    phone:"541-776-7171",
    address:"100 S Oakdale Avenue, Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/programs-services/Pages/treatment-courts.aspx",
    labels:["TREATMENT COURT", "RECOVERY", "MENTAL HEALTH"],
    keywords:["ROC", "Recovery Opportunity Court", "Wellness Court", "drug court", "treatment court"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-drug-court",
    category:"legal",
    section:"Criminal, Public Defense & Recovery Court",
    name:"Josephine County Circuit Court — Adult Drug Court",
    helps:"Court-supervised outpatient treatment program for eligible high-risk/high-needs adults. Eligibility is determined through the Josephine County justice system.",
    audience:["Justice-Involved Adults", "People in Recovery"],
    counties:["Josephine"],
    cost:"Program rules apply",
    phone:"541-476-2309 ext. 4535",
    address:"Grants Pass",
    website:"https://www.courts.oregon.gov/courts/josephine/programs-services/Pages/drug-court.aspx",
    labels:["DRUG COURT", "RECOVERY", "JOSEPHINE"],
    keywords:["drug court", "treatment court", "probation", "recovery", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"criminal-set-aside",
    category:"legal",
    section:"Records, Fines & Driver License",
    name:"Oregon Courts — Criminal Record Set Aside (Expungement)",
    helps:"Current statewide forms and instructions for asking a court to seal eligible adult arrest, dismissal or conviction records. Eligibility rules can be complicated and some records cannot be set aside.",
    audience:["Adults with Criminal Records", "Job Seekers"],
    counties:["Jackson", "Josephine"],
    cost:"Court/record-check fees may apply",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/forms/pages/crimarrestsetaside.aspx",
    labels:["EXPUNGEMENT", "SET ASIDE", "CRIMINAL RECORD"],
    keywords:["expungement", "set aside", "seal record", "criminal record", "background check"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-set-aside",
    category:"legal",
    section:"Records, Fines & Driver License",
    name:"Jackson County — Criminal Set-Aside Information",
    helps:"Jackson County court instructions for setting aside eligible arrest, dismissal, acquittal or conviction records and where local filings are submitted.",
    audience:["Jackson County Residents with Criminal Records"],
    counties:["Jackson"],
    cost:"Fees may apply",
    phone:"541-776-7171",
    address:"Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/go/pages/criminal-cases.aspx",
    labels:["EXPUNGEMENT", "JACKSON", "COURT"],
    keywords:["set aside", "expungement", "Medford", "criminal record"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-expungement",
    category:"legal",
    section:"Records, Fines & Driver License",
    name:"Josephine County — Expungement Information",
    helps:"Josephine County court page explaining adult criminal record set-asides and linking to statewide forms and instructions; it also points to juvenile-record expunction information.",
    audience:["Josephine County Residents with Criminal Records"],
    counties:["Josephine"],
    cost:"Fees may apply",
    phone:"541-476-2309",
    address:"Grants Pass",
    website:"https://www.courts.oregon.gov/courts/josephine/help/Pages/expungements.aspx",
    labels:["EXPUNGEMENT", "JOSEPHINE", "COURT"],
    keywords:["expungement", "set aside", "Grants Pass", "juvenile record"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-license-reinstatement",
    category:"legal",
    section:"Records, Fines & Driver License",
    name:"Oregon License Reinstatement Program — Circuit Court Debt",
    helps:"State program that may help people with qualifying Oregon circuit-court debt release a driver-license hold after setting up the required payment plan. It does not cover every suspension reason.",
    audience:["People with Suspended Licenses", "People with Court Debt"],
    counties:["Jackson", "Josephine"],
    cost:"Program requires qualifying debt and payment terms",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/dor/programs/Collections/Pages/license-reinstatement.aspx",
    labels:["LICENSE REINSTATEMENT", "COURT DEBT", "TRANSPORTATION CROSS-LINK"],
    keywords:["license back", "suspended license", "court debt", "DMV hold", "reinstatement"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-worker-rights",
    category:"legal",
    section:"Work, Wages & Civil Rights",
    name:"BOLI — Oregon Worker Rights",
    helps:"Official Oregon worker-rights landing page for wages, overtime, breaks, sick time, final pay, discrimination, equal pay, leave and other workplace protections.",
    audience:["Workers", "Employees", "Job Applicants"],
    counties:["Jackson", "Josephine"],
    cost:"Free government information",
    phone:"971-245-3844",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/workers/pages/default.aspx",
    labels:["WORKER RIGHTS", "WAGES", "BOLI"],
    keywords:["unpaid wages", "overtime", "breaks", "sick time", "final paycheck", "equal pay", "pregnancy", "domestic violence"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-worker-complaint",
    category:"legal",
    section:"Work, Wages & Civil Rights",
    name:"BOLI — File a Worker Rights Complaint",
    helps:"Official complaint pathway when an Oregon employer may be violating wage, discrimination, leave or other worker-protection laws.",
    audience:["Workers", "Employees"],
    counties:["Jackson", "Josephine"],
    cost:"Free complaint process",
    phone:"971-245-3844",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/workers/Pages/complaint.aspx",
    labels:["COMPLAINT", "EMPLOYMENT", "BOLI"],
    keywords:["file complaint", "wage claim", "harassment", "discrimination", "retaliation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-civil-rights",
    category:"legal",
    section:"Work, Wages & Civil Rights",
    name:"BOLI — Civil Rights & Discrimination",
    helps:"Oregon civil-rights hub covering discrimination and harassment at work, housing discrimination, disability rights, public accommodations, racial discrimination, equal pay and complaint options.",
    audience:["Everyone", "Workers", "Renters", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and complaint process",
    phone:"971-245-3844",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/civil-rights/Pages/default.aspx",
    labels:["CIVIL RIGHTS", "DISCRIMINATION", "PUBLIC PLACES"],
    keywords:["civil rights", "discrimination", "public accommodation", "race", "gender", "disability", "retaliation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"boli-immigrant-workers",
    category:"legal",
    section:"Work, Wages & Civil Rights",
    name:"BOLI — Immigrant Rights on the Job",
    helps:"Explains Oregon wage and civil-rights protections for workers regardless of immigration status, including retaliation protections when workers raise wage, safety or other workplace concerns.",
    audience:["Immigrant Workers", "Employees"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boli/workers/pages/immigrant-rights-on-the-job.aspx",
    labels:["IMMIGRANT WORKERS", "EMPLOYMENT RIGHTS"],
    keywords:["immigrant worker", "ICE retaliation", "wages", "national origin", "workplace rights"],
    lastVerified:"2026-09-04"
  },
  {
    id:"dro",
    category:"legal",
    section:"Disability, Mental Health & Health-Care Rights",
    name:"Disability Rights Oregon",
    helps:"Oregon's protection-and-advocacy organization for disability-related legal issues. Its current resources cover accessibility, employment, housing, mental health, education, guardianship, service animals, financial protection and more.",
    audience:["People with Disabilities", "Families", "Advocates"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; individual case priorities apply",
    phone:"503-243-2081",
    address:"Oregon statewide",
    website:"https://www.droregon.org/",
    labels:["DISABILITY RIGHTS", "LEGAL ADVOCACY", "STATEWIDE"],
    keywords:["disability", "ADA", "mental health", "education", "guardianship", "service animals", "housing", "employment"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohp-member-rights",
    category:"legal",
    section:"Disability, Mental Health & Health-Care Rights",
    name:"Oregon Health Plan — Member Rights",
    helps:"Official OHP rights, including behavioral-health and substance-use treatment without a referral, access to records, denial notices, complaint rights and help with appeals/hearings.",
    audience:["OHP Members", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/HSD/OHP/Pages/Member-Rights.aspx",
    labels:["OHP RIGHTS", "HEALTH CARE", "BEHAVIORAL HEALTH"],
    keywords:["OHP rights", "mental health", "substance use", "records", "complaint", "denial"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ohp-appeals",
    category:"legal",
    section:"Disability, Mental Health & Health-Care Rights",
    name:"Oregon Health Plan — Appeals & Hearings",
    helps:"Official process and deadlines for challenging certain OHP or coordinated-care-organization denials, including appeals and administrative hearings.",
    audience:["OHP Members", "Representatives", "Providers"],
    counties:["Jackson", "Josephine"],
    cost:"Free administrative process",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/OHP/Members/Pages/Appeals-Hearings.aspx",
    labels:["OHP APPEAL", "HEARING", "DENIAL"],
    keywords:["OHP appeal", "hearing", "denied service", "CCO denial", "notice of adverse benefit"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-civil-commitment",
    category:"legal",
    section:"Disability, Mental Health & Health-Care Rights",
    name:"Oregon Health Authority — Civil Commitment",
    helps:"Official information about Oregon's civil-commitment process, where a judge decides whether a person alleged to be mentally ill must accept treatment.",
    audience:["People with Mental Health Concerns", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/hsd/amh/pages/civil-commitment.aspx",
    labels:["MENTAL HEALTH LAW", "CIVIL COMMITMENT"],
    keywords:["civil commitment", "involuntary treatment", "mental health court", "commitment hearing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"mental-health-declaration",
    category:"legal",
    section:"Disability, Mental Health & Health-Care Rights",
    name:"Oregon Health Authority — Health-Care Decisions & Mental Health Declaration",
    helps:"Official information and forms for advance health-care decisions, including Oregon's Declaration for Mental Health Treatment and naming someone to make health-care decisions in qualifying situations.",
    audience:["Adults", "People with Mental Health Conditions", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free forms and information",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/oha/hsd/ohp/pages/decisions.aspx",
    labels:["MENTAL HEALTH DECLARATION", "ADVANCE PLANNING"],
    keywords:["mental health declaration", "advance directive", "health care representative", "treatment wishes"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-doj-consumer",
    category:"legal",
    section:"Money, Debt, Scams & Consumer Problems",
    name:"Oregon DOJ — Consumer Protection",
    helps:"Strong state landing page for consumer complaints, debt and credit issues, identity theft/data breaches, scams and fraud, vehicles, home/mortgage problems and marketplace concerns.",
    audience:["Consumers", "Families", "Older Adults"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and complaint help",
    phone:"877-877-9392",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/consumer-protection/",
    labels:["CONSUMER", "SCAMS", "IDENTITY THEFT", "COMPLAINT"],
    keywords:["debt collector", "identity theft", "scam", "fraud", "car dealer", "mortgage", "consumer complaint"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-court-debt",
    category:"legal",
    section:"Money, Debt, Scams & Consumer Problems",
    name:"Oregon Courts — Debt Collection Cases",
    helps:"Official self-help information for people suing over money or being sued for debt, including garnishment, repossession, debt-buyer cases and small-claims links.",
    audience:["People Owed Money", "People Sued for Debt", "Consumers"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; filing fees may apply",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/help/pages/debtcollection.aspx",
    labels:["DEBT COLLECTION", "GARNISHMENT", "COURT"],
    keywords:["debt lawsuit", "garnishment", "repossession", "collection", "small claims"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-law-help-immigration",
    category:"legal",
    section:"Immigration & Language Rights",
    name:"Oregon Law Help — Immigration Legal Help & Know Your Rights",
    helps:"Attorney-reviewed Oregon immigration information covering trusted legal help, immigration options, deportation/court cases, immigration-officer encounters, Oregon sanctuary protections and scam avoidance.",
    audience:["Immigrants", "Refugees", "Mixed-Status Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; linked legal programs vary",
    address:"Oregon statewide",
    website:"https://oregonlawhelp.org/topics/immigration",
    labels:["IMMIGRATION", "KNOW YOUR RIGHTS", "LEGAL HELP"],
    keywords:["immigration", "ICE", "deportation", "green card", "asylum", "sanctuary", "immigration lawyer"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-crime-victims",
    category:"legal",
    section:"Crime Victims & Survivor Rights",
    name:"Oregon DOJ — Crime Victim & Survivor Services",
    helps:"Statewide hub for crime-victim rights, county victim-assistance programs, legal resources and Crime Victims' Compensation for qualifying crime-related expenses.",
    audience:["Crime Victims", "Survivors", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; compensation eligibility applies",
    phone:"503-378-5348",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/",
    labels:["CRIME VICTIMS", "RIGHTS", "COMPENSATION"],
    keywords:["crime victim", "victim rights", "compensation", "survivor", "restitution"],
    lastVerified:"2026-09-04"
  },
  {
    id:"odhs-senior-legal",
    category:"legal",
    section:"Seniors, Elder Abuse & Legal Assistance",
    name:"ODHS — Legal Assistance for Older Adults",
    helps:"Official statewide information on legal assistance for adults 60+ with priority issues such as income, benefits, health care, long-term care, housing, utilities, elder abuse, unwanted guardianship and age discrimination.",
    audience:["Adults 60+", "Caregivers", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free referral; local legal-service capacity varies",
    phone:"855-673-2372",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/providers-partners/community-services-supports/Pages/legal-assistance.aspx",
    labels:["OLDER ADULTS", "LEGAL ASSISTANCE", "ELDER RIGHTS"],
    keywords:["senior lawyer", "elder law", "elder abuse", "unwanted guardianship", "age discrimination"],
    lastVerified:"2026-09-04"
  },
  {
    id:"osbar-wills-estates",
    category:"legal",
    section:"Wills, Probate & Life Planning",
    name:"Oregon State Bar — Wills, Trusts & Elder Law",
    helps:"Public legal-information hub for wills, probate, trusts, advance directives, powers of attorney and other estate/life-planning topics.",
    audience:["Adults", "Seniors", "Families", "Personal Representatives"],
    counties:["Jackson", "Josephine"],
    cost:"Free legal information",
    address:"Oregon statewide",
    website:"https://www.osbar.org/public/legalinfo/wills.html",
    labels:["WILLS", "PROBATE", "TRUSTS", "POA"],
    keywords:["will", "probate", "trust", "power of attorney", "advance directive", "estate"],
    lastVerified:"2026-09-04"
  },
  {
    id:"odhs-guardianship",
    category:"legal",
    section:"Guardianship, Conservatorship & Decision-Making",
    name:"ODHS — Guardianship, Conservatorship & Other Options",
    helps:"Broad decision-making resource covering guardianship, conservatorship, powers of attorney, trusts, mental-health declarations, health-care representatives, supported decision-making and alternatives to guardianship.",
    audience:["Adults", "Families", "Caregivers", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/providers-partners/community-services-supports/Pages/guardianship.aspx",
    labels:["GUARDIANSHIP", "CONSERVATORSHIP", "ALTERNATIVES"],
    keywords:["guardianship", "conservatorship", "POA", "supported decision making", "trust", "mental health declaration"],
    lastVerified:"2026-09-04"
  },
  {
    id:"dro-guardianship-rights",
    category:"legal",
    section:"Guardianship, Conservatorship & Decision-Making",
    name:"Disability Rights Oregon — Guardianship Rights",
    helps:"Rights-focused information for people with disabilities who have a guardian or are facing a proposed guardianship, including limiting or ending guardianship and alternatives that preserve independence.",
    audience:["People with Disabilities", "Protected Persons", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.droregon.org/guardianship",
    labels:["GUARDIANSHIP RIGHTS", "DISABILITY", "SELF-DETERMINATION"],
    keywords:["end guardianship", "limit guardianship", "supported decision making", "protected person"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-business-registry",
    category:"legal",
    section:"Business, Contractors, Taxes & Workers",
    name:"Oregon Secretary of State — Register a Business",
    helps:"Official Oregon Business Registry starting point for business-name availability, business registration, renewals and Corporation Division filings.",
    audience:["Business Owners", "Entrepreneurs", "Nonprofits"],
    counties:["Jackson", "Josephine"],
    cost:"Registration/filing fees vary",
    phone:"503-986-2200",
    address:"Oregon statewide",
    website:"https://sos.oregon.gov/business/register/pages/default.aspx",
    labels:["BUSINESS REGISTRY", "LLC", "OFFICIAL"],
    keywords:["LLC", "business name", "register business", "renew business", "Corporation Division"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-ccb-license",
    category:"legal",
    section:"Business, Contractors, Taxes & Workers",
    name:"Oregon Construction Contractors Board — CCB License",
    helps:"Official licensing page explaining when construction and repair work requires a CCB license. It specifically lists painting, carpentry, handyman work and most construction/repair services as licensed work, while some cleaning-only activities are examples that do not require a CCB license.",
    audience:["Contractors", "Handymen", "Property-Service Businesses", "Consumers"],
    counties:["Jackson", "Josephine"],
    cost:"Licensing costs apply",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ccb/Pages/CCB%20License.aspx",
    labels:["CCB", "CONTRACTOR LICENSE", "BUSINESS"],
    keywords:["contractor", "handyman", "painting", "carpentry", "pressure washing", "debris cleanup", "CCB"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-payroll-taxes",
    category:"legal",
    section:"Business, Contractors, Taxes & Workers",
    name:"Oregon Department of Revenue — Payroll Taxes & Worker Classification",
    helps:"Official employer guide for Oregon payroll registration, withholding, reporting and resources on employee-versus-independent-contractor classification.",
    audience:["Employers", "Business Owners"],
    counties:["Jackson", "Josephine"],
    cost:"Free information; taxes apply",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/dor/programs/businesses/pages/withholding-and-payroll-tax.aspx",
    labels:["PAYROLL", "EMPLOYEES", "CONTRACTORS", "TAXES"],
    keywords:["payroll", "BIN", "withholding", "independent contractor", "employee classification", "taxes"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-animal-law",
    category:"legal",
    section:"Animals, Service Animals & Veterinary Complaints",
    name:"Jackson County Animal Services — Animal Control Regulations",
    helps:"Official Jackson County animal-control rules covering pet ownership, licensing, nuisance animals, dangerous dogs and enforcement. Cities may have additional local rules.",
    audience:["Pet Owners", "Neighbors", "Animal Caregivers"],
    counties:["Jackson"],
    cost:"Free legal information",
    phone:"541-774-6654",
    address:"Jackson County",
    website:"https://jacksoncountyor.gov/departments/health___human_services/programs_and_services/animal_services/animal_control_regulations.php",
    labels:["ANIMAL LAW", "JACKSON", "DOGS"],
    keywords:["dog law", "animal control", "dangerous dog", "barking", "license", "nuisance"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-animal-law",
    category:"legal",
    section:"Animals, Service Animals & Veterinary Complaints",
    name:"Oregon Legislature — State Dog & Animal Control Law",
    helps:"Official Oregon statute chapter covering statewide dog-control law, dangerous dogs, licensing and related rules that interact with county and city ordinances.",
    audience:["Pet Owners", "Residents", "Animal Professionals"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregonlegislature.gov/bills_laws/ors/ors609.html",
    labels:["ANIMAL LAW", "STATE LAW"],
    keywords:["ORS 609", "dog control", "dangerous dog", "dog license", "county animal law"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ovmeb-complaints",
    category:"legal",
    section:"Animals, Service Animals & Veterinary Complaints",
    name:"Oregon Veterinary Medical Examining Board — File a Complaint",
    helps:"Official complaint process for concerns that an Oregon veterinary facility, veterinarian or certified veterinary technician may have violated veterinary practice rules or laws.",
    audience:["Pet Owners", "Veterinary Clients"],
    counties:["Jackson", "Josephine"],
    cost:"Free complaint process",
    phone:"971-673-0222",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ovmeb/pages/how_to_file.aspx",
    labels:["VETERINARY COMPLAINT", "STATE BOARD"],
    keywords:["vet complaint", "veterinarian complaint", "veterinary board", "animal medical care"],
    lastVerified:"2026-09-04"
  },
  {
    id:"dro-service-animals",
    category:"legal",
    section:"Animals, Service Animals & Veterinary Complaints",
    name:"Disability Rights Oregon — Service & Assistance Animals",
    helps:"Rights information on service and assistance animals in public places, housing, employment and transportation. Rules differ by setting, so use this as a rights guide rather than a pet-registration site.",
    audience:["People with Disabilities", "Tenants", "Workers"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Oregon statewide",
    website:"https://www.droregon.org/disability-rights-oregon-resources/service-and-assistance-animals-in-oregon",
    labels:["SERVICE ANIMALS", "DISABILITY RIGHTS"],
    keywords:["service dog", "assistance animal", "emotional support animal", "reasonable accommodation", "ADA"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ode-complaints",
    category:"legal",
    section:"School, IEP & Education Rights",
    name:"Oregon Department of Education — School Complaints & Civil Rights",
    helps:"Official complaint landing page for concerns involving Oregon public schools, including special-education complaints and school civil-rights/discrimination complaints.",
    audience:["Parents", "Students", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"503-947-5600",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ode/about-us/Pages/Complaints.aspx",
    labels:["SCHOOL RIGHTS", "COMPLAINTS", "CIVIL RIGHTS"],
    keywords:["school complaint", "discrimination", "504", "civil rights", "special education"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ode-special-ed-disputes",
    category:"legal",
    section:"School, IEP & Education Rights",
    name:"Oregon Department of Education — Special Education Dispute Resolution",
    helps:"Official IDEA dispute-resolution information for IEP facilitation, mediation, state complaints and due-process hearings when families and schools disagree about special-education identification, evaluation, placement or services.",
    audience:["Parents", "Students with Disabilities", "IEP Teams"],
    counties:["Jackson", "Josephine"],
    cost:"Free state process; legal representation varies",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/ode/rules-and-policies/Pages/Dispute-Resolution.aspx",
    labels:["IEP", "IDEA", "MEDIATION", "DUE PROCESS"],
    keywords:["IEP dispute", "special education complaint", "IDEA", "mediation", "due process", "504"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-small-claims",
    category:"legal",
    section:"Small Claims & Court Self-Help",
    name:"Oregon Courts — Small Claims Forms & Information",
    helps:"Official statewide forms and self-help links for small-claims cases, including interactive filing options where available.",
    audience:["Consumers", "Landlords", "Tenants", "Businesses", "Residents"],
    counties:["Jackson", "Josephine"],
    cost:"Court filing fees apply; waivers/deferrals may be available",
    address:"Oregon statewide",
    website:"https://www.courts.oregon.gov/forms/pages/small-claims.aspx",
    labels:["SMALL CLAIMS", "COURT FORMS"],
    keywords:["small claims", "sue", "money owed", "court forms", "debt"],
    lastVerified:"2026-09-04"
  },
  {
    id:"legal-211",
    category:"legal",
    section:"Small Claims & Court Self-Help",
    name:"211info — Legal & Public Safety Search",
    helps:"Use Oregon's larger live directory to find additional legal aid, tenant advocacy, victim services, immigration help and public-safety resources not yet individually listed in the Hub.",
    audience:["Everyone"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["LIVE DIRECTORY", "211", "CATCH-ALL"],
    keywords:["legal", "lawyer", "tenant", "victim", "immigration", "public safety"],
    lastVerified:"2026-09-04"
  }
];
