/* Flourish Anyway Community Resource Hub
   MONEY & CREDIT — September 2026 expanded rebuild
   Jackson + Josephine Counties, Oregon
   Upload as: money-data.js

   RESOURCE DATA ONLY.
   Shared category/search/loader/index/Help Plan files are intentionally untouched.

   Structure:
   1) Money & Credit Basics
   2) Debt & Financial Crisis Help
   3) Saving, Investing & Retirement
   4) Real Estate, Rental Property & Wealth Building
   5) Upcoming Money & Investment Classes
*/

window.FLOURISH_MONEY_DATA = [
  {id:"access-financial-literacy",category:"money",section:"Money & Credit Basics",name:"ACCESS — Financial Literacy",helps:"Free classes covering budgeting, credit management, savings goals, emergency savings and everyday financial decisions.",audience:["Adults","Families","Renters","Future Homebuyers"],counties:["Jackson","Josephine"],cost:"Free; ACCESS states no eligibility requirements for its financial-literacy class",phone:"541-774-4305",address:"Virtual classes + ACCESS Homeownership Center, Medford",website:"https://accesshelps.org/services/",labels:["FREE","BUDGETING","CREDIT","SAVINGS"],keywords:["budget","credit score","money management","saving","financial literacy"],lastVerified:"2026-09-04"},
  {id:"access-homeownership-center",category:"money",section:"Money & Credit Basics",name:"ACCESS — Homeownership Center",helps:"Financial education, homebuyer preparation and counseling that can help households understand credit, budgeting and the financial side of buying or keeping a home.",audience:["Adults","Families","Homebuyers","Homeowners"],counties:["Jackson"],cost:"Program/class costs vary; some education is free",phone:"541-774-4305",address:"3630 Aviation Way, Medford",website:"https://accesshelps.org/services/",labels:["HOMEOWNERSHIP","CREDIT","BUDGETING"],keywords:["homebuyer","mortgage","credit","budget","homeownership counseling"],lastVerified:"2026-09-04"},
  {id:"access-rent-well-money",category:"money",section:"Money & Credit Basics",name:"ACCESS — Rent Well Tenant Education",helps:"Tenant education that also teaches practical money and credit skills: understanding a lease, managing credit, landlord communication and realistic housing searches. ACCESS brings in cross-sector instructors and guest speakers for parts of its housing education.",audience:["Renters","Future Renters","Families"],counties:["Jackson"],cost:"Check current class schedule",phone:"541-779-6691",address:"Medford / class schedule varies",website:"https://accesshelps.org/rental-assistance/",labels:["RENT WELL","CREDIT","TENANT EDUCATION"],keywords:["Rent Well","credit repair","budget","tenant class","bad credit","eviction history"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"rogue-credit-union-financial-education",category:"money",section:"Money & Credit Basics",name:"Rogue Credit Union — Free Financial Education",helps:"Free financial education with learning resources, classroom/community presentations and curriculum. Topics include budgeting, credit and debt, identity theft, insurance, savings, investing, taxes and retirement.",audience:["Adults","Students","Families","Community Groups","Workplaces"],counties:["Jackson","Josephine"],cost:"Free educational resources and presentations",phone:"800-856-7328",address:"Southern Oregon",website:"https://www.roguecu.org/community/financial-education",labels:["FREE","FINANCIAL EDUCATION","CREDIT","RETIREMENT"],keywords:["Rogue Credit Union","money class","budget","credit","debt","investing","retirement","presentation"],lastVerified:"2026-09-04"},
  {id:"neighborworks-financial-literacy",category:"money",section:"Money & Credit Basics",name:"NeighborWorks Umpqua — Financial Literacy & Coaching",helps:"Financial-literacy classes plus one-on-one financial coaching covering budgeting, saving, paying off debt and building better credit. NeighborWorks serves Josephine County and other Southern Oregon communities.",audience:["Adults","Families","Future Homebuyers"],counties:["Josephine"],cost:"Financial coaching is free; course costs can vary",phone:"541-673-4909",address:"Serves Josephine County; main office Roseburg",website:"https://www.nwumpqua.org/our-programs/home-buyer-and-financial-literacy-programs/",labels:["FINANCIAL COACHING","BUDGET","CREDIT","JOSEPHINE"],keywords:["NeighborWorks Umpqua","financial literacy","coach","debt","credit","budget"],lastVerified:"2026-09-04"},
  {id:"annual-credit-report",category:"money",section:"Money & Credit Basics",name:"AnnualCreditReport.com — Official Free Credit Reports",helps:"Federally authorized site for obtaining free credit reports from Equifax, Experian and TransUnion.",audience:["Adults","Consumers"],counties:["Jackson","Josephine"],cost:"Free",phone:"877-322-8228",address:"Nationwide",website:"https://www.annualcreditreport.com/",labels:["CREDIT REPORT","FREE","OFFICIAL"],keywords:["credit report","Equifax","Experian","TransUnion","credit history"],lastVerified:"2026-09-04"},

  {id:"cccs-southern-oregon",category:"money",section:"Debt & Financial Crisis Help",name:"Consumer Credit Counseling Service of Southern Oregon",helps:"Longstanding Medford nonprofit-style credit counseling resource offering confidential credit counseling, personalized debt-management plans, pre-filing bankruptcy counseling and pre-discharge bankruptcy education.",audience:["Adults","People in Debt","Consumers"],counties:["Jackson","Josephine"],cost:"Counseling/program fees vary; ask before enrolling",phone:"541-779-2273",address:"820 Crater Lake Avenue, Suite 202, Medford",website:"https://improvedcredit.org/contact/",labels:["DEBT","CREDIT COUNSELING","MEDFORD"],keywords:["collections","credit cards","debt management","bankruptcy counseling","Consumer Credit Counseling Southern Oregon"],lastVerified:"2026-09-04"},
  {id:"consumer-financial-protection",category:"money",section:"Debt & Financial Crisis Help",name:"Consumer Financial Protection Bureau — Money & Debt Help",helps:"Free federal information on credit reports, debt collection, loans, banking, scams and consumer financial rights; complaints can be submitted online.",audience:["Adults","Consumers"],counties:["Jackson","Josephine"],cost:"Free",phone:"855-411-2372",address:"Federal resource",website:"https://www.consumerfinance.gov/consumer-tools/",apply:"https://www.consumerfinance.gov/complaint/",labels:["CREDIT","DEBT","CONSUMER RIGHTS"],keywords:["credit report","debt collector","bank","loan","scam","complaint"],lastVerified:"2026-09-04"},
  {id:"oregon-taxpayer-advocate",category:"money",section:"Debt & Financial Crisis Help",name:"Oregon Department of Revenue — Taxpayer Advocate",helps:"Helps taxpayers who have unresolved Oregon tax problems or significant hardship related to a Department of Revenue issue.",audience:["Oregon Taxpayers"],counties:["Jackson","Josephine"],cost:"Free government assistance",phone:"503-945-8700",address:"Oregon statewide",website:"https://www.oregon.gov/dor/pages/taxpayer-advocate.aspx",labels:["TAXES","HARDSHIP","STATE HELP"],keywords:["tax debt","Oregon taxes","hardship","taxpayer advocate"],lastVerified:"2026-09-04"},
  {id:"oregon-one-benefits",category:"money",section:"Debt & Financial Crisis Help",name:"Oregon ONE — Food, Cash, Medical & Child Care Benefits",helps:"Official application pathway for SNAP, TANF cash benefits, Oregon Health Plan and Employment Related Day Care. Use when an income crisis means the household needs benefits as well as budgeting help.",audience:["Adults","Families","Parents","Pregnant People"],counties:["Jackson","Josephine"],cost:"Free to apply",phone:"800-699-9075",address:"Oregon statewide",website:"https://www.oregon.gov/odhs/benefits/pages/default.aspx",apply:"https://benefits.oregon.gov/",labels:["BENEFITS","CASH","FOOD","CHILD CARE"],keywords:["ONE","SNAP","TANF","OHP","ERDC","financial crisis"],lastVerified:"2026-09-04"},
  {id:"oregon-ta-dvs",category:"money",section:"Debt & Financial Crisis Help",name:"Oregon TA-DVS — Domestic Violence Financial Assistance",helps:"Short-term financial help for eligible families and pregnant people experiencing domestic violence, including some safety, housing and moving-related expenses.",audience:["Domestic Violence Survivors","Parents","Pregnant People","Families"],counties:["Jackson","Josephine"],cost:"Free benefit if eligible",phone:"800-699-9075",address:"Oregon statewide",website:"https://www.oregon.gov/odhs/cash/pages/default.aspx",apply:"https://benefits.oregon.gov/",labels:["DOMESTIC VIOLENCE","CASH HELP","SAFETY"],keywords:["TA-DVS","domestic violence","moving money","deposit","safety"],lastVerified:"2026-09-04"},
  {id:"oregon-money-management",category:"money",section:"Debt & Financial Crisis Help",name:"Oregon Money Management Program",helps:"Volunteer-supported money-management help for eligible older adults and adults with disabilities who need assistance organizing bills and protecting financial independence.",audience:["Seniors","Adults with Disabilities"],counties:["Jackson","Josephine"],cost:"Free to eligible participants",phone:"855-673-2372",address:"Oregon ADRC / local aging-disability network",website:"https://www.adrcoforegon.org/",labels:["BILL PAYING","SENIORS","DISABILITY"],keywords:["money management","bill paying","senior finances","disability","ADRC"],lastVerified:"2026-09-04"},
  {id:"211-money-search",category:"money",section:"Debt & Financial Crisis Help",name:"211info — Money, Benefits & Financial Assistance Search",helps:"Live Oregon directory for cash assistance, benefits, tax help, budgeting, debt help, emergency financial assistance and other programs whose availability changes.",audience:["Everyone"],counties:["Jackson","Josephine"],cost:"Free information and referral",phone:"211",address:"Oregon statewide",website:"https://www.211info.org/",labels:["211","LIVE DIRECTORY","FINANCIAL HELP"],keywords:["211","money","cash","credit","debt","benefits","financial assistance","tax"],lastVerified:"2026-09-04",scheduleChangesOften:true},

  {id:"oregon-pacific-events",category:"money",section:"Saving, Investing & Retirement",name:"Oregon Pacific Financial Advisors — Public Seminars & Webinars",helps:"Medford financial-planning firm with a current public education calendar covering topics such as tax planning, Social Security, retirement, Oregon PERS, long-term care, college planning, budgeting and financial fitness. Use the live events page because dates change.",audience:["Adults","Workers","Retirees","PERS Members","Families"],counties:["Jackson","Josephine"],cost:"Many listed educational events are free; confirm registration details",phone:"541-772-1116",address:"210 W 8th Street, Medford + online webinars",website:"https://www.opfa.com/events",labels:["SEMINARS","RETIREMENT","INVESTING","MEDFORD"],keywords:["Oregon Pacific Financial Advisors","OPFA","tax planning","Social Security","retirement webinar","PERS seminar","budget class"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"rogue-advisors-grants-pass",category:"money",section:"Saving, Investing & Retirement",name:"Rogue Advisors — Grants Pass Fee-Only Fiduciary Planning",helps:"Local fee-only Registered Investment Adviser providing financial planning, investment management and education. Useful for people who want professional guidance before a major investment or retirement decision. The initial meeting is offered at no cost or obligation; ongoing services have fees.",audience:["Adults","Families","Business Owners","Investors"],counties:["Josephine"],cost:"Initial meeting no cost/obligation; advisory services are fee-based",phone:"541-474-9700",address:"1246 NE 7th Street, Suite B, Grants Pass",website:"https://rogueadvisors.com/",labels:["FIDUCIARY","FEE-ONLY","INVESTING","GRANTS PASS"],keywords:["financial advisor","fiduciary","RIA","investment management","retirement","Rogue Advisors"],lastVerified:"2026-09-04"},
  {id:"oregonsaves",category:"money",section:"Saving, Investing & Retirement",name:"OregonSaves — Retirement Savings",helps:"Oregon retirement-savings program for workers whose employers facilitate OregonSaves and for eligible people who save on their own. Contributions go to a Roth IRA; participation is voluntary and investment values can rise or fall.",audience:["Workers","Self-Employed Adults","First-Time Savers"],counties:["Jackson","Josephine"],cost:"Program fees apply to accounts; no taxpayer-funded participation fee",phone:"844-661-6777",address:"Oregon statewide",website:"https://www.oregonsaves.com/savers",labels:["RETIREMENT","ROTH IRA","OREGON"],keywords:["OregonSaves","retirement savings","Roth IRA","workplace retirement","self employed"],lastVerified:"2026-09-04"},
  {id:"oregonsaves-webinars",category:"money",section:"Saving, Investing & Retirement",name:"OregonSaves — Saver Webinars & Resources",helps:"OregonSaves offers recurring introductory webinars for savers, plus retirement calculators, forms and educational resources. Events are offered in English and Spanish.",audience:["OregonSaves Participants","Workers","Adults"],counties:["Jackson","Josephine"],cost:"Free education; account fees are separate",phone:"844-661-6777",address:"Online / Oregon statewide",website:"https://www.oregonsaves.com/resources/saver",labels:["WEBINAR","RETIREMENT","ENGLISH","SPANISH"],keywords:["OregonSaves webinar","retirement class","saver education","Spanish retirement"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"oregon-pers-education",category:"money",section:"Saving, Investing & Retirement",name:"Oregon PERS — Retirement Education & Workshops",helps:"Official PERS education for public employees, including group workshops about membership, benefits and retirement. PERS and OSGP also provide retirement checklists, videos and investment/retirement-strategy education.",audience:["Oregon Public Employees","PERS Members","Retirees"],counties:["Jackson","Josephine"],cost:"Free official education",phone:"888-320-7377",address:"Oregon statewide / online",website:"https://www.oregon.gov/pers/mem/Pages/Navigate-PERS-OSGP.aspx",labels:["PERS","OSGP","RETIREMENT","WORKSHOPS"],keywords:["PERS workshop","OPSRP","Tier 1","Tier 2","OSGP","public employee retirement"],lastVerified:"2026-09-04"},
  {id:"investor-gov-basics",category:"money",section:"Saving, Investing & Retirement",name:"Investor.gov — Learn Investing Before You Invest",helps:"Free SEC investor education covering savings versus investing, compound growth, risk, diversification, investment products, fees, fraud and planning tools. Good neutral starting point before buying an investment product.",audience:["Beginning Investors","Adults","Families"],counties:["Jackson","Josephine"],cost:"Free",address:"Federal resource",website:"https://www.investor.gov/introduction-investing",labels:["INVESTING BASICS","SEC","FREE"],keywords:["stocks","bonds","ETF","mutual fund","compound interest","risk","diversification","investing beginner"],lastVerified:"2026-09-04"},
  {id:"finra-brokercheck",category:"money",section:"Saving, Investing & Retirement",name:"FINRA BrokerCheck — Check an Investment Professional",helps:"Free tool to research brokers, brokerage firms and investment-adviser information before handing someone money. Shows registration, employment history, regulatory actions, licensing information, arbitrations and complaints where available.",audience:["Investors","Consumers"],counties:["Jackson","Josephine"],cost:"Free",phone:"800-289-9999",address:"National resource",website:"https://brokercheck.finra.org/",labels:["CHECK AN ADVISOR","INVESTOR SAFETY","FREE"],keywords:["financial advisor background","broker license","complaint","investment professional","BrokerCheck"],lastVerified:"2026-09-04"},
  {id:"oregon-dfr-investor-protection",category:"money",section:"Saving, Investing & Retirement",name:"Oregon Division of Financial Regulation — Investor Protection",helps:"Oregon regulator for securities and financial services. Use it to check licensing, ask consumer questions or file a complaint involving financial services or investments.",audience:["Investors","Consumers"],counties:["Jackson","Josephine"],cost:"Free government help",phone:"888-877-4894",address:"Oregon statewide",website:"https://dfr.oregon.gov/pages/index.aspx",labels:["INVESTMENT FRAUD","LICENSE CHECK","COMPLAINT"],keywords:["investment scam","financial advisor license","securities complaint","Oregon DFR"],lastVerified:"2026-09-04"},
  {id:"neighborworks-matched-savings",category:"money",section:"Saving, Investing & Retirement",name:"NeighborWorks Umpqua — Dream$avers Matched Savings",helps:"Matched-savings program that can help eligible participants save toward approved goals while receiving financial education and coaching. Current program information describes a $5 match for every $1 saved, subject to eligibility and service-area restrictions.",audience:["Low- and Moderate-Income Savers","Future Homebuyers","Students","Homeowners"],counties:["Josephine"],cost:"Eligibility applies",phone:"541-673-4909",address:"Serves Josephine County; main office Roseburg",website:"https://www.nwumpqua.org/our-programs/matched-savings-programs/",labels:["MATCHED SAVINGS","IDA","COACHING"],keywords:["DreamSavers","IDA","matched savings","5 to 1 match","home purchase","education"],lastVerified:"2026-09-04"},

  {id:"southern-oregon-real-estate-meetup",category:"money",section:"Real Estate, Rental Property & Wealth Building",name:"Southern Oregon Real Estate Meetup — Rogue Valley Investors",helps:"Local network for new and experienced real-estate investors to learn from each other and connect. The group says it has no dues and does not sell get-rich-quick courses. Topics have included investment strategy, title/closing education and networking. Use the live event source because meeting details change.",audience:["Beginning Investors","Experienced Investors","Real Estate Professionals"],counties:["Jackson","Josephine"],cost:"Group says no dues; individual event costs may vary",address:"Medford / Phoenix area; locations vary",website:"https://www.meetup.com/rogue-valley-real-estate-investors-network/",labels:["REAL ESTATE INVESTING","BEGINNER FRIENDLY","NETWORKING"],keywords:["Rogue Valley Real Estate Investors","real estate meetup","rental investing","property investing","Medford investor"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"soroa-rental-owners",category:"money",section:"Real Estate, Rental Property & Wealth Building",name:"Southern Oregon Rental Owners Association — SOROA",helps:"Nonprofit membership association for rental owners, housing providers, property managers and related professionals serving Jackson and Josephine counties. Offers training/events and is a certified continuing-education provider for property managers.",audience:["Landlords","Rental Owners","Property Managers","Future Rental Owners"],counties:["Jackson","Josephine"],cost:"Membership and some training fees apply",phone:"541-842-7676",address:"830 Bennett Avenue, Suite A, Medford",website:"https://soroa.net/",labels:["LANDLORD","RENTAL PROPERTY","PROPERTY MANAGEMENT"],keywords:["SOROA","rental owner","landlord class","property manager","rental property education"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"cornerstone-investor-events",category:"money",section:"Real Estate, Rental Property & Wealth Building",name:"Cornerstone Property Group — Investor Education Events",helps:"Medford property-management company that has hosted 2026 investor seminars with a property manager/investor, real-estate agent/investor and lender covering investment property, offers, negotiations, inspections, closing and financing. Use as a source to watch for future classes rather than preserving an expired seminar date.",audience:["Beginning Real Estate Investors","Rental Owners"],counties:["Jackson"],cost:"Event cost varies",address:"Medford; event locations vary",website:"https://www.eventbrite.com/o/cornerstone-property-group-118475655541",labels:["INVESTOR SEMINAR","PROPERTY MANAGEMENT","WATCH FOR EVENTS"],keywords:["Cornerstone Property Group","investor seminar","investment property","financing","Medford"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"commercial-real-estate-roundtable",category:"money",section:"Real Estate, Rental Property & Wealth Building",name:"Commercial Real Estate Roundtable — Medford",helps:"Advanced local meetup for commercial real-estate investing, property development, financing and strategy. It typically meets around the fourth Friday; RSVP and meeting fees apply. This is not a beginner household-finance class.",audience:["Commercial Investors","Developers","Business Owners","Real Estate Professionals"],counties:["Jackson"],cost:"Meeting fee applies; verify current amount",address:"Medford; current meetup location listed online",website:"https://www.meetup.com/commercial-real-estate-roundtable/",labels:["ADVANCED","COMMERCIAL REAL ESTATE","DEVELOPMENT"],keywords:["commercial investing","commercial property","land development","CCIM","Medford"],lastVerified:"2026-09-04",scheduleChangesOften:true},
  {id:"rogue-valley-realtors-classes",category:"money",section:"Real Estate, Rental Property & Wealth Building",name:"Rogue Valley Association of REALTORS® — Classes & Events",helps:"Active local education and networking calendar with Medford and Grants Pass offices. Much of the training is designed for real-estate professionals, so check eligibility before registering. Useful for real-estate careers, market tools, fair housing and professional property education.",audience:["Real Estate Professionals","People Exploring Real Estate Careers"],counties:["Jackson","Josephine"],cost:"Varies; many events require member registration",phone:"541-770-7060",address:"Medford and Grants Pass offices",website:"https://rvar.realtor/classes-events/",labels:["REAL ESTATE CAREER","CLASSES","PROFESSIONAL EDUCATION"],keywords:["RVAR","realtor classes","real estate career","MLS","fair housing","Grants Pass","Medford"],lastVerified:"2026-09-04",scheduleChangesOften:true},

  {id:"upcoming-money-classes",category:"money",section:"Upcoming Money & Investment Classes",name:"Where to Check for Upcoming Money & Investment Classes",helps:"For changing local classes, start with the live calendars and education pages from Oregon Pacific Financial Advisors, Rogue Credit Union, ACCESS, NeighborWorks Umpqua, SOROA, Southern Oregon Real Estate Meetup and Rogue Valley REALTORS. The Hub should link to live sources instead of hard-coding expired seminar dates.",audience:["Adults","Families","Investors","Future Homebuyers","Rental Owners"],counties:["Jackson","Josephine"],cost:"Varies by provider; many education options are free",address:"Jackson + Josephine Counties / online",website:"https://www.opfa.com/events",labels:["LIVE CALENDARS","CLASSES","SEMINARS"],keywords:["upcoming money class","financial seminar","investment class","retirement seminar","real estate class"],lastVerified:"2026-09-04",scheduleChangesOften:true}
];
