/* Flourish Anyway Community Resource Hub
   MONEY & CREDIT
   File name after upload: money-data.js
   Jackson + Josephine Counties, Oregon
   Backbone: 211info + official state/local/provider sources
   Last researched: 2026-08-30
*/

window.FLOURISH_MONEY_DATA = [
  {
    id:"access-financial-literacy",
    category:"money",
    name:"ACCESS — Financial Literacy",
    helps:"Free classes covering budgeting, credit management, savings goals, emergency savings and everyday financial decisions.",
    audience:["Adults","Families","Renters","Future Homebuyers"],
    counties:["Jackson","Josephine"],
    cost:"Free; ACCESS states no eligibility requirements for its financial-literacy class",
    phone:"541-774-4305",
    address:"Virtual classes + ACCESS Homeownership Center, Medford",
    website:"https://accesshelps.org/event/financial-literacy-class-7/",
    labels:["FREE","BUDGETING","CREDIT","SAVINGS"],
    keywords:["budget","credit score","money management","saving","financial literacy"],
    lastVerified:"2026-08-30"
  },
  {
    id:"access-homeownership-center",
    category:"money",
    name:"ACCESS — Homeownership Center",
    helps:"Financial education, homebuyer preparation and counseling that can help households understand credit, budgeting and the financial side of buying or keeping a home.",
    audience:["Adults","Families","Homebuyers","Homeowners"],
    counties:["Jackson"],
    cost:"Program/class costs vary; some education is free",
    phone:"541-774-4305",
    address:"3630 Aviation Way, Medford, OR 97504",
    website:"https://accesshelps.org/services/",
    labels:["HOMEOWNERSHIP","CREDIT","BUDGETING"],
    keywords:["homebuyer","mortgage","credit","budget","homeownership counseling"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-tanf",
    category:"money",
    name:"Oregon TANF — Cash Benefits for Families",
    helps:"Monthly cash benefits for eligible Oregon families with children or qualifying pregnant applicants while they work toward greater financial stability.",
    audience:["Parents","Caregivers","Families","Pregnant People"],
    counties:["Jackson","Josephine"],
    cost:"Free benefit if eligible",
    phone:"800-699-9075",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/odhs/cash/pages/tanf.aspx",
    apply:"https://www.oregon.gov/odhs/benefits/pages/default.aspx",
    source211:"https://www.211info.org/",
    labels:["CASH BENEFIT","FAMILIES","TANF"],
    keywords:["cash assistance","TANF","money","family benefit","EBT"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-ta-dvs",
    category:"money",
    name:"Oregon TA-DVS — Domestic Violence Financial Assistance",
    helps:"Short-term financial help for eligible families and pregnant people experiencing domestic violence, including some safety, housing and moving-related expenses.",
    audience:["Domestic Violence Survivors","Parents","Pregnant People","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free benefit if eligible",
    phone:"800-699-9075",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/odhs/cash/pages/default.aspx",
    apply:"https://www.oregon.gov/odhs/benefits/pages/default.aspx",
    source211:"https://www.211info.org/",
    labels:["DOMESTIC VIOLENCE","CASH HELP","SAFETY"],
    keywords:["TA-DVS","domestic violence","moving money","deposit","safety"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-one-benefits",
    category:"money",
    name:"Oregon ONE — Apply for Food, Cash, Medical & Child Care Benefits",
    helps:"One application portal for SNAP, TANF cash benefits, Oregon Health Plan and Employment Related Day Care.",
    audience:["Adults","Families","Parents","Pregnant People"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"800-699-9075",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/odhs/benefits/pages/default.aspx",
    apply:"https://benefits.oregon.gov/",
    labels:["ONE PORTAL","BENEFITS","CASH","CHILD CARE"],
    keywords:["benefits","ONE","SNAP","TANF","OHP","ERDC","apply"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-erdc",
    category:"money",
    name:"Oregon ERDC — Help Paying for Child Care",
    helps:"Employment Related Day Care helps eligible working or student families pay part of their child-care costs.",
    audience:["Parents","Caregivers","Families"],
    counties:["Jackson","Josephine"],
    cost:"Subsidized child care; some families pay a copay",
    phone:"800-699-9075",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/odhs/benefits/pages/default.aspx",
    apply:"https://benefits.oregon.gov/",
    labels:["CHILD CARE","SUBSIDY","WORK","SCHOOL"],
    keywords:["ERDC","daycare","child care payment","subsidy","copay"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-ebt-help",
    category:"money",
    name:"Oregon EBT / Oregon Trail Card Help",
    helps:"Official help for Oregon Trail Card users receiving SNAP or TANF benefits, including benefit access and card information.",
    audience:["SNAP Recipients","TANF Recipients"],
    counties:["Jackson","Josephine"],
    cost:"Free support",
    phone:"888-997-4447",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/odhs/benefits/pages/ebt.aspx",
    labels:["EBT","OREGON TRAIL CARD","BENEFITS"],
    keywords:["EBT","lost card","Oregon Trail","cash benefit","SNAP"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-lifeline",
    category:"money",
    name:"Oregon Lifeline — Discounted Phone or Internet",
    helps:"Monthly discount on phone or broadband service for qualifying low-income Oregon households.",
    audience:["Low-income Households","SNAP Recipients","Medicaid Recipients"],
    counties:["Jackson","Josephine"],
    cost:"Discount program",
    phone:"800-848-4442",
    address:"Statewide Oregon program",
    website:"https://www.oregon.gov/puc/pages/oregon-lifeline.aspx",
    labels:["PHONE","INTERNET","DISCOUNT"],
    keywords:["Lifeline","cheap phone","internet discount","low income"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-child-support",
    category:"money",
    name:"Oregon Child Support Program",
    helps:"Establishes and modifies child-support orders, helps locate parents, establishes parentage and processes child-support payments.",
    audience:["Parents","Caregivers","Children"],
    counties:["Jackson","Josephine"],
    cost:"Government child-support service",
    phone:"800-850-0228",
    address:"Statewide Oregon program",
    website:"https://www.doj.state.or.us/child-support/",
    labels:["CHILD SUPPORT","PARENTS","PAYMENTS"],
    keywords:["child support","parentage","paternity","support order","back support"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ssa-ssi",
    category:"money",
    name:"Social Security — SSI",
    helps:"Federal monthly cash assistance for qualifying people with limited income/resources who are disabled, blind or age 65+.",
    audience:["Disability","Blind","Seniors 65+"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"800-772-1213",
    address:"Federal program",
    website:"https://www.ssa.gov/ssi",
    labels:["SSI","DISABILITY","SENIORS","CASH BENEFIT"],
    keywords:["SSI","Social Security","disabled","low income","cash"],
    lastVerified:"2026-08-30"
  },
  {
    id:"ssa-ssdi",
    category:"money",
    name:"Social Security — Disability Benefits (SSDI)",
    helps:"Federal disability benefits for qualifying workers with sufficient Social Security work history.",
    audience:["Adults with Disabilities","Workers"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"800-772-1213",
    address:"Federal program",
    website:"https://www.ssa.gov/disability",
    labels:["SSDI","DISABILITY","INCOME"],
    keywords:["SSDI","disability benefit","Social Security","unable to work"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-veterans-benefits",
    category:"money",
    name:"Oregon Department of Veterans’ Affairs — Benefits Help",
    helps:"Helps veterans and families understand and pursue federal and state veteran benefits, compensation, pensions and other supports.",
    audience:["Veterans","Spouses","Survivors","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free benefits assistance",
    phone:"800-692-9666",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odva/benefits/pages/default.aspx",
    labels:["VETERANS","BENEFITS","PENSION","COMPENSATION"],
    keywords:["veteran benefits","VA","pension","disability compensation","survivor"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-money-management",
    category:"money",
    name:"Oregon Money Management Program",
    helps:"Volunteer-supported money-management help for eligible older adults and adults with disabilities who need assistance organizing bills and protecting financial independence.",
    audience:["Seniors","Adults with Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Free to eligible participants",
    phone:"855-673-2372",
    address:"Oregon ADRC / local aging-disability network",
    website:"https://www.adrcoforegon.org/",
    labels:["BILL PAYING","SENIORS","DISABILITY"],
    keywords:["money management","bill paying","senior finances","disability","ADRC"],
    lastVerified:"2026-08-30"
  },
  {
    id:"consumer-financial-protection",
    category:"money",
    name:"Consumer Financial Protection Bureau — Money & Debt Help",
    helps:"Free federal information on credit reports, debt collection, loans, banking, scams and consumer financial rights; complaints can be submitted online.",
    audience:["Adults","Consumers"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"855-411-2372",
    address:"Federal resource",
    website:"https://www.consumerfinance.gov/consumer-tools/",
    apply:"https://www.consumerfinance.gov/complaint/",
    labels:["CREDIT","DEBT","CONSUMER RIGHTS"],
    keywords:["credit report","debt collector","bank","loan","scam","complaint"],
    lastVerified:"2026-08-30"
  },
  {
    id:"annual-credit-report",
    category:"money",
    name:"AnnualCreditReport.com — Official Free Credit Reports",
    helps:"Federally authorized site for obtaining free credit reports from Equifax, Experian and TransUnion.",
    audience:["Adults","Consumers"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"877-322-8228",
    address:"Nationwide",
    website:"https://www.annualcreditreport.com/",
    labels:["CREDIT REPORT","FREE","OFFICIAL"],
    keywords:["credit report","Equifax","Experian","TransUnion","credit history"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-taxpayer-advocate",
    category:"money",
    name:"Oregon Department of Revenue — Taxpayer Advocate",
    helps:"Helps taxpayers who have unresolved Oregon tax problems or are experiencing significant hardship related to a Department of Revenue issue.",
    audience:["Oregon Taxpayers"],
    counties:["Jackson","Josephine"],
    cost:"Free government assistance",
    phone:"503-945-8700",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/dor/pages/taxpayer-advocate.aspx",
    labels:["TAXES","HARDSHIP","STATE HELP"],
    keywords:["tax debt","Oregon taxes","hardship","taxpayer advocate"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-money-search",
    category:"money",
    name:"211info — Money, Benefits & Financial Assistance Search",
    helps:"Search Oregon’s larger live resource directory for cash assistance, benefits, tax help, budgeting, debt help, emergency financial assistance and other programs not yet individually listed in the Flourish hub.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["211","LIVE DIRECTORY","CATCH-ALL"],
    keywords:["211","money","cash","credit","debt","benefits","financial assistance","tax"],
    lastVerified:"2026-08-30"
  }
];
