/* Flourish Anyway Community Resource Hub
   DOMESTIC VIOLENCE / SEXUAL ASSAULT / TRAFFICKING / PERSONAL SAFETY
   Jackson + Josephine Counties, Oregon
   Built from September 2026 verified research.
   Upload as: safety-data.js

   IMPORTANT:
   - This file is RESOURCE DATA ONLY.
   - Do not replace category.html, search.html, resource-loader.js, index.html,
     life-plans.html, or life-plans-data.js with this build.
   - The site will need one later master architecture update before a new
     "safety" category can display if the current loader/index does not yet
     register FLOURISH_SAFETY_DATA.
   - Medical/evidence time windows are intentionally not collapsed into one
     generic deadline.
*/

window.FLOURISH_SAFETY_DATA = [
  {
    id:"community-works-survivor-services",
    category:"safety",
    section:"Start Here — Confidential Local Advocates",
    name:"Community Works — Jackson County 24/7 HelpLine",
    helps:"Free, confidential support for domestic violence, sexual assault, stalking and trafficking. Advocates can help with immediate safety planning, shelter, housing, court support, medical advocacy and longer-term stabilization.",
    audience:["Survivors", "Adults", "Youth", "Families"],
    counties:["Jackson"],
    cost:"Free and confidential",
    phone:"24/7 HelpLine: 541-779-4357 | Office: 541-779-2393",
    address:"2594 E Barnett Road, Suite C, Medford",
    website:"https://www.community-works.org/",
    sourceName:"Community Works",
    labels:["24/7", "DOMESTIC VIOLENCE", "SEXUAL ASSAULT", "STALKING", "TRAFFICKING"],
    keywords:["abuse", "DV", "rape", "stalking", "trafficking", "safe shelter", "safety plan", "Jackson County"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"wcst-josephine-survivors",
    category:"safety",
    section:"Start Here — Confidential Local Advocates",
    name:"Women’s Crisis Support Team — Josephine County",
    helps:"Free, confidential domestic-violence and sexual-assault advocacy for Josephine County, including 24-hour crisis support, safety planning, shelter and court/community navigation.",
    audience:["Survivors", "Adults", "Youth", "Families"],
    counties:["Josephine"],
    cost:"Free and confidential",
    phone:"24/7 Crisis Line: 541-479-9349 | Office: 541-476-3877",
    address:"612 NW 5th Street, Grants Pass",
    website:"https://www.wcstjoco.org/",
    sourceName:"Women’s Crisis Support Team",
    labels:["24/7", "DOMESTIC VIOLENCE", "SEXUAL ASSAULT", "JOSEPHINE"],
    keywords:["WCST", "Grants Pass", "abuse", "rape", "shelter", "court advocate", "safety planning"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"ivsha-cave-junction-survivors",
    category:"safety",
    section:"Start Here — Confidential Local Advocates",
    name:"Illinois Valley Safe House Alliance — Cave Junction",
    helps:"In-person survivor advocacy in Cave Junction for domestic violence, dating violence, sexual assault and stalking. Services include safety planning, protection-order help, court/medical accompaniment, emergency shelter, transportation and other safety needs.",
    audience:["Survivors", "Rural Residents", "Adults", "Youth", "Families"],
    counties:["Josephine"],
    cost:"Free and confidential",
    phone:"Office: 541-592-2515 | 24/7 Crisis: 541-415-9367 | 24/7 Rape Crisis: 541-415-6545",
    address:"103 S Kerby Avenue, Cave Junction",
    website:"https://www.ivsha.org/",
    sourceName:"Illinois Valley Safe House Alliance",
    labels:["24/7", "CAVE JUNCTION", "RURAL", "DOMESTIC VIOLENCE", "SEXUAL ASSAULT"],
    keywords:["Illinois Valley", "IVSHA", "Cave Junction", "rape crisis", "safe house", "restraining order"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"call-to-safety-oregon",
    category:"safety",
    section:"Start Here — Confidential Local Advocates",
    name:"Call to Safety — Oregon Statewide Crisis Line",
    helps:"Statewide confidential domestic- and sexual-violence crisis support. Useful when a local program is unavailable, when someone wants another confidential option, or when help is needed outside normal office hours.",
    audience:["Survivors", "Friends", "Family"],
    counties:["Jackson", "Josephine"],
    cost:"Free and confidential",
    phone:"888-235-5333",
    address:"Oregon statewide",
    website:"https://calltosafety.org/",
    sourceName:"Call to Safety",
    labels:["STATEWIDE", "CRISIS LINE", "DOMESTIC VIOLENCE", "SEXUAL VIOLENCE"],
    keywords:["statewide crisis line", "DV hotline", "sexual assault hotline", "advocate"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-sart",
    category:"safety",
    section:"Sexual Assault & Strangulation Medical Care",
    name:"Jackson County SART — Sexual Assault Response Team",
    helps:"Jackson County sexual-assault medical and advocacy pathway. Current local guidance distinguishes immediate care available within seven days from the local SAFE evidence-collection window described on the SART page. Use the current SART page or an advocate for exact timing.",
    audience:["Sexual Assault Survivors", "Teens", "Adults"],
    counties:["Jackson"],
    cost:"See current program; advocacy is free",
    address:"Jackson County",
    website:"https://jacksoncountyor.gov/departments/district_attorney/victim_assistance_program/sexual_assault_response_team.php",
    sourceName:"Jackson County SART",
    labels:["SEXUAL ASSAULT", "FORENSIC EXAM", "MEDICAL CARE", "TIME-SENSITIVE"],
    keywords:["SART", "SAFE kit", "rape kit", "sexual assault exam", "84 hours", "7 days", "evidence"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-save-fund",
    category:"safety",
    section:"Sexual Assault & Strangulation Medical Care",
    name:"Oregon SAVE Fund — Sexual Assault & Strangulation Exams",
    helps:"Oregon’s Sexual Assault Victims’ Emergency Medical Response Fund can pay for qualifying sexual-assault medical examinations within the state program’s current time window and also covers qualifying strangulation/SKIT examinations. This is a payment program, not the same thing as a local evidence-collection deadline.",
    audience:["Sexual Assault Survivors", "Strangulation Survivors"],
    counties:["Jackson", "Josephine"],
    cost:"Qualifying exams paid through the state fund",
    phone:"503-378-6254",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/victims-services/sexual-assault-victims-emergency-medical-response-fund/",
    sourceName:"Oregon Department of Justice",
    labels:["SAVE FUND", "SEXUAL ASSAULT EXAM", "STRANGULATION", "SKIT"],
    keywords:["SAVE Fund", "sexual assault exam", "strangulation exam", "SKIT", "medical bill", "forensic exam"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jackson-protective-orders",
    category:"safety",
    section:"Protection Orders & Court Safety",
    name:"Jackson County Circuit Court — Protective Orders",
    helps:"Official Jackson County information and forms for civil protection orders. Use the current court page for filing instructions and timing; a confidential advocate can also help with paperwork and court preparation.",
    audience:["Survivors", "Self-Represented People"],
    counties:["Jackson"],
    cost:"Court forms are free",
    phone:"541-776-7171",
    address:"100 S Oakdale Avenue, Medford",
    website:"https://www.courts.oregon.gov/courts/jackson/help/Pages/protective-orders.aspx",
    sourceName:"Oregon Judicial Department",
    labels:["PROTECTIVE ORDER", "RESTRAINING ORDER", "JACKSON"],
    keywords:["FAPA", "stalking order", "sexual abuse order", "elder abuse order", "protective order"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-protective-orders",
    category:"safety",
    section:"Protection Orders & Court Safety",
    name:"Josephine County Circuit Court — Protective Orders",
    helps:"Official Josephine County filing instructions for stalking, domestic-violence, sexual-abuse and elder-abuse protective orders. Josephine currently uses different filing/hearing timing for stalking orders than for most other protective orders, so check the current page before going.",
    audience:["Survivors", "Self-Represented People"],
    counties:["Josephine"],
    cost:"Court forms are free",
    phone:"541-476-2309",
    address:"500 NW 6th Street, Grants Pass",
    website:"https://www.courts.oregon.gov/courts/josephine/help/Pages/protective-orders.aspx",
    sourceName:"Oregon Judicial Department",
    labels:["PROTECTIVE ORDER", "RESTRAINING ORDER", "JOSEPHINE", "TIME-SENSITIVE"],
    keywords:["FAPA", "stalking order", "8:30", "2:00", "sexual abuse order", "elder abuse"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-hope-card",
    category:"safety",
    section:"Protection Orders & Court Safety",
    name:"Oregon Hope Card Program",
    helps:"Free wallet-sized card for people with an active qualifying civil protection order. It shows essential order information and can be useful with law enforcement, employers, landlords and schools.",
    audience:["People with Active Civil Protection Orders"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"503-986-6768",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/victims-services/hope-card-program/",
    sourceName:"Oregon Department of Justice",
    labels:["HOPE CARD", "PROTECTION ORDER", "FREE"],
    keywords:["Hope Card", "restraining order card", "protective order wallet card", "school", "landlord", "employer"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-visor",
    category:"safety",
    section:"Release Notifications & Ongoing Safety",
    name:"Oregon VISOR — Custody & Release Notifications",
    helps:"Free opt-in notifications about custody-status changes involving people in Oregon custody, including transfers, releases and other changes. Registration is confidential from the person in custody.",
    audience:["Crime Victims", "Survivors", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/doc/victim-services/Pages/vine.aspx",
    sourceName:"Oregon Department of Corrections",
    labels:["VISOR", "RELEASE NOTIFICATION", "CUSTODY STATUS"],
    keywords:["tell me when released", "release alert", "custody notification", "jail release", "prison release", "VISOR"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-parole-victim-notification",
    category:"safety",
    section:"Release Notifications & Ongoing Safety",
    name:"Oregon Board of Parole — Victim Notification",
    helps:"Separate opt-in notification program for parole-board events and certain supervision or sex-offender matters. VISOR and Board of Parole notification are separate registrations, so someone may need both.",
    audience:["Crime Victims", "Survivors", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/boppps/Pages/Victim-Services.aspx",
    sourceName:"Oregon Board of Parole",
    labels:["PAROLE", "VICTIM NOTIFICATION", "SEPARATE FROM VISOR"],
    keywords:["parole notification", "release", "post prison supervision", "sex offender", "victim alert"],
    lastVerified:"2026-09-04"
  },
  {
    id:"community-works-shelter",
    category:"safety",
    section:"Emergency Shelter & Longer-Term Safety",
    name:"Community Works — Dunn House Emergency Shelter",
    helps:"Confidential emergency shelter for adults and children experiencing violence-related crisis or displacement. Advocates also help with safety, housing, court, health-care and benefits navigation.",
    audience:["Survivors", "Parents", "Children"],
    counties:["Jackson"],
    cost:"Free and confidential",
    phone:"541-779-4357",
    address:"Confidential location; call HelpLine",
    website:"https://www.community-works.org/shelter/",
    sourceName:"Community Works",
    labels:["EMERGENCY SHELTER", "SURVIVORS", "CHILDREN"],
    keywords:["Dunn House", "safe shelter", "domestic violence shelter", "emergency housing"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"community-works-housing",
    category:"safety",
    section:"Emergency Shelter & Longer-Term Safety",
    name:"Community Works — Survivor Housing",
    helps:"Housing advocacy and longer-term survivor housing pathways, including Mary’s Haven transitional housing for qualifying survivors and their children.",
    audience:["Survivors", "Parents", "Children"],
    counties:["Jackson"],
    cost:"Free/confidential; eligibility varies",
    phone:"541-779-4357",
    address:"Jackson County",
    website:"https://www.community-works.org/housing/",
    sourceName:"Community Works",
    labels:["TRANSITIONAL HOUSING", "SURVIVOR HOUSING", "JACKSON"],
    keywords:["Mary's Haven", "transitional housing", "housing advocate", "domestic violence housing"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"oregon-law-help-survivor-housing",
    category:"safety",
    section:"Emergency Shelter & Longer-Term Safety",
    name:"Oregon Law Help — Housing Protections for Survivors",
    helps:"Current Oregon renter-rights guide covering early lease termination, lock changes, options involving an abusive co-tenant, and protections against being denied housing or evicted simply because someone was victimized.",
    audience:["Renters", "Survivors"],
    counties:["Jackson", "Josephine"],
    cost:"Free legal information",
    address:"Oregon statewide",
    website:"https://oregonlawhelp.org/topics/housing/rental-housing/housing-protections-victims-domestic-violence-and-certain-other-crimes",
    sourceName:"Oregon Law Help",
    labels:["HOUSING RIGHTS", "LOCK CHANGE", "LEASE TERMINATION"],
    keywords:["break lease", "change locks", "abusive roommate", "eviction survivor", "housing protection"],
    lastVerified:"2026-09-04"
  },
  {
    id:"paid-leave-safe-leave",
    category:"safety",
    section:"Work, Money & Identity Safety",
    name:"Paid Leave Oregon — Safe Leave",
    helps:"Paid leave for qualifying survivors, and qualifying parents, affected by sexual assault, domestic violence, harassment, bias crimes or stalking. Current rules explain documentation, job protection and how to apply.",
    audience:["Workers", "Parents", "Survivors"],
    counties:["Jackson", "Josephine"],
    cost:"State benefit; eligibility rules apply",
    phone:"833-854-0166",
    address:"Oregon statewide",
    website:"https://paidleave.oregon.gov/employees/applying-for-safe-leave.html",
    sourceName:"Paid Leave Oregon",
    labels:["SAFE LEAVE", "PAID LEAVE", "WORK"],
    keywords:["time off work", "safe leave", "DV work leave", "stalking", "sexual assault", "parent"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-address-confidentiality",
    category:"safety",
    section:"Work, Money & Identity Safety",
    name:"Oregon Address Confidentiality Program",
    helps:"Free substitute-address and mail-forwarding program for eligible survivors of domestic violence, sexual assault, stalking, human trafficking, bias crimes and bias incidents. Application is completed with a certified application assistant.",
    audience:["Survivors", "People Relocating for Safety"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"503-373-1323",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/victims-services/address-confidentiality-program-acp/",
    sourceName:"Oregon Department of Justice",
    labels:["ADDRESS CONFIDENTIALITY", "MAIL FORWARDING", "IDENTITY SAFETY"],
    keywords:["hide address", "ACP", "confidential address", "school address", "driver license", "trafficking"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-crime-victims-compensation",
    category:"safety",
    section:"Work, Money & Identity Safety",
    name:"Oregon Crime Victims’ Compensation",
    helps:"May help eligible victims of violent crime with certain crime-related medical, counseling, lost-earnings, funeral, rehabilitation and other qualifying costs. It is not immediate cash assistance and does not pay relocation costs.",
    audience:["Crime Victims", "Survivors", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free to apply; eligibility applies",
    phone:"503-378-5348",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/crime-victim-compensation/compensation-for-victims-of-crime/",
    sourceName:"Oregon Department of Justice",
    labels:["CRIME VICTIMS", "COMPENSATION", "MEDICAL", "COUNSELING"],
    keywords:["crime victim compensation", "lost wages", "counseling", "medical bill", "violent crime"],
    lastVerified:"2026-09-04"
  },
  {
    id:"cac-jackson-county",
    category:"safety",
    section:"Children, Teens & Family Safety",
    name:"Children’s Advocacy Center of Jackson County",
    helps:"Child-abuse response center providing forensic interviews, child-abuse advocacy, medical evaluation/treatment and therapeutic intervention in a child-focused setting.",
    audience:["Children", "Teens", "Parents", "Caregivers"],
    counties:["Jackson"],
    cost:"Victim-service program; contact center",
    phone:"541-734-KIDS (5437)",
    address:"816 W 10th Street, Medford",
    website:"https://cacjc.org/",
    sourceName:"Children’s Advocacy Center of Jackson County",
    labels:["CHILD ABUSE", "FORENSIC INTERVIEW", "MEDICAL", "THERAPY"],
    keywords:["child sexual abuse", "forensic interview", "child advocacy center", "CAC", "abuse exam"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-child-abuse-report",
    category:"safety",
    section:"Children, Teens & Family Safety",
    name:"Oregon Child Abuse Hotline",
    helps:"Report suspected child abuse or neglect anywhere in Oregon. You do not need proof to make a report. Call 911 when a child is in immediate danger.",
    audience:["Children", "Families", "Community", "Mandatory Reporters"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"855-503-SAFE (7233)",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/report-abuse/Pages/default.aspx",
    sourceName:"Oregon Department of Human Services",
    labels:["CHILD ABUSE", "REPORT ABUSE", "SAFE LINE"],
    keywords:["child abuse hotline", "neglect", "mandatory reporter", "855-503-SAFE"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-adult-abuse-report",
    category:"safety",
    section:"Older & Vulnerable Adults",
    name:"Oregon SAFEline — Older & Vulnerable Adult Abuse",
    helps:"Report suspected physical, sexual or emotional abuse, financial exploitation, neglect or other abuse involving adults 65+ or qualifying adults with developmental, physical or mental-health disabilities.",
    audience:["Older Adults", "People with Disabilities", "Caregivers", "Community"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"855-503-SAFE (7233)",
    address:"Oregon statewide",
    website:"https://www.oregon.gov/odhs/aging-disability-services/Pages/prevent-adult-abuse.aspx",
    sourceName:"Oregon Department of Human Services",
    labels:["ELDER ABUSE", "FINANCIAL EXPLOITATION", "DISABILITY", "REPORT ABUSE"],
    keywords:["elder abuse", "caregiver abuse", "financial exploitation", "neglect", "sexual abuse", "vulnerable adult"],
    lastVerified:"2026-09-04"
  },
  {
    id:"sou-sexual-violence-response",
    category:"safety",
    section:"College & Campus Survivors",
    name:"Southern Oregon University — Sexual Violence Response",
    helps:"SOU resources for students affected by sexual assault, dating/domestic violence, stalking and related harm, including confidential advising, reporting options and information about free sexual-assault forensic exams.",
    audience:["SOU Students", "College Students"],
    counties:["Jackson"],
    cost:"Campus support; many services are free",
    phone:"541-552-6221",
    address:"Southern Oregon University, Ashland",
    website:"https://dos.sou.edu/safe/",
    sourceName:"Southern Oregon University",
    labels:["SOU", "CAMPUS", "TITLE IX", "CONFIDENTIAL ADVISOR"],
    keywords:["SOU sexual assault", "college survivor", "dating violence", "stalking", "forensic exam"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rcc-title-ix",
    category:"safety",
    section:"College & Campus Survivors",
    name:"Rogue Community College — Title IX & Sexual Misconduct Resources",
    helps:"RCC’s current Title IX resource for sexual assault, dating violence, domestic violence and stalking, including reporting and campus support information.",
    audience:["RCC Students", "College Students", "Employees"],
    counties:["Jackson", "Josephine"],
    cost:"Campus support",
    phone:"Title IX: 541-956-7124",
    address:"Rogue Community College",
    website:"https://www.roguecc.edu/titleIX/",
    sourceName:"Rogue Community College",
    labels:["RCC", "TITLE IX", "CAMPUS", "SEXUAL ASSAULT"],
    keywords:["RCC Title IX", "college sexual assault", "dating violence", "domestic violence", "stalking"],
    lastVerified:"2026-09-04"
  },
  {
    id:"nnedv-safety-net",
    category:"safety",
    section:"Technology, Stalking & Digital Safety",
    name:"NNEDV Safety Net Project — Technology Safety for Survivors",
    helps:"Survivor-specific guidance for spyware/stalkerware, account monitoring, location tracking, connected devices, online stalking, evidence preservation and technology safety planning. Changing settings can sometimes alert an abusive person or erase evidence, so safety-plan before making major changes.",
    audience:["Survivors", "Stalking Victims", "Advocates"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"National resource",
    website:"https://www.techsafety.org/resources-survivors",
    sourceName:"NNEDV Safety Net Project",
    labels:["SPYWARE", "LOCATION TRACKING", "ONLINE STALKING", "TECH SAFETY"],
    keywords:["stalkerware", "AirTag", "location tracker", "phone monitoring", "account hacked", "digital evidence", "spyware"],
    lastVerified:"2026-09-04"
  },
  {
    id:"the-hotline-pet-safety",
    category:"safety",
    section:"Pets & Leaving Safely",
    name:"National Domestic Violence Hotline — Pet Safety Planning",
    helps:"Safety-planning information for survivors who are worried about pets, pet threats or how to leave safely with animals. Use with a local advocate to explore local shelter, foster or temporary-care options.",
    audience:["Survivors with Pets", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    phone:"800-799-SAFE (7233)",
    address:"National resource",
    website:"https://www.thehotline.org/plan-for-safety/pet-safety-during-domestic-violence/",
    sourceName:"National Domestic Violence Hotline",
    labels:["PETS", "SAFETY PLAN", "DOMESTIC VIOLENCE"],
    keywords:["can't leave because of pets", "pet threat", "dog", "cat", "pet foster", "animal safety"],
    lastVerified:"2026-09-04"
  },
  {
    id:"national-human-trafficking-hotline",
    category:"safety",
    section:"Human Trafficking & Exploitation",
    name:"National Human Trafficking Hotline",
    helps:"Confidential help for people experiencing or concerned about sex trafficking or labor trafficking. The hotline can help identify options and connect callers with local services; call 911 for immediate danger.",
    audience:["Trafficking Survivors", "Workers", "Youth", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"888-373-7888 | Text 233733",
    address:"National resource",
    website:"https://humantraffickinghotline.org/en",
    sourceName:"National Human Trafficking Hotline",
    labels:["TRAFFICKING", "LABOR EXPLOITATION", "SEX TRAFFICKING"],
    keywords:["human trafficking", "forced labor", "sex trafficking", "exploitation", "trafficker"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"uscis-trafficking-immigration",
    category:"safety",
    section:"Human Trafficking & Exploitation",
    name:"USCIS — Immigration Options for Trafficking & Crime Victims",
    helps:"Federal information about possible immigration protections for qualifying victims, including T nonimmigrant status for certain trafficking victims and U nonimmigrant status for certain victims of qualifying criminal activity. Eligibility requires legal screening; the Hub should not assume someone qualifies.",
    audience:["Immigrant Survivors", "Trafficking Survivors", "Crime Victims"],
    counties:["Jackson", "Josephine"],
    cost:"Government information; legal help recommended",
    address:"Federal",
    website:"https://www.uscis.gov/humanitarian/victims-of-human-trafficking-and-other-crimes",
    sourceName:"U.S. Citizenship and Immigration Services",
    labels:["IMMIGRATION", "T VISA", "U VISA", "TRAFFICKING"],
    keywords:["T visa", "T status", "U visa", "U status", "immigrant victim", "trafficking immigration"],
    lastVerified:"2026-09-04"
  },
  {
    id:"cnpls-survivor-legal",
    category:"safety",
    section:"Legal Aid & Survivor Rights",
    name:"Center for NonProfit Legal Services — Jackson County",
    helps:"Civil legal aid for eligible Jackson County residents. Survivor-related issues can overlap with protective orders, family law, housing, benefits, immigration, employment and life-planning needs.",
    audience:["Low-Income Survivors", "Families"],
    counties:["Jackson"],
    cost:"Free or eligibility-based",
    phone:"541-779-7292",
    address:"225 W Main Street, Medford",
    website:"https://cnpls.org/",
    sourceName:"Center for NonProfit Legal Services",
    labels:["LEGAL AID", "JACKSON", "SURVIVOR RIGHTS"],
    keywords:["survivor lawyer", "restraining order", "custody abuse", "housing legal aid", "immigration legal aid"],
    lastVerified:"2026-09-04"
  },
  {
    id:"olc-survivor-legal-josephine",
    category:"safety",
    section:"Legal Aid & Survivor Rights",
    name:"Oregon Law Center — Grants Pass Regional Office",
    helps:"Civil legal aid for eligible low-income Josephine County residents. The office accepts calls about civil legal problems including family, housing, disability, discrimination and OHP-related issues.",
    audience:["Low-Income Survivors", "Families"],
    counties:["Josephine"],
    cost:"Free for eligible clients",
    phone:"541-476-1058",
    address:"873 NE 7th Street, Suite A, Grants Pass",
    website:"https://oregonlawcenter.org/how-to-get-help/olc-offices/grants-pass/",
    sourceName:"Oregon Law Center",
    labels:["LEGAL AID", "JOSEPHINE", "SURVIVOR RIGHTS"],
    keywords:["survivor lawyer", "restraining order", "custody abuse", "housing legal aid", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-doj-victim-rights",
    category:"safety",
    section:"Legal Aid & Survivor Rights",
    name:"Oregon DOJ — Crime Victim & Survivor Services",
    helps:"Statewide hub for crime-victim rights, compensation, county victim-assistance programs and other legal/support resources for people harmed by crime.",
    audience:["Crime Victims", "Survivors", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    phone:"971-673-1880",
    address:"Oregon statewide",
    website:"https://www.doj.state.or.us/crime-victims/",
    sourceName:"Oregon Department of Justice",
    labels:["VICTIM RIGHTS", "CRIME VICTIMS", "STATEWIDE"],
    keywords:["victim rights", "crime victim advocate", "compensation", "court rights", "victim services"],
    lastVerified:"2026-09-04"
  },
  {
    id:"211-survivor-safety",
    category:"safety",
    section:"Longer-Term Stability & Live Resource Search",
    name:"211info — Live Housing, Food & Basic-Needs Search",
    helps:"Use 211 for changing shelter, housing, rent, utility, food, transportation and other basic-needs resources that may affect a survivor’s ability to stay safe. Availability changes too quickly to hard-code.",
    audience:["Survivors", "Families", "Everyone"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    sourceName:"211info",
    labels:["LIVE DIRECTORY", "HOUSING", "BASIC NEEDS", "211"],
    keywords:["shelter bed", "rent", "utilities", "food", "transportation", "motel", "basic needs"],
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  }
];
