/* Flourish Anyway Community Resource Hub
   SENIOR & DISABILITY RESOURCES
   File name after upload: senior-data.js
   Jackson + Josephine Counties, Oregon
   Backbone: RVCOG/ADRC + official local/state/provider sources + 211info
   Last researched: 2026-08-30
*/

window.FLOURISH_SENIOR_DATA = [
  {
    id:"adrc-rogue-valley",
    category:"senior",
    name:"Aging & Disability Resource Connection — Rogue Valley",
    helps:"One-stop information, options counseling and referral for older adults, people with disabilities and family caregivers. Can help with long-term care, Medicaid/OHP, SNAP, caregiver support, housing options, safety and community services.",
    audience:["Seniors","Adults with Disabilities","Family Caregivers"],
    counties:["Jackson","Josephine"],
    cost:"Free information and assistance",
    phone:"541-618-7572",
    tollFree:"855-673-2372",
    address:"155 N 1st St, Central Point, OR 97502",
    website:"https://rvcog.org/home/sds-2/about-us-3/adrc/",
    labels:["ADRC","ONE-STOP HELP","CAREGIVERS","LONG-TERM CARE"],
    keywords:["senior help","disability help","caregiver","Medicaid","long term care","ADRC"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvcog-senior-disability-services",
    category:"senior",
    name:"RVCOG Senior & Disability Services",
    helps:"Regional Area Agency on Aging serving Jackson and Josephine Counties with supportive services, nutrition, caregiver support, elder rights, healthy aging and disability resources.",
    audience:["Seniors","Adults with Disabilities","Caregivers"],
    counties:["Jackson","Josephine"],
    cost:"Most information/referral services are free; program eligibility varies",
    phone:"541-664-6674",
    address:"155 N 1st St, Central Point, OR 97502",
    website:"https://rvcog.org/learn-more/",
    labels:["AREA AGENCY ON AGING","TWO COUNTIES","ADVOCACY"],
    keywords:["RVCOG","senior services","disability services","Area Agency on Aging","AAA"],
    lastVerified:"2026-08-30"
  },
  {
    id:"food-friends-jackson",
    category:"senior",
    name:"Food & Friends — Meals on Wheels, Jackson County",
    helps:"Hot nutritious meal delivery for eligible homebound seniors, plus senior dining sites for social meals in several Jackson County communities.",
    audience:["Seniors 60+","Homebound Adults","Spouses of Eligible Seniors"],
    counties:["Jackson"],
    cost:"Program supported through Older Americans Act funding and donations; call for current contribution guidance",
    eligibility:"Generally age 60+ and homebound due to illness, injury or disability; delivery needed for at least two weeks.",
    phone:"541-734-9505",
    address:"2860 State St, Medford, OR 97501",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/",
    labels:["MEALS ON WHEELS","HOMEBOUND","SENIOR MEALS"],
    keywords:["Meals on Wheels","senior food","home delivered meals","Medford","Jackson County"],
    lastVerified:"2026-08-30"
  },
  {
    id:"food-friends-josephine",
    category:"senior",
    name:"Food & Friends — Meals on Wheels, Josephine County",
    helps:"Home-delivered meals for eligible homebound seniors and senior dining opportunities in Grants Pass, Cave Junction, Merlin and other Josephine County communities.",
    audience:["Seniors 60+","Homebound Adults","Spouses of Eligible Seniors"],
    counties:["Josephine"],
    cost:"Program supported through Older Americans Act funding and donations; call for current contribution guidance",
    eligibility:"Generally age 60+ and homebound due to illness, injury or disability.",
    phone:"541-955-8839",
    address:"1150 NE 9th St, Grants Pass, OR 97526",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/",
    labels:["MEALS ON WHEELS","GRANTS PASS","SENIOR MEALS"],
    keywords:["Meals on Wheels","senior food","Grants Pass","Josephine County"],
    lastVerified:"2026-08-30"
  },
  {
    id:"food-friends-dining-sites",
    category:"senior",
    name:"Food & Friends — Senior Dining Sites",
    helps:"Hot weekday lunches and social connection at senior dining sites across Jackson and Josephine Counties.",
    audience:["Seniors 60+","Eligible Spouses","Some Adults with Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Call for current meal contribution guidance",
    phone:"541-734-9505",
    address:"Multiple locations in Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/food-friends-senior-dining-sites-meals-on-wheels-service-areas/",
    labels:["SOCIAL MEALS","SENIOR CENTERS","TWO COUNTIES"],
    keywords:["senior lunch","dining site","social meal","Medford","Grants Pass","Cave Junction"],
    lastVerified:"2026-08-30"
  },
  {
    id:"family-caregiver-support",
    category:"senior",
    name:"RVCOG — Family Caregiver Support",
    helps:"Classes, coaching, information and support for people caring for an older adult or family member with significant care needs.",
    audience:["Family Caregivers","Spouses","Adult Children"],
    counties:["Jackson","Josephine"],
    cost:"Free or low-cost depending on program",
    phone:"541-618-7572",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/about-us-3/adrc/",
    labels:["CAREGIVER SUPPORT","COACHING","CLASSES"],
    keywords:["caregiver","caregiver burnout","respite","family caregiver","support"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvcog-behavioral-health",
    category:"senior",
    name:"RVCOG — Behavioral Health for Seniors & Adults with Disabilities",
    helps:"Behavioral-health support and resource connection intended to improve quality of life for older adults and people with disabilities.",
    audience:["Seniors","Adults with Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Call ADRC for current service details",
    phone:"541-618-7572",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/about-us-3/adrc/",
    labels:["BEHAVIORAL HEALTH","SENIORS","DISABILITY"],
    keywords:["senior mental health","disabled adult mental health","behavioral health"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvcog-community-living",
    category:"senior",
    name:"RVCOG — Community Living & Long-Term Care Options",
    helps:"Helps older adults and people with disabilities understand in-home care, assisted living, residential care and other community-based long-term care options, including possible financial assistance.",
    audience:["Seniors","Adults with Disabilities","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free options counseling; care costs vary",
    phone:"541-618-7572",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/about-us-3/adrc/",
    labels:["LONG-TERM CARE","ASSISTED LIVING","IN-HOME CARE"],
    keywords:["assisted living","in home care","care facility","long term care","Medicaid"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvcog-safety-rights",
    category:"senior",
    name:"RVCOG — Safety, Rights & Elder Advocacy",
    helps:"Information and advocacy to help protect older adults and adults with disabilities from abuse, exploitation, neglect and other safety concerns.",
    audience:["Seniors","Adults with Disabilities","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free information and advocacy",
    phone:"541-618-7572",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/about-us-3/adrc/",
    labels:["ELDER RIGHTS","ABUSE PREVENTION","ADVOCACY"],
    keywords:["elder abuse","financial exploitation","neglect","rights","senior safety"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-apd",
    category:"senior",
    name:"Oregon Aging and People with Disabilities (APD)",
    helps:"State services for older adults and adults with physical disabilities, including Medicaid long-term care, in-home services and residential-care eligibility.",
    audience:["Seniors","Adults with Physical Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Eligibility-based",
    phone:"855-673-2372",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odhs/aging-disability-services/pages/default.aspx",
    labels:["MEDICAID LONG-TERM CARE","IN-HOME SERVICES","APD"],
    keywords:["APD","Medicaid long term care","in home caregiver","physical disability","senior"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-adult-protective-services",
    category:"senior",
    name:"Oregon Adult Protective Services",
    helps:"Report suspected abuse, neglect, self-neglect or financial exploitation of an older adult or adult with a disability.",
    audience:["Seniors","Adults with Disabilities","Community"],
    counties:["Jackson","Josephine"],
    cost:"Free reporting service",
    phone:"855-503-7233",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odhs/report-abuse/pages/default.aspx",
    labels:["ABUSE REPORTING","PROTECTIVE SERVICES","SAFETY"],
    keywords:["adult abuse","elder abuse","neglect","financial exploitation","APS"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hasl-grants-pass",
    category:"senior",
    name:"HASL Center for Independent Living — Grants Pass",
    helps:"Independent-living support for people with disabilities, including peer support, advocacy, skills training, information/referral and help navigating community resources.",
    audience:["Adults with Disabilities","Seniors","Families"],
    counties:["Josephine"],
    cost:"Many independent-living services are free",
    phone:"541-479-4275",
    address:"305 NE E St, Grants Pass, OR 97526",
    website:"https://www.grantspassoregon.gov/414/Health-Resources",
    labels:["DISABILITY","INDEPENDENT LIVING","PEER SUPPORT"],
    keywords:["HASL","disability help","independent living","peer support","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"hasl-medical-equipment",
    category:"senior",
    name:"HASL — Medical Equipment Assistance",
    helps:"Helps connect people with disabilities and mobility needs to durable medical equipment resources such as walkers, wheelchairs and related supports when available.",
    audience:["Adults with Disabilities","Seniors"],
    counties:["Josephine"],
    cost:"Availability and cost vary",
    phone:"541-479-4275",
    address:"305 NE E St, Grants Pass, OR 97526",
    website:"https://www.grantspassoregon.gov/414/Health-Resources",
    labels:["MEDICAL EQUIPMENT","MOBILITY","DISABILITY"],
    keywords:["wheelchair","walker","medical equipment","mobility aid","HASL"],
    lastVerified:"2026-08-30"
  },
  {
    id:"community-living-case-management",
    category:"senior",
    name:"Community Living Case Management — Developmental Disability Services",
    helps:"Case management and service coordination for eligible adults and children with intellectual or developmental disabilities in Josephine County.",
    audience:["Adults with I/DD","Children with I/DD","Families"],
    counties:["Josephine"],
    cost:"Eligibility-based public developmental-disability services",
    phone:"541-474-6072 ext 301",
    address:"1215 NE 7th St, Suite C, Grants Pass, OR 97526",
    website:"https://www.211info.org/",
    labels:["I/DD","CASE MANAGEMENT","JOSEPHINE"],
    keywords:["developmental disability","intellectual disability","case management","I/DD","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-dd-services",
    category:"senior",
    name:"Oregon Developmental Disabilities Services",
    helps:"Statewide information about supports for eligible people with intellectual and developmental disabilities, including case management, in-home and community services.",
    audience:["Adults with I/DD","Children with I/DD","Families"],
    counties:["Jackson","Josephine"],
    cost:"Eligibility-based",
    phone:"",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odhs/idd/pages/default.aspx",
    labels:["I/DD","STATE SERVICES","COMMUNITY SUPPORT"],
    keywords:["developmental disability","I/DD","case management","ODDS"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-vocational-rehab-disability",
    category:"senior",
    name:"Oregon Vocational Rehabilitation — Disability Employment Support",
    helps:"Helps eligible people with disabilities prepare for, obtain, keep or advance in employment through individualized vocational services.",
    audience:["Adults with Disabilities","Youth with Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Eligibility-based public service",
    phone:"",
    address:"Southern Oregon local offices",
    website:"https://www.oregon.gov/odhs/vr/pages/default.aspx",
    labels:["DISABILITY","EMPLOYMENT","VOCATIONAL REHAB"],
    keywords:["VR","vocational rehabilitation","disability job help","employment"],
    lastVerified:"2026-08-30"
  },
  {
    id:"disability-rights-oregon-senior",
    category:"senior",
    name:"Disability Rights Oregon",
    helps:"Legal advocacy for people with disabilities involving discrimination, abuse, access, education, employment, health care and other disability-rights issues.",
    audience:["People with Disabilities","Families","Caregivers"],
    counties:["Jackson","Josephine"],
    cost:"Free advocacy/legal services for accepted matters",
    phone:"503-243-2081",
    address:"Statewide Oregon",
    website:"https://www.droregon.org/",
    labels:["DISABILITY RIGHTS","LEGAL ADVOCACY","ACCESS"],
    keywords:["ADA","disability discrimination","rights","legal help","access"],
    lastVerified:"2026-08-30"
  },
  {
    id:"social-security-ssi-senior",
    category:"senior",
    name:"Social Security — SSI",
    helps:"Federal monthly cash assistance for qualifying people with limited income/resources who are disabled, blind or age 65+.",
    audience:["Seniors 65+","Adults with Disabilities","Blind Adults"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"800-772-1213",
    address:"Federal program",
    website:"https://www.ssa.gov/ssi",
    labels:["SSI","CASH BENEFIT","DISABILITY","65+"],
    keywords:["SSI","Social Security","disabled","senior income"],
    lastVerified:"2026-08-30"
  },
  {
    id:"social-security-ssdi-senior",
    category:"senior",
    name:"Social Security — SSDI",
    helps:"Federal disability benefits for qualifying workers with a sufficient Social Security work history.",
    audience:["Adults with Disabilities","Workers"],
    counties:["Jackson","Josephine"],
    cost:"Free to apply",
    phone:"800-772-1213",
    address:"Federal program",
    website:"https://www.ssa.gov/disability",
    labels:["SSDI","DISABILITY","INCOME"],
    keywords:["SSDI","disability income","Social Security"],
    lastVerified:"2026-08-30"
  },
  {
    id:"medicare-help-shiba",
    category:"senior",
    name:"Oregon SHIBA — Medicare Counseling",
    helps:"Free, unbiased Medicare counseling for people with Medicare and their families, including help understanding plans, enrollment, costs and benefits.",
    audience:["Medicare Beneficiaries","Seniors","People with Disabilities","Caregivers"],
    counties:["Jackson","Josephine"],
    cost:"Free",
    phone:"800-722-4134",
    address:"Statewide Oregon",
    website:"https://shiba.oregon.gov/",
    labels:["MEDICARE","FREE COUNSELING","INSURANCE"],
    keywords:["Medicare","SHIBA","Part D","Medicare Advantage","insurance help"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-money-management-senior",
    category:"senior",
    name:"Oregon Money Management Program",
    helps:"Volunteer-supported money-management help for eligible older adults and adults with disabilities who need help organizing bills and maintaining financial independence.",
    audience:["Seniors","Adults with Disabilities"],
    counties:["Jackson","Josephine"],
    cost:"Free to eligible participants",
    phone:"855-673-2372",
    address:"Oregon ADRC network",
    website:"https://www.adrcoforegon.org/",
    labels:["BILL PAYING","FINANCIAL SAFETY","SENIORS"],
    keywords:["bill paying","money management","senior finances","disability"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-valley-lift-senior",
    category:"senior",
    name:"RVTD Valley Lift — ADA Paratransit",
    helps:"Wheelchair-accessible origin-to-destination transportation for eligible people whose disability prevents use of regular RVTD fixed-route buses.",
    audience:["Adults with Disabilities","Seniors with Qualifying Disabilities"],
    counties:["Jackson"],
    cost:"Current fare $4 per ride",
    phone:"541-842-2080",
    address:"Jackson County service area",
    website:"https://www.rvtd.org/accessible-transportation/valley-lift/",
    labels:["PARATRANSIT","ADA","WHEELCHAIR"],
    keywords:["Valley Lift","paratransit","senior transportation","disabled ride"],
    lastVerified:"2026-08-30"
  },
  {
    id:"jct-dial-a-ride-senior",
    category:"senior",
    name:"Josephine Community Transit — Dial-A-Ride",
    helps:"Demand-response transportation for eligible seniors and people with disabilities in the Grants Pass area.",
    audience:["Seniors","Adults with Disabilities"],
    counties:["Josephine"],
    cost:"Call for current fare and eligibility",
    phone:"541-474-5452",
    address:"Grants Pass, OR",
    website:"https://www.grantspassoregon.gov/443/Transportation",
    labels:["DIAL-A-RIDE","SENIORS","DISABILITY"],
    keywords:["senior ride","Dial A Ride","disabled transportation","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-senior-disability-search",
    category:"senior",
    name:"211info — Senior & Disability Search",
    helps:"Search Oregon's larger live directory for in-home care, caregiver support, disability services, senior meals, transportation, medical equipment, legal help and other aging/disability resources not yet individually listed in the Flourish hub.",
    audience:["Seniors","Adults with Disabilities","Caregivers","Families"],
    counties:["Jackson","Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    labels:["211","LIVE DIRECTORY","CATCH-ALL"],
    keywords:["211","senior","disability","caregiver","in home care","medical equipment","aging"],
    lastVerified:"2026-08-30"
  }
];
