/* Flourish Anyway Community Resource Hub
   SENIORS & OLDER ADULTS — VERIFIED REBUILD
   File name after upload: senior-data.js
   Jackson + Josephine Counties, Oregon
   Rebuilt and link-audited: 2026-09-04
   Rule: one provider/resource per card unless the card is explicitly labeled DIRECTORY/OFFICIAL SEARCH.
*/

window.FLOURISH_SENIOR_DATA = [
  {
    id:"silver-pages-southern-oregon",
    category:"senior",
    section:"Start Here & Local Senior Navigation",
    name:"The Silver Pages — Jackson & Josephine Counties",
    helps:"Local senior resource directory covering health and medical care, housing, social services, activities, dining, businesses and other services used by older adults. Good starting point when you do not know which local organization to call.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free directory",
    phone:"541-779-4839",
    address:"Jackson + Josephine Counties",
    website:"https://sosilverpages.com/",
    labels:["LOCAL DIRECTORY", "START HERE", "SENIORS"],
    keywords:["Silver Pages", "senior directory", "older adults", "local services", "housing", "health", "activities"],
    lastVerified:"2026-09-04"
  },
  {
    id:"adrc-rogue-valley",
    category:"senior",
    section:"Start Here & Local Senior Navigation",
    name:"Aging & Disability Resource Connection — Rogue Valley",
    helps:"One-stop information, options counseling and referrals for older adults, people with disabilities and family caregivers. Strong first call for long-term care, staying at home, Medicaid services, caregiver support, housing choices and benefits navigation.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free information and options counseling",
    phone:"541-618-7572",
    tollFree:"855-673-2372",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/what-we-do/",
    labels:["ADRC", "START HERE", "LONG-TERM CARE", "CAREGIVERS"],
    keywords:["ADRC", "aging", "senior help", "caregiver", "disability", "long term care", "options counseling"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rvcog-senior-disability",
    category:"senior",
    section:"Start Here & Local Senior Navigation",
    name:"RVCOG Senior & Disability Services",
    helps:"Area Agency on Aging for Jackson and Josephine Counties. Coordinates aging and disability services, advocacy, nutrition, caregiver supports and links with Medicaid long-term-care programs.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Program eligibility varies",
    phone:"541-664-6674",
    address:"Central Point",
    website:"https://rvcog.org/what-we-do/",
    labels:["AREA AGENCY ON AGING", "TWO COUNTIES"],
    keywords:["RVCOG", "AAA", "Senior Disability Services", "aging services", "advocacy"],
    lastVerified:"2026-09-04"
  },
  {
    id:"food-friends-jackson",
    category:"senior",
    section:"Food & Meals on Wheels",
    name:"Food & Friends — Jackson County Meals on Wheels",
    helps:"Home-delivered meals for eligible older adults and senior dining options in Jackson County. Call the Jackson County office for home-delivery eligibility and current service details.",
    audience:["Older Adults", "Homebound Adults"],
    counties:["Jackson"],
    cost:"Older Americans Act program; contribution guidance varies",
    phone:"541-734-9505",
    address:"Jackson County",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/",
    labels:["MEALS ON WHEELS", "FOOD", "HOME DELIVERY"],
    keywords:["Meals on Wheels", "Food and Friends", "senior meals", "homebound", "Jackson County"],
    lastVerified:"2026-09-04"
  },
  {
    id:"food-friends-josephine",
    category:"senior",
    section:"Food & Meals on Wheels",
    name:"Food & Friends — Josephine County Meals on Wheels",
    helps:"Home-delivered meals for eligible older adults in Grants Pass and surrounding Josephine County communities, with local dining sites and rural delivery areas.",
    audience:["Older Adults", "Homebound Adults"],
    counties:["Josephine"],
    cost:"Older Americans Act program; contribution guidance varies",
    phone:"541-955-8839",
    address:"Josephine County",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/",
    labels:["MEALS ON WHEELS", "FOOD", "HOME DELIVERY"],
    keywords:["Meals on Wheels", "Food and Friends", "senior meals", "Grants Pass", "Cave Junction", "Merlin"],
    lastVerified:"2026-09-04"
  },
  {
    id:"food-friends-dining-sites",
    category:"senior",
    section:"Food & Meals on Wheels",
    name:"Food & Friends — Senior Dining Sites & Service Areas",
    helps:"Official current list of senior dining sites and Meals on Wheels service areas across Jackson and Josephine Counties, including rural communities.",
    audience:["Older Adults", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Call for eligibility and contribution guidance",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/home/sds-2/food-friends-meals-on-wheels/food-friends-meal-services-2/food-friends-senior-dining-sites-meals-on-wheels-service-areas/",
    labels:["OFFICIAL LIST", "DINING SITES", "RURAL"],
    keywords:["senior dining", "meal sites", "Cave Junction", "Merlin", "Rogue River", "Ashland", "Jacksonville", "Meals on Wheels"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-senior-resource-center",
    category:"senior",
    section:"Start Here & Local Senior Navigation",
    name:"Josephine County Senior Resource Center",
    helps:"One-stop senior resource location in Grants Pass. The center brings together senior activities and local senior-service partners, including Club Sixty and Food & Friends services.",
    audience:["Older Adults", "Caregivers", "Families"],
    counties:["Josephine"],
    cost:"Many activities/resources are free; partner programs vary",
    phone:"541-660-2591",
    address:"1150 NE 9th Street, Grants Pass",
    website:"https://www.clubsixty.org/",
    labels:["SENIOR HUB", "GRANTS PASS", "START HERE"],
    keywords:["Josephine County Senior Resource Center", "senior center", "Grants Pass", "older adults"],
    lastVerified:"2026-09-04"
  },
  {
    id:"club-sixty",
    category:"senior",
    section:"Senior Centers, Activities & Connection",
    name:"Club Sixty — Grants Pass",
    helps:"Free senior activities and connection at the Josephine County Senior Resource Center. Offers social activities, workshops, lunch opportunities, vitals checks and other programs for older adults.",
    audience:["Older Adults"],
    counties:["Josephine"],
    cost:"Free membership",
    phone:"541-660-2591",
    address:"1150 NE 9th Street, Grants Pass",
    website:"https://www.clubsixty.org/",
    labels:["ACTIVITIES", "SOCIAL CONNECTION", "FREE"],
    keywords:["Club Sixty", "bingo", "senior activities", "loneliness", "social", "Grants Pass"],
    lastVerified:"2026-09-04"
  },
  {
    id:"team-senior-referral",
    category:"senior",
    section:"Help Choosing Housing & Care",
    name:"Team Senior Referral Services",
    helps:"Local Southern Oregon senior-living guidance. Helps families compare care settings, research facilities and licensing issues, work through hospital or nursing-home discharge questions and identify housing options. The service is free to seniors and families.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free to seniors and families",
    phone:"541-295-8230",
    address:"Southern Oregon",
    website:"https://www.teamsenior.org/",
    labels:["LOCAL GUIDANCE", "HOUSING", "CARE PLACEMENT"],
    keywords:["Team Senior", "senior placement", "assisted living help", "memory care help", "facility research", "discharge"],
    lastVerified:"2026-09-04"
  },
  {
    id:"senior-one-source",
    category:"senior",
    section:"Help Choosing Housing & Care",
    name:"Senior One Source — Medford & Grants Pass",
    helps:"Free senior-living guidance for Southern Oregon families looking at independent living, assisted living, memory care, adult/group homes, home care or skilled nursing and rehabilitation.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free guidance",
    phone:"541-414-4264",
    address:"Medford + Grants Pass service area",
    website:"https://senioronesource.net/location-map/",
    labels:["LOCAL GUIDANCE", "HOUSING", "CARE OPTIONS"],
    keywords:["Senior One Source", "placement", "Medford", "Grants Pass", "assisted living", "memory care", "nursing"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-ltc-search",
    category:"senior",
    section:"Licensed Care, Inspections & Complaints",
    name:"Oregon Licensed Long-Term Care — Official Provider Search",
    helps:"Official Oregon search for licensed assisted living, residential care, memory care, nursing facilities and adult foster homes. Shows open/closed status, inspections, substantiated violations, regulatory actions, Medicaid acceptance and other provider details. Updated every 24 hours.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free official search",
    address:"Oregon",
    website:"https://ltclicensing.oregon.gov/",
    labels:["OFFICIAL SEARCH", "INSPECTIONS", "VIOLATIONS", "MEDICAID"],
    keywords:["facility search", "licensed care", "assisted living", "memory care", "adult foster home", "nursing home", "inspection", "violation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-adult-foster-home",
    category:"senior",
    section:"Licensed Care, Inspections & Complaints",
    name:"Oregon Adult Foster Homes — Licensing & Search",
    helps:"Official information about adult foster homes, which are licensed single-family residences offering 24-hour care in a smaller homelike setting. Use the linked state resources to understand the care type and find licensed homes.",
    audience:["Older Adults", "Adults with Physical Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Information is free; care costs vary",
    address:"Oregon",
    website:"https://www.oregon.gov/odhs/licensing/adult-foster-homes/pages/default.aspx",
    labels:["ADULT FOSTER HOME", "OFFICIAL", "SMALL SETTING"],
    keywords:["adult foster home", "small care home", "24 hour care", "AFH", "licensed foster home"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-referral-registry",
    category:"senior",
    section:"Licensed Care, Inspections & Complaints",
    name:"Oregon Long-Term Care Referral Registry — Check a Placement Agency",
    helps:"Official state registry for long-term-care referral agents. Use it to check whether a placement/referral agency is registered before relying on it for assisted living, memory care, adult foster home or nursing-facility placement.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free official registry",
    address:"Oregon",
    website:"https://ltcr.oregon.gov/",
    labels:["OFFICIAL REGISTRY", "PLACEMENT AGENCIES", "CONSUMER CHECK"],
    keywords:["referral agent", "placement agency", "registered agent", "senior placement", "long term care referral"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-ltc-complaints",
    category:"senior",
    section:"Licensed Care, Inspections & Complaints",
    name:"Oregon Long-Term Care — Complaints, Licensing & Quality",
    helps:"Official Oregon page explaining facility licensing, inspections and how to make complaints about nursing facilities, assisted living/residential care and adult foster homes.",
    audience:["Residents", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"844-503-4773",
    address:"Oregon",
    website:"https://www.oregon.gov/odhs/aging-disability-services/Pages/long-term-care-quality.aspx",
    labels:["COMPLAINTS", "INSPECTIONS", "QUALITY", "OFFICIAL"],
    keywords:["complaint", "bad care", "facility problem", "inspection", "regulatory action", "nursing home complaint"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-apd",
    category:"senior",
    section:"Benefits, Medicare & Long-Term Care Help",
    name:"Oregon Aging and People with Disabilities (APD)",
    helps:"State aging and disability program connecting people to benefits, Medicaid long-term care, local offices, disability supports and other services for older adults and adults with disabilities.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Program eligibility varies",
    phone:"800-699-9075",
    address:"Oregon",
    website:"https://www.oregon.gov/odhs/agency/pages/apd.aspx",
    labels:["STATE PROGRAM", "BENEFITS", "LONG-TERM CARE"],
    keywords:["APD", "Medicaid long term care", "aging", "disability benefits", "Oregon benefits"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-opi-stay-home",
    category:"senior",
    section:"Staying Safely at Home",
    name:"Oregon Project Independence (OPI / OPI-M) — Help Staying at Home",
    helps:"State programs that may provide in-home help such as personal care, housekeeping, meals, transportation, assistive technology, home modifications and caregiver support. OPI and OPI-M have different payment and eligibility rules.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"OPI may use a sliding scale; OPI-M is free if eligible",
    address:"Oregon",
    website:"https://www.oregon.gov/odhs/aging-disability-services/pages/long-term-care.aspx",
    labels:["STAY AT HOME", "IN-HOME HELP", "OPI", "OPI-M"],
    keywords:["stay home", "in home care", "home modification", "housekeeping", "personal care", "OPI", "OPI-M"],
    lastVerified:"2026-09-04"
  },
  {
    id:"oregon-shiba",
    category:"senior",
    section:"Benefits, Medicare & Long-Term Care Help",
    name:"Oregon SHIBA — Free Medicare Counseling",
    helps:"Free, unbiased Medicare information and counseling from trained volunteers. Helps with Medicare choices, deadlines, Extra Help and programs that can reduce Medicare costs.",
    audience:["People with Medicare", "Older Adults", "Adults with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"800-722-4134",
    address:"Oregon",
    website:"https://shiba.oregon.gov/get-help/pages/shiba-help.aspx",
    labels:["MEDICARE", "FREE COUNSELING", "SHIBA"],
    keywords:["Medicare", "SHIBA", "Part D", "Medigap", "Medicare Advantage", "Extra Help"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ssa-ssi",
    category:"senior",
    section:"Money, Social Security & Disability Benefits",
    name:"Social Security — Supplemental Security Income (SSI)",
    helps:"Official SSI information and application guidance. SSI may provide monthly payments to people age 65+ or people with disabilities who have little or no income and resources.",
    audience:["Older Adults", "People with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Free official information",
    phone:"800-772-1213",
    address:"Federal",
    website:"https://www.ssa.gov/ssi",
    labels:["SSI", "INCOME", "SOCIAL SECURITY"],
    keywords:["SSI", "Social Security", "low income senior", "disability income", "65"],
    lastVerified:"2026-09-04"
  },
  {
    id:"ssa-disability",
    category:"senior",
    section:"Money, Social Security & Disability Benefits",
    name:"Social Security — Disability (SSDI)",
    helps:"Official Social Security Disability Insurance information, eligibility guidance, applications and information about returning to work while receiving disability benefits.",
    audience:["Adults with Disabilities"],
    counties:["Jackson", "Josephine"],
    cost:"Free official information",
    phone:"800-772-1213",
    address:"Federal",
    website:"https://www.ssa.gov/disability",
    labels:["SSDI", "DISABILITY", "SOCIAL SECURITY"],
    keywords:["SSDI", "disability benefits", "work history", "Social Security disability"],
    lastVerified:"2026-09-04"
  },
  {
    id:"disability-rights-oregon",
    category:"senior",
    section:"Legal Rights, Safety & Advocacy",
    name:"Disability Rights Oregon",
    helps:"Statewide disability-rights organization helping people with disability-related legal issues, including accessibility, housing, guardianship, financial protection, employment and service rights.",
    audience:["People with Disabilities", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Help depends on issue and program",
    address:"Oregon statewide",
    website:"https://www.droregon.org/",
    labels:["DISABILITY RIGHTS", "LEGAL", "ADVOCACY"],
    keywords:["disability rights", "ADA", "guardianship", "housing rights", "legal disability help"],
    lastVerified:"2026-09-04"
  },
  {
    id:"senior-211",
    category:"senior",
    section:"Start Here & Local Senior Navigation",
    name:"211info — Senior & Disability Resource Search",
    helps:"Oregon's larger live resource directory. Useful for finding additional in-home care, caregiver support, medical equipment, food, housing, transportation and disability resources not yet individually listed in the Hub.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    phone:"211",
    address:"Oregon",
    website:"https://www.211info.org/",
    labels:["LIVE DIRECTORY", "211", "CATCH-ALL"],
    keywords:["211", "senior resources", "disability resources", "medical equipment", "caregiver", "in home care"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rvtd-accessible",
    category:"senior",
    section:"Transportation",
    name:"RVTD Accessible Transportation — Valley Lift & TransLink",
    helps:"Accessible transportation information for Jackson County. RVTD oversees Valley Lift ADA paratransit and TransLink Medicaid non-emergency medical transportation.",
    audience:["Older Adults", "People with Disabilities", "OHP Members"],
    counties:["Jackson"],
    cost:"Program rules and fares vary",
    phone:"541-842-2080",
    address:"Jackson County",
    website:"https://www.rvtd.org/accessible-transportation/",
    labels:["PARATRANSIT", "MEDICAL RIDES", "ACCESSIBLE"],
    keywords:["Valley Lift", "TransLink", "senior ride", "wheelchair", "paratransit", "medical transportation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"josephine-transit",
    category:"senior",
    section:"Transportation",
    name:"Josephine Community Transit — Transportation",
    helps:"Official Grants Pass/Josephine County transportation information, including local transit options and accessible transportation information.",
    audience:["Older Adults", "People with Disabilities", "General Public"],
    counties:["Josephine"],
    cost:"Fares and eligibility vary",
    phone:"541-474-5452",
    address:"Josephine County",
    website:"https://www.grantspassoregon.gov/443/Transportation",
    labels:["TRANSIT", "JOSEPHINE", "RIDES"],
    keywords:["Josephine Community Transit", "Dial A Ride", "Grants Pass bus", "senior ride", "disabled transportation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"older-women-pathway",
    category:"senior",
    section:"Older Women — Health, Recovery & Connection",
    name:"Older Women — Health, Recovery & Connection",
    helps:"Hub pathway for older women looking for menopause or gynecology care, breast/cervical screening, bone health, pelvic/bladder care, recovery support, trauma help, grief, mental health or social connection.",
    audience:["Older Women"],
    counties:["Jackson", "Josephine"],
    cost:"Varies by service",
    address:"Flourish Anyway Hub",
    website:"search.html?q=older%20women%20health%20recovery%20connection",
    labels:["OLDER WOMEN", "HEALTH", "RECOVERY", "CONNECTION"],
    keywords:["older women", "menopause", "gynecology", "osteoporosis", "pelvic health", "recovery", "grief", "loneliness"],
    lastVerified:"2026-09-04"
  },
  {
    id:"talent-senior-apartments",
    category:"senior",
    section:"Affordable Senior Apartments",
    name:"Talent Senior Apartments — Affordable Senior Housing",
    helps:"ACCESS affordable housing project with one-bedroom units for seniors at or below 60% of area median income. ACCESS lists the community as actively leasing.",
    audience:["Income-Qualified Seniors"],
    counties:["Jackson"],
    cost:"Income-restricted; contact ACCESS for current rent and leasing",
    phone:"541-779-6691",
    address:"Talent",
    website:"https://accesshelps.org/rental-housing-projects/",
    labels:["AFFORDABLE HOUSING", "SENIOR APARTMENTS", "ACTIVELY LEASING"],
    keywords:["Talent Senior Apartments", "affordable senior apartment", "60 AMI", "one bedroom", "Talent"],
    lastVerified:"2026-09-04"
  },
  {
    id:"talent-senior-apartments-ii",
    category:"senior",
    section:"Affordable Senior Apartments",
    name:"Talent Senior Apartments II — Affordable Senior Housing",
    helps:"Newer ACCESS senior housing development with 21 one-bedroom units planned for seniors at or below 60% of area median income. Check ACCESS for current leasing/opening status.",
    audience:["Income-Qualified Seniors"],
    counties:["Jackson"],
    cost:"Income-restricted; contact ACCESS for current rent and status",
    phone:"541-779-6691",
    address:"Talent",
    website:"https://accesshelps.org/rental-housing-projects/",
    labels:["AFFORDABLE HOUSING", "SENIOR APARTMENTS", "NEWER HOUSING"],
    keywords:["Talent Senior Apartments II", "affordable senior apartment", "60 AMI", "Talent"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rogue-river-estates",
    category:"senior",
    section:"Affordable Senior Apartments",
    name:"Rogue River Estates — Affordable Senior/Disabled Apartments",
    helps:"Affordable apartment community in Medford serving older adults and people with disabilities. Current third-party housing data identifies 94 affordable units and Housing Authority of Jackson County waitlist management; verify current application status before relying on availability.",
    audience:["Older Adults", "People with Disabilities", "Income-Qualified Households"],
    counties:["Jackson"],
    cost:"Income-restricted; availability changes",
    address:"1395 Poplar Drive, Medford",
    website:"https://affordablehousinghub.org/housing/oregon/jackson-county/medford/rogue-river-estates-35370-lihtc",
    labels:["AFFORDABLE HOUSING", "SENIOR/DISABLED", "MEDFORD"],
    keywords:["Rogue River Estates", "affordable senior housing", "Medford", "Housing Authority"],
    lastVerified:"2026-09-04"
  },
  {
    id:"jasmine-park-i",
    category:"senior",
    section:"Affordable Senior Apartments",
    name:"Jasmine Park I — Low-Income Senior Apartments",
    helps:"43-unit low-income senior housing community in Grants Pass for residents age 62+ who can live independently. Includes one- and two-bedroom apartments and accessibility features in designated units.",
    audience:["Seniors 62+", "Income-Qualified Seniors"],
    counties:["Josephine"],
    cost:"Income-restricted; call for current waitlist and rent",
    phone:"541-471-9477",
    address:"501 NE Anderson Street, Grants Pass",
    website:"https://affordablehousinghub.org/housing/oregon/josephine-county/grants-pass/jasmine-park-i-35361-lihtc",
    labels:["AFFORDABLE HOUSING", "62+", "GRANTS PASS"],
    keywords:["Jasmine Park", "senior apartments", "low income housing", "Grants Pass", "62"],
    lastVerified:"2026-09-04"
  },
  {
    id:"twin-creeks",
    category:"senior",
    section:"Independent Senior Living",
    name:"Twin Creeks Retirement & Cottages — Independent Living",
    helps:"Independent retirement living in Central Point with apartments and cottages, dining, housekeeping, transportation, activities, fitness and other community amenities.",
    audience:["Older Adults", "Independent Seniors"],
    counties:["Jackson"],
    cost:"Private-pay retirement living; contact community for current pricing",
    phone:"541-664-8880",
    address:"888 Twin Creeks Crossing, Central Point",
    website:"https://twincreeksretirement.com/",
    labels:["INDEPENDENT LIVING", "CENTRAL POINT", "RETIREMENT"],
    keywords:["Twin Creeks", "independent living", "retirement", "Central Point", "cottages"],
    lastVerified:"2026-09-04"
  },
  {
    id:"cascades-grants-pass",
    category:"senior",
    section:"Assisted Living, Memory Care & Respite",
    name:"Cascades of Grants Pass — Independent, Assisted, Memory & Respite",
    helps:"Grants Pass senior living campus offering independent living, assisted living, memory care and short-term respite care. Useful when someone wants a campus that can support changing care needs.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Josephine"],
    cost:"Private-pay; care and apartment pricing vary",
    phone:"541-479-1284",
    address:"1357 Redwood Circle, Grants Pass",
    website:"https://www.cascadeliving.com/community/cascades-of-grants-pass/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "MEMORY CARE", "RESPITE"],
    keywords:["Cascades of Grants Pass", "assisted living", "memory care", "independent living", "respite"],
    lastVerified:"2026-09-04"
  },
  {
    id:"countryside-village",
    category:"senior",
    section:"Assisted Living, Memory Care & Respite",
    name:"Countryside Village — Grants Pass",
    helps:"Senior living community offering independent living, cottage living, assisted living and memory care in Grants Pass.",
    audience:["Older Adults", "Families"],
    counties:["Josephine"],
    cost:"Private-pay; contact community for pricing",
    phone:"541-291-5843",
    address:"1700 Kellenbeck Avenue, Grants Pass",
    website:"https://countrysidevillageretire.com/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "MEMORY CARE", "COTTAGES"],
    keywords:["Countryside Village", "Grants Pass", "assisted living", "memory care", "independent living"],
    lastVerified:"2026-09-04"
  },
  {
    id:"pioneer-village",
    category:"senior",
    section:"Independent & Assisted Living",
    name:"Pioneer Village — Jacksonville",
    helps:"Jacksonville senior community offering independent living and assisted living with individualized support when residents need help with daily activities.",
    audience:["Older Adults", "Families"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for pricing",
    phone:"541-702-1804",
    address:"805 N 5th Street, Jacksonville",
    website:"https://pioneervillageoregon.com/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "JACKSONVILLE"],
    keywords:["Pioneer Village", "Jacksonville", "assisted living", "independent living"],
    lastVerified:"2026-09-04"
  },
  {
    id:"bonaventure-medford",
    category:"senior",
    section:"Independent & Assisted Living",
    name:"Bonaventure of Medford",
    helps:"Medford senior living community offering independent living, assisted living and memory care.",
    audience:["Older Adults", "Families"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for pricing",
    phone:"541-930-8750",
    address:"2530 E McAndrews Road, Medford",
    website:"https://bonaventuresenior.com/senior-living-oregon/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "MEMORY CARE", "MEDFORD"],
    keywords:["Bonaventure of Medford", "assisted living", "memory care", "independent living"],
    lastVerified:"2026-09-04"
  },
  {
    id:"brookdale-medford",
    category:"senior",
    section:"Assisted Living",
    name:"Brookdale Medford — Assisted Living",
    helps:"Assisted living community in Medford with personalized support for daily activities such as bathing, dressing, medication management and mobility.",
    audience:["Older Adults", "Families"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for current pricing",
    phone:"541-776-7600",
    address:"3033 Barnett Road, Medford",
    website:"https://www.brookdale.com/en/communities/brookdale-medford.html",
    labels:["ASSISTED LIVING", "MEDFORD"],
    keywords:["Brookdale Medford", "assisted living", "daily living help", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"farmington-square-medford",
    category:"senior",
    section:"Memory Care",
    name:"Farmington Square Medford — Memory Care",
    helps:"Medford memory-care community providing specialized support in a secured community setting. Also offers respite care.",
    audience:["People with Memory Loss", "Families", "Caregivers"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for pricing",
    phone:"458-225-5234",
    address:"1530 Poplar Drive, Medford",
    website:"https://farmingtonsquare-medford.com/",
    labels:["MEMORY CARE", "RESPITE", "MEDFORD"],
    keywords:["Farmington Square", "memory care", "dementia", "Alzheimer", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"springs-veranda-park",
    category:"senior",
    section:"Independent & Assisted Living",
    name:"The Springs at Veranda Park — Medford",
    helps:"Independent living and assisted living community in Medford with apartments/cottages, dining, wellness, social programs and personalized assisted-living support.",
    audience:["Older Adults", "Families"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for pricing",
    phone:"541-494-5000",
    address:"1641 Veranda Park Drive, Medford",
    website:"https://www.thespringsliving.com/senior-living/medford/oregon/veranda-park/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "MEDFORD"],
    keywords:["Springs at Veranda Park", "assisted living", "independent living", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"springs-anna-maria",
    category:"senior",
    section:"Independent & Assisted Living",
    name:"The Springs at Anna Maria — Medford",
    helps:"Independent living and assisted living community in Medford with social programs, meals, wellness, excursions and care that can adjust as needs change.",
    audience:["Older Adults", "Families"],
    counties:["Jackson"],
    cost:"Private-pay; contact community for pricing",
    phone:"541-774-1822",
    address:"822 Golf View Drive, Medford",
    website:"https://www.thespringsliving.com/senior-living/medford/oregon/anna-maria/",
    labels:["INDEPENDENT", "ASSISTED LIVING", "MEDFORD"],
    keywords:["Springs at Anna Maria", "assisted living", "independent living", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"rogue-valley-manor",
    category:"senior",
    section:"Independent Senior Living",
    name:"Rogue Valley Manor — Life Plan Community",
    helps:"Medford Life Plan/continuing-care retirement community with cottages and apartments and a continuum of healthcare available on the campus.",
    audience:["Older Adults", "Retirees", "Families"],
    counties:["Jackson"],
    cost:"Private-pay Life Plan community; contact for current financial requirements",
    phone:"541-857-7777",
    address:"1200 Mira Mar Avenue, Medford",
    website:"https://retirement.org/rvm/",
    labels:["LIFE PLAN COMMUNITY", "RETIREMENT", "CONTINUUM OF CARE"],
    keywords:["Rogue Valley Manor", "Life Plan Community", "retirement", "continuing care", "Medford"],
    lastVerified:"2026-09-04"
  },
  {
    id:"team-senior-assisted-directory",
    category:"senior",
    section:"Help Choosing Housing & Care",
    name:"Team Senior — Assisted Living Directory",
    helps:"Clearly labeled local directory of Southern Oregon assisted-living communities. Use it to browse individual communities, then verify licensing and inspections through Oregon's official long-term-care search.",
    audience:["Older Adults", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free directory",
    phone:"541-295-8230",
    address:"Southern Oregon",
    website:"https://www.medfordassistedliving.com/",
    labels:["DIRECTORY", "ASSISTED LIVING", "LOCAL"],
    keywords:["assisted living directory", "Alderwood", "Arbor Place", "Avamere", "Redwood Terrace", "The Suites", "Weatherly Court"],
    lastVerified:"2026-09-04"
  },
  {
    id:"team-senior-independent-directory",
    category:"senior",
    section:"Help Choosing Housing & Care",
    name:"Team Senior — Independent Living Directory",
    helps:"Clearly labeled local directory of Southern Oregon independent-living communities. Includes options in Medford, Central Point, Jacksonville and Grants Pass.",
    audience:["Older Adults", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free directory",
    phone:"541-295-8230",
    address:"Southern Oregon",
    website:"https://www.medfordassistedliving.com/independent-living-communities",
    labels:["DIRECTORY", "INDEPENDENT LIVING", "LOCAL"],
    keywords:["independent living directory", "Barnett Woods", "Twin Creeks", "Pioneer Village", "Cascades", "Countryside"],
    lastVerified:"2026-09-04"
  },
  {
    id:"team-senior-memory-directory",
    category:"senior",
    section:"Help Choosing Housing & Care",
    name:"Team Senior — Memory Care Directory",
    helps:"Clearly labeled local directory of Southern Oregon memory-care communities. Use Oregon's official licensing search alongside this directory to review inspections, violations and regulatory actions.",
    audience:["People with Memory Loss", "Families", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free directory",
    phone:"541-295-8230",
    address:"Southern Oregon",
    website:"https://www.grantspassmemorycare.com/",
    labels:["DIRECTORY", "MEMORY CARE", "LOCAL"],
    keywords:["memory care directory", "dementia care", "Farmington Square", "Kinsington Place", "Cascades Pointe"],
    lastVerified:"2026-09-04"
  },
  {
    id:"caregiver-tools-rvcog",
    category:"senior",
    section:"Caregiver Help, Dementia & Respite",
    name:"RVCOG — Caregiver, Dementia & Home-Safety Tools",
    helps:"Practical planning tools from the local Area Agency on Aging, including home-safety checks, fall-prevention tools, caregiver interview questions, dementia planning resources and care-plan tools.",
    audience:["Caregivers", "Older Adults", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Free",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/resources-and-forms/",
    labels:["CAREGIVERS", "DEMENTIA", "HOME SAFETY", "FALL PREVENTION"],
    keywords:["caregiver help", "dementia", "home safety", "fall prevention", "care plan", "aging at home"],
    lastVerified:"2026-09-04"
  },
  {
    id:"senior-behavioral-health-rvcog",
    category:"senior",
    section:"Mental Health, Grief & Loneliness",
    name:"RVCOG — Older Adult Behavioral Health Resources",
    helps:"Local aging-system behavioral-health information and resources for older adults and adults with disabilities, including materials on older-adult behavioral health and high-risk medications.",
    audience:["Older Adults", "Adults with Disabilities", "Caregivers"],
    counties:["Jackson", "Josephine"],
    cost:"Free information",
    address:"Jackson + Josephine Counties",
    website:"https://rvcog.org/resources-and-forms/",
    labels:["MENTAL HEALTH", "OLDER ADULTS", "BEHAVIORAL HEALTH"],
    keywords:["senior mental health", "depression", "older adult behavioral health", "medications", "isolation"],
    lastVerified:"2026-09-04"
  },
  {
    id:"senior-veterans-crosslink",
    category:"senior",
    section:"Veterans & Surviving Spouses",
    name:"Older Veteran or Surviving Spouse — Benefits & Care Help",
    helps:"Hub pathway for older veterans and surviving spouses looking for VA benefits, Aid & Attendance, health care, transportation, home support or county veteran-service help.",
    audience:["Older Veterans", "Surviving Spouses", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Varies by program",
    address:"Flourish Anyway Hub",
    website:"search.html?q=senior%20veteran%20benefits%20aid%20attendance",
    labels:["VETERANS", "BENEFITS", "CROSS-LINK"],
    keywords:["senior veteran", "Aid and Attendance", "surviving spouse", "VA", "older veteran"],
    lastVerified:"2026-09-04"
  },
  {
    id:"senior-recovery-crosslink",
    category:"senior",
    section:"Recovery & Sobriety",
    name:"Older Adult Recovery & Sobriety Support",
    helps:"Hub pathway to recovery resources, peer support, meetings, treatment and community connection that can also serve older adults.",
    audience:["Older Adults in Recovery", "Families"],
    counties:["Jackson", "Josephine"],
    cost:"Varies; many peer/community supports are free",
    address:"Flourish Anyway Hub",
    website:"search.html?q=older%20adult%20recovery%20sobriety%20peer%20support",
    labels:["RECOVERY", "PEER SUPPORT", "CROSS-LINK"],
    keywords:["older adult recovery", "sobriety", "AA", "NA", "peer support", "substance use"],
    lastVerified:"2026-09-04"
  }
];
