/* Flourish Anyway Community Resource Hub
   MENTAL HEALTH & THERAPY — ADDITIVE DIRECTORY
   Jackson + Josephine Counties, Oregon

   Upload as: therapy-data.js
   Global: window.FLOURISH_THERAPY_DATA

   IMPORTANT:
   - This is a separate Mental Health & Therapy chapter.
   - It does NOT replace health-data.js or parenting-data.js.
   - Some established programs intentionally remain cross-linked in older files.
   - Hub-facing addresses omit ZIP codes per current architecture rules.
   - Provider availability, waitlists and insurance participation change often.
   - Last researched/verified: 2026-09-04
*/

window.FLOURISH_THERAPY_DATA = [
  {
    id:"inner-peace-counseling",
    category:"therapy",
    section:"Children, Teens, Adults & Families",
    name:"Inner Peace Counseling — Medford + Grants Pass",
    helps:"Large Southern Oregon counseling practice serving children, teens and adults. Depending on clinician, support may include individual, couples and family therapy, ADHD/neurodivergence, trauma/PTSD, anxiety, depression, behavioral concerns, parenting, women’s issues, play therapy, EMDR, CBT/DBT, neurofeedback, medication management and psychological evaluation.",
    situations:["I need a therapist", "My child or teen needs counseling", "I need trauma help", "I need ADHD or neurodivergent support", "I need couples or family therapy"],
    audience:["Children", "Teens", "Adults", "Couples", "Families", "Neurodivergent People", "Women"],
    counties:["Jackson", "Josephine"],
    city:"Medford + Grants Pass",
    cost:"Insurance and availability vary by clinician; confirm current OHP/private-plan participation directly.",
    phone:"541-281-9026",
    address:"Medford + Grants Pass",
    website:"https://ipcounselinc.org/",
    labels:["THERAPY", "CHILDREN", "TEENS", "ADULTS", "FAMILIES", "ADHD", "NEURODIVERGENCE", "TRAUMA", "WOMEN"],
    keywords:["Inner Peace", "therapist", "counseling", "autism", "ADHD", "neurodivergent", "trauma", "PTSD", "play therapy", "EMDR", "women's mental health", "couples", "family therapy"],
    sourceName:"Inner Peace Counseling",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"transform-youth-family",
    category:"therapy",
    section:"Children & Teens",
    name:"Transform Youth and Family Counseling — Medford + Grants Pass",
    helps:"Youth-centered mental-health care for ages 6–24. Services can include individual, group and family counseling, ADHD evaluations, medication management, peer support, case management and caregiver support.",
    situations:["My child or teen needs counseling", "My young adult needs support", "I need ADHD evaluation", "I need family support"],
    audience:["Children", "Teens", "Young Adults", "Parents", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Medford + Grants Pass",
    cost:"Insurance and self-pay options vary; confirm current coverage and openings.",
    phone:"541-507-6400",
    address:"Medford + Grants Pass",
    website:"https://www.transformyfc.com/",
    labels:["YOUTH", "FAMILY", "ADHD", "MEDICATION MANAGEMENT", "PEER SUPPORT"],
    keywords:["Transform Youth", "child therapist", "teen therapist", "young adult", "ADHD evaluation", "family counseling", "case management", "caregiver support"],
    sourceName:"Transform Youth & Family Counseling",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"kairos-jackson-therapy",
    category:"therapy",
    section:"Children & Teens",
    name:"Kairos Jackson Services — Youth & Family Behavioral Health",
    helps:"Outpatient behavioral-health services for youth and families, including therapy, skills coaching, peer-delivered services, family support and psychiatric services.",
    situations:["My child or teen needs counseling", "My family needs coordinated behavioral-health support", "I have OHP"],
    audience:["Children", "Teens", "Young Adults", "Parents", "Families"],
    counties:["Jackson"],
    city:"Medford",
    cost:"Program and OHP plan eligibility apply; confirm current access.",
    phone:"541-772-0127",
    address:"10 Crater Lake Ave, Medford",
    website:"https://kairosnw.org/programs-and-services/outpatient-services/",
    labels:["YOUTH", "FAMILY", "OHP", "BEHAVIORAL HEALTH"],
    keywords:["Kairos", "child therapy", "teen therapy", "family therapy", "skills coaching", "psychiatric"],
    sourceName:"Kairos",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"kairos-josephine-therapy",
    category:"therapy",
    section:"Children & Teens",
    name:"Kairos Josephine Services — Youth & Family Behavioral Health",
    helps:"Outpatient behavioral-health services for youth and families, including therapy, skills coaching, peer-delivered services, family support and psychiatric services.",
    situations:["My child or teen needs counseling", "My family needs coordinated behavioral-health support", "I have OHP"],
    audience:["Children", "Teens", "Young Adults", "Parents", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Program and OHP plan eligibility apply; confirm current access.",
    phone:"458-257-2001",
    address:"1750 Nebraska Ave, Building B, Grants Pass",
    website:"https://kairosnw.org/programs-and-services/outpatient-services/",
    labels:["YOUTH", "FAMILY", "OHP", "BEHAVIORAL HEALTH"],
    keywords:["Kairos", "child therapy", "teen therapy", "family therapy", "skills coaching", "psychiatric", "Grants Pass"],
    sourceName:"Kairos",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"options-creekside-therapy",
    category:"therapy",
    section:"Children & Teens",
    name:"Options for Southern Oregon — Creekside Child & Family Services",
    helps:"Child and family behavioral-health services including individual, group and family counseling, school-based counseling, social/behavioral skills, Wraparound-related support and psychiatric or psychological evaluation pathways.",
    situations:["My child needs counseling", "My teen needs counseling", "My child needs school-based support", "My family needs Wraparound"],
    audience:["Children", "Teens", "Parents", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Insurance and sliding-fee options vary; call for current access.",
    phone:"541-476-2373",
    address:"1181 SW Ramsey Ave, Grants Pass",
    website:"https://www.optionsonline.org/",
    labels:["CHILD THERAPY", "FAMILY", "SCHOOL-BASED", "WRAPAROUND"],
    keywords:["Options", "Creekside", "child counseling", "family therapy", "school counseling", "wraparound"],
    sourceName:"Options for Southern Oregon",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"options-adult-behavioral-health",
    category:"therapy",
    section:"Adults",
    name:"Options for Southern Oregon — Adult Behavioral Health",
    helps:"Josephine County community mental-health services for adults, including counseling and broader behavioral-health supports. Options is the county Community Mental Health Program.",
    situations:["I need an adult therapist", "I need community mental-health care", "I need lower-cost behavioral-health help"],
    audience:["Adults", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Sliding-fee and insurance options vary; contact Options for current access.",
    phone:"541-476-2373",
    address:"Grants Pass",
    website:"https://www.optionsonline.org/",
    labels:["ADULTS", "COMMUNITY MENTAL HEALTH", "SLIDING FEE"],
    keywords:["Options", "adult counseling", "mental health", "community mental health", "Josephine County"],
    sourceName:"Options for Southern Oregon",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"adapt-grants-pass-mental-health",
    category:"therapy",
    section:"Adults",
    name:"Adapt Integrated Health Care — Grants Pass Mental Health",
    helps:"Mental-health care for adults and youth plus addiction treatment at the Grants Pass location. Services include assessment, counseling, psychiatric services and care for co-occurring mental-health and substance-use needs.",
    situations:["I need a therapist", "My child or teen needs counseling", "I need mental health and recovery care together", "I need sliding-fee care"],
    audience:["Adults", "Youth", "Families", "People in Recovery"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Insurance accepted; sliding-fee discounts are available based on household size and income. Adapt states no one is denied services due to inability to pay.",
    phone:"541-474-1033",
    address:"356 NE Beacon Dr, Grants Pass",
    website:"https://adaptoregon.org/",
    labels:["ADULTS", "YOUTH", "RECOVERY", "SLIDING FEE", "PSYCHIATRIC"],
    keywords:["Adapt", "mental health", "counseling", "addiction", "co-occurring", "Grants Pass", "psychiatric"],
    sourceName:"Adapt Integrated Health Care",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"family-solutions-child-family",
    category:"therapy",
    section:"Children & Teens",
    name:"Family Solutions — Child, Teen & Family Behavioral Health",
    helps:"Individual, family and group behavioral-health care for children, teens and families, including concerns such as ADHD, behavior, anxiety, depression, trauma, grief and family conflict.",
    situations:["My child needs therapy", "My teen needs therapy", "My family needs counseling", "My child has ADHD or behavior concerns"],
    audience:["Children", "Teens", "Parents", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Rogue Valley",
    cost:"Accepts OHP and other coverage; confirm current program and access.",
    phone:"541-414-1720",
    address:"Jackson + Josephine Counties",
    website:"https://familysolutionsoregon.org/",
    labels:["CHILD THERAPY", "FAMILY THERAPY", "ADHD", "TRAUMA", "OHP"],
    keywords:["Family Solutions", "ADHD", "anxiety", "depression", "trauma", "grief", "child therapy", "teen therapy"],
    sourceName:"Family Solutions",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"family-solutions-day-treatment",
    category:"therapy",
    section:"Intensive Child & Youth Support",
    name:"Family Solutions — Psychiatric Day Treatment",
    helps:"Therapeutic day program with therapy, skills training and classroom support for children with serious, long-term emotional or behavioral needs.",
    situations:["My child needs more than weekly therapy", "My child has serious emotional or behavioral needs", "My child needs therapeutic school-day support"],
    audience:["Children", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Grants Pass",
    cost:"Eligibility and current funding/fees should be confirmed directly.",
    phone:"541-479-2966",
    address:"322 NW F St, Grants Pass",
    website:"https://familysolutionsoregon.org/",
    labels:["DAY TREATMENT", "CHILDREN", "INTENSIVE SUPPORT", "THERAPY"],
    keywords:["psychiatric day treatment", "behavior", "child therapy", "Family Solutions", "therapeutic school"],
    sourceName:"Family Solutions",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-county-mental-health",
    category:"therapy",
    section:"Adults",
    name:"Jackson County Mental Health — Outpatient Services",
    helps:"County behavioral-health services that can include individual and family counseling, group counseling, assessment and connections to additional mental-health services.",
    situations:["I need a therapist", "My family needs counseling", "I need county mental-health services", "I need help paying for care"],
    audience:["Children", "Teens", "Adults", "Families"],
    counties:["Jackson"],
    city:"Medford",
    cost:"Coverage and sliding-fee eligibility vary; contact Jackson County Behavioral Health for current information.",
    phone:"541-774-8201",
    address:"140 S Holly St, Medford",
    website:"https://jacksoncountyor.gov/hhs/Behavioral_Health/",
    labels:["COMMUNITY MENTAL HEALTH", "FAMILY THERAPY", "ASSESSMENT"],
    keywords:["Jackson County Mental Health", "family therapist", "adult counseling", "child counseling", "Medford"],
    sourceName:"Jackson County Behavioral Health",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-county-pcit",
    category:"therapy",
    section:"Children & Teens",
    name:"Jackson County Mental Health — Parent-Child Interaction Therapy (PCIT)",
    helps:"Specialized parent-child therapy for young children with significant tantrums, separation anxiety, trauma-related behavior, destructive behavior or parent-child relationship concerns.",
    situations:["My young child has severe behavior problems", "My child has tantrums or separation anxiety", "I need parent-child therapy"],
    audience:["Young Children", "Parents", "Foster Parents", "Kinship Caregivers", "Families"],
    counties:["Jackson"],
    city:"Medford",
    cost:"Coverage and eligibility vary; contact Jackson County Mental Health.",
    phone:"541-774-3333",
    address:"140 S Holly St, Medford",
    website:"https://jacksoncountyor.gov/hhs/Behavioral_Health/",
    labels:["PCIT", "PARENT-CHILD", "BEHAVIOR", "TRAUMA"],
    keywords:["PCIT", "tantrums", "behavior", "separation anxiety", "trauma", "young child", "parent child therapy"],
    sourceName:"Jackson County Behavioral Health",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"pinnacle-health-services",
    category:"therapy",
    section:"Children, Teens, Adults & Families",
    name:"Pinnacle Health Services — Central Point",
    helps:"Counseling for adults, children and adolescents plus couples therapy. Specialty areas listed by the practice include anxiety, depression, PTSD/trauma, sensory and behavioral concerns, grief, ADHD, stress, relationship concerns and self-esteem.",
    situations:["I need a therapist", "My child or teen needs counseling", "I need couples counseling", "I need trauma or ADHD support"],
    audience:["Adults", "Children", "Teens", "Couples", "Families"],
    counties:["Jackson"],
    city:"Central Point",
    cost:"Insurance and self-pay vary; confirm directly.",
    phone:"541-423-8151",
    address:"547 E Pine St, Suite 201, Central Point",
    website:"https://www.cppinnacle.com/",
    labels:["THERAPY", "CHILDREN", "COUPLES", "TRAUMA", "ADHD"],
    keywords:["Pinnacle", "therapist", "counseling", "PTSD", "trauma", "ADHD", "child therapy", "couples counseling", "Central Point"],
    sourceName:"Pinnacle Health Services",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-county-therapy-private",
    category:"therapy",
    section:"Adults",
    name:"Jackson County Therapy — Private Practice",
    helps:"Private Medford therapy practice offering in-person care in Medford and telehealth statewide in Oregon. The practice is separate from Jackson County government.",
    situations:["I need an adult therapist", "I want telehealth", "I need trauma-informed counseling"],
    audience:["Adults", "Families", "Veterans", "Trauma Survivors"],
    counties:["Jackson", "Josephine"],
    city:"Medford + Telehealth",
    cost:"Coverage and availability vary; confirm directly.",
    phone:"541-414-4931",
    address:"670 Superior Ct, Medford",
    website:"https://www.jacksoncountytherapy.com/",
    labels:["THERAPY", "TELEHEALTH", "TRAUMA", "PRIVATE PRACTICE"],
    keywords:["Jackson County Therapy", "therapist", "counselor", "mental health", "telehealth", "Medford", "trauma"],
    sourceName:"Jackson County Therapy",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"quality-counseling-services",
    category:"therapy",
    section:"Adults",
    name:"Quality Counseling Services — Medford + Grants Pass",
    helps:"Local counseling practice with offices in Medford and Grants Pass. Call directly for current clinicians, specialties, openings and insurance participation.",
    situations:["I need a therapist in Medford", "I need a therapist in Grants Pass", "I need to check insurance before starting therapy"],
    audience:["Adults", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Medford + Grants Pass",
    cost:"Insurance contracts can change; verify current coverage directly before scheduling.",
    phone:"541-890-9594",
    address:"Medford + Grants Pass",
    website:"https://qualitycounselingservices.com/",
    labels:["THERAPY", "MEDFORD", "GRANTS PASS"],
    keywords:["Quality Counseling Services", "therapist", "Medford", "Grants Pass", "counseling"],
    sourceName:"Quality Counseling Services",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"serein-counseling",
    category:"therapy",
    section:"Autism, ADHD & Neurodivergence",
    name:"Serein Counseling",
    helps:"Counseling for adults, adolescents, couples and families, with experience supporting autistic and other neurodivergent children, teens and adults, including ADHD.",
    situations:["I need an autism-affirming therapist", "I need ADHD support", "My neurodivergent child or teen needs counseling", "I need couples or family counseling"],
    audience:["Children", "Teens", "Adults", "Couples", "Families", "Neurodivergent People"],
    counties:["Jackson", "Josephine"],
    city:"Southern Oregon",
    cost:"Coverage and openings vary; confirm directly.",
    phone:"541-872-3844",
    address:"Southern Oregon",
    website:"https://www.sereincounseling.com/",
    labels:["AUTISM", "ADHD", "NEURODIVERGENCE", "FAMILY", "COUPLES"],
    keywords:["Serein", "autism", "ADHD", "neurodivergent", "neurodiversity", "teen therapist", "adult therapist", "family counseling"],
    sourceName:"Serein Counseling",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"southern-oregon-psychology-ditty",
    category:"therapy",
    section:"Adults",
    name:"Southern Oregon Psychology — Dr. Matt Ditty",
    helps:"Virtual psychological services for individuals, couples and families. Areas listed by the practice include trauma/PTSD, depression, anxiety, ADHD, addiction, behavioral concerns, chronic pain, grief, eating concerns, family conflict, school concerns and women’s issues.",
    situations:["I want telehealth therapy", "I need trauma or PTSD help", "I need ADHD support", "I need couples or family therapy"],
    audience:["Adults", "Couples", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Telehealth",
    cost:"Practice lists several private plans and AllCare/OHP; verify current coverage directly.",
    phone:"541-226-4396",
    address:"Telehealth across Oregon",
    website:"https://www.sorpsych.com/",
    labels:["PSYCHOLOGIST", "TELEHEALTH", "TRAUMA", "ADHD", "COUPLES"],
    keywords:["Matt Ditty", "Southern Oregon Psychology", "psychologist", "telehealth", "PTSD", "ADHD", "couples", "family"],
    sourceName:"Southern Oregon Psychology",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"david-smith-lcsw",
    category:"therapy",
    section:"Autism, ADHD & Neurodivergence",
    name:"David Smith, LCSW — Grants Pass / Telehealth",
    helps:"Neurodiversity-affirming and trauma-informed counseling with specialty focus including autism, ADHD and trauma/PTSD. Current services are primarily telehealth; verify availability.",
    situations:["I need an autism-affirming therapist", "I need ADHD support", "I need trauma therapy", "I prefer telehealth"],
    audience:["Adults", "Families", "Neurodivergent People"],
    counties:["Josephine", "Jackson"],
    city:"Grants Pass + Telehealth",
    cost:"Insurance participation and openings change; verify directly.",
    phone:"541-697-4914",
    address:"Grants Pass / Telehealth",
    website:"https://www.psychologytoday.com/us/therapists/david-smith-grants-pass-or/",
    labels:["AUTISM", "ADHD", "NEURODIVERGENCE", "TRAUMA", "TELEHEALTH"],
    keywords:["David Smith", "LCSW", "autism", "ADHD", "neurodivergent", "trauma", "PTSD", "Grants Pass"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"darnel-owens-scott",
    category:"therapy",
    section:"Autism, ADHD & Neurodivergence",
    name:"Darnel Owens Scott, LMFT — Grants Pass",
    helps:"Counseling with specialty interests including ADHD, anxiety and neurodivergence; provider listings also note neurofeedback and experience with autism and learning differences.",
    situations:["I need ADHD support", "I need neurodivergent-affirming counseling", "I am looking for neurofeedback"],
    audience:["Adults", "Teens", "Neurodivergent People", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Insurance participation and waitlist status can change; verify directly.",
    phone:"458-203-3160",
    address:"225 NE C St, Grants Pass",
    website:"https://www.psychologytoday.com/us/therapists/darnel-owens-scott-grants-pass-or/",
    labels:["ADHD", "NEURODIVERGENCE", "NEUROFEEDBACK", "ANXIETY"],
    keywords:["Darnel Owens Scott", "LMFT", "ADHD", "neurodivergence", "neurofeedback", "autism", "Grants Pass"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"stubbs-music-therapy",
    category:"therapy",
    section:"Autism, ADHD & Neurodivergence",
    name:"Stubbs Music Therapy and Counseling LLC — Medford",
    helps:"Counseling and board-certified music therapy with specialty focus including trauma/PTSD, ADHD and autism. Services may use experiential and music-based approaches in addition to counseling.",
    situations:["I want a therapist who uses music or experiential therapy", "I need autism or ADHD support", "I need trauma therapy"],
    audience:["Teens", "Adults", "Neurodivergent People", "Trauma Survivors"],
    counties:["Jackson", "Josephine"],
    city:"Medford",
    cost:"Insurance participation varies; verify current coverage and openings.",
    phone:"458-207-2469",
    address:"221 W Main St, Suite 300, Medford",
    website:"https://www.psychologytoday.com/us/therapists/richard-m-stubbs-medford-or/",
    labels:["MUSIC THERAPY", "AUTISM", "ADHD", "TRAUMA"],
    keywords:["Stubbs", "music therapy", "ADHD", "autism", "trauma", "PTSD", "Medford"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"melissa-chapman-lpc",
    category:"therapy",
    section:"Trauma & PTSD",
    name:"Melissa Chapman, LPC — Medford",
    helps:"Individual and family counseling with specialty focus including trauma/PTSD, anxiety and life transitions.",
    situations:["I need trauma therapy", "I have anxiety", "I am going through a major life change"],
    audience:["Adults", "Families", "Trauma Survivors"],
    counties:["Jackson"],
    city:"Medford",
    cost:"Insurance participation and openings vary; verify directly.",
    phone:"541-566-4822",
    address:"1600 Sky Park Dr, Suite 217, Medford",
    website:"https://www.psychologytoday.com/us/therapists/melissa-chapman-medford-or/",
    labels:["TRAUMA", "PTSD", "ANXIETY", "LIFE TRANSITIONS"],
    keywords:["Melissa Chapman", "LPC", "trauma", "PTSD", "anxiety", "Medford"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"melissa-howard-lmft",
    category:"therapy",
    section:"Children & Teens",
    name:"Melissa Howard, LMFT — Grants Pass",
    helps:"Counseling for youth, adults and families with areas that include trauma/PTSD, depression, anxiety, child and adolescent needs, parenting, identity and gender-affirming care; play therapy may be used with younger clients.",
    situations:["My child or teen needs therapy", "I need family therapy", "I need trauma help", "I need affirming counseling"],
    audience:["Children", "Teens", "Adults", "Parents", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Insurance and availability vary; verify directly.",
    phone:"541-348-6750",
    address:"Grants Pass",
    website:"https://www.psychologytoday.com/us/therapists/melissa-howard-grants-pass-or/",
    labels:["YOUTH", "FAMILY", "TRAUMA", "PLAY THERAPY", "AFFIRMING"],
    keywords:["Melissa Howard", "LMFT", "child therapist", "teen therapist", "play therapy", "trauma", "parenting", "Grants Pass"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"mending-minds-latara-wilson",
    category:"therapy",
    section:"Autism, ADHD & Neurodivergence",
    name:"Mending Minds Counseling — Latara Wilson, LPC",
    helps:"Counseling with specialty areas including anxiety, depression, trauma, ADHD, OCD and neurodivergence.",
    situations:["I need ADHD support", "I need OCD support", "I need trauma therapy", "I need neurodivergent-affirming care"],
    audience:["Adults", "Teens", "Neurodivergent People"],
    counties:["Josephine", "Jackson"],
    city:"Grants Pass / Telehealth",
    cost:"Insurance and openings vary; verify directly.",
    phone:"971-458-4374",
    address:"Grants Pass / Telehealth",
    website:"https://www.psychologytoday.com/us/therapists/latara-wilson-grants-pass-or/",
    labels:["ADHD", "OCD", "NEURODIVERGENCE", "TRAUMA", "ANXIETY"],
    keywords:["Mending Minds", "Latara Wilson", "ADHD", "OCD", "neurodivergent", "trauma", "Grants Pass"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"michael-stattel-lpc",
    category:"therapy",
    section:"Adults",
    name:"Michael Stattel, LPC — Grants Pass",
    helps:"Adult counseling for concerns including anxiety, depression, stress, grief, trauma patterns, relationships and emotional regulation, with a somatic orientation.",
    situations:["I need an adult therapist", "I have anxiety or depression", "I am grieving", "I want somatic or trauma-informed counseling"],
    audience:["Adults", "Couples"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Insurance and self-pay vary; verify directly.",
    phone:"541-472-8022",
    address:"980 SW 6th St, Suite 22, Grants Pass",
    website:"https://www.psychologytoday.com/us/therapists/michael-stattel-grants-pass-or/",
    labels:["ADULTS", "ANXIETY", "GRIEF", "TRAUMA", "SOMATIC"],
    keywords:["Michael Stattel", "LPC", "somatic", "grief", "trauma", "anxiety", "depression", "Grants Pass"],
    sourceName:"Current provider listing",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"agape-professional-counseling",
    category:"therapy",
    section:"Adults",
    name:"Agape Professional Counseling Center — Grants Pass",
    helps:"Private counseling practice in Grants Pass. Public provider listings identify support for concerns including trauma/PTSD, addiction and relationship or couples concerns; confirm current clinician specialties directly.",
    situations:["I need a therapist in Grants Pass", "I need trauma help", "I need recovery-related counseling", "I need relationship counseling"],
    audience:["Adults", "Couples", "People in Recovery"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Coverage and openings vary; verify directly.",
    phone:"",
    address:"432 NW 6th St, Grants Pass",
    website:"https://www.psychologytoday.com/us/therapists/or/grants-pass",
    labels:["ADULTS", "TRAUMA", "RECOVERY", "COUPLES"],
    keywords:["Agape Professional Counseling", "Grants Pass", "trauma", "addiction", "couples counseling"],
    sourceName:"Current public provider listings",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"josephine-cac-therapy",
    category:"therapy",
    section:"Trauma & PTSD",
    name:"Josephine County Children’s Advocacy Center — Trauma Therapy Connection",
    helps:"For children affected by abuse, the Children’s Advocacy Center can connect families with licensed therapists who specialize in child trauma and help caregivers navigate therapy options.",
    situations:["My child experienced abuse", "My child needs trauma therapy", "I need help finding a child trauma therapist"],
    audience:["Children", "Teens", "Non-Offending Caregivers", "Families"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Contact the center for current service and referral information.",
    phone:"541-916-4166",
    address:"700 NW 5th St, Grants Pass",
    website:"https://www.cacjoco.org/services",
    labels:["CHILD TRAUMA", "ABUSE", "THERAPY CONNECTION", "CAC"],
    keywords:["Josephine County Children's Advocacy Center", "child abuse", "trauma therapist", "child trauma", "Grants Pass"],
    sourceName:"Josephine County Children's Advocacy Center",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-cac-therapy",
    category:"therapy",
    section:"Trauma & PTSD",
    name:"Children’s Advocacy Center of Jackson County — Child Trauma Support",
    helps:"Child-focused advocacy and treatment connection for children and families affected by abuse. Use this pathway when a child needs specialized trauma-informed support after abuse.",
    situations:["My child experienced abuse", "My child needs trauma-informed support", "I need help after a child abuse disclosure"],
    audience:["Children", "Teens", "Non-Offending Caregivers", "Families"],
    counties:["Jackson"],
    city:"Medford",
    cost:"Contact the center for current service and referral information.",
    phone:"",
    address:"Medford",
    website:"https://cacjc.org/",
    labels:["CHILD TRAUMA", "ABUSE", "CAC", "THERAPY CONNECTION"],
    keywords:["Children's Advocacy Center Jackson County", "child abuse", "trauma", "therapy", "Medford"],
    sourceName:"Children's Advocacy Center of Jackson County",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"theraplay-pediatric-ot",
    category:"therapy",
    section:"Developmental Disability & Sensory Support",
    name:"TheraPlay LLC — Pediatric Occupational Therapy",
    helps:"Pediatric occupational therapy for children with disabilities or developmental delays, including sensory processing, daily living skills, gross/fine motor delays, visual-motor skills, handwriting, reflex integration and ocular-motor skills. This is occupational therapy, not psychotherapy.",
    situations:["My child has sensory needs", "My child has developmental delays", "My child needs occupational therapy", "My child has fine-motor or daily-living challenges"],
    audience:["Children", "Parents", "Families", "Children with Disabilities"],
    counties:["Josephine"],
    city:"Grants Pass",
    cost:"Current site lists AllCare, Regence, Providence and Moda; referral/prescription from a physician is required. Verify current insurance status.",
    phone:"541-659-7134",
    address:"337 Union Ave, Unit D, Grants Pass",
    website:"https://www.theraplaygp.com/",
    labels:["PEDIATRIC OT", "SENSORY", "DEVELOPMENTAL DELAY", "DISABILITY"],
    keywords:["TheraPlay", "occupational therapy", "sensory processing", "developmental delay", "fine motor", "ADL", "Grants Pass"],
    sourceName:"TheraPlay LLC",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"allcare-find-behavioral-health",
    category:"therapy",
    section:"OHP, Insurance & Finding a Therapist",
    name:"AllCare Health — Find Behavioral Health Care",
    helps:"Use AllCare’s member/provider resources to find current in-network mental-health and behavioral-health providers when you have AllCare Oregon Health Plan coverage.",
    situations:["I have AllCare OHP", "I need an in-network therapist", "I need to find someone taking my insurance"],
    audience:["AllCare Members", "Adults", "Children", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Jackson + Josephine Counties",
    cost:"OHP member benefits and network rules apply.",
    phone:"",
    address:"Online provider search",
    website:"https://www.allcarehealth.com/",
    labels:["OHP", "ALLCARE", "FIND A THERAPIST", "INSURANCE"],
    keywords:["AllCare", "OHP", "therapist directory", "behavioral health provider", "in network"],
    sourceName:"AllCare Health",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"jackson-care-connect-find-therapy",
    category:"therapy",
    section:"OHP, Insurance & Finding a Therapist",
    name:"Jackson Care Connect — Find Behavioral Health Care",
    helps:"Jackson Care Connect members can use the plan’s provider resources to locate current in-network mental-health and behavioral-health providers.",
    situations:["I have Jackson Care Connect", "I need an in-network therapist", "I need to find someone taking my OHP plan"],
    audience:["Jackson Care Connect Members", "Adults", "Children", "Families"],
    counties:["Jackson"],
    city:"Jackson County",
    cost:"OHP member benefits and network rules apply.",
    phone:"",
    address:"Online provider search",
    website:"https://www.jacksoncareconnect.org/",
    labels:["OHP", "JACKSON CARE CONNECT", "FIND A THERAPIST", "INSURANCE"],
    keywords:["Jackson Care Connect", "OHP", "therapist directory", "behavioral health provider", "in network"],
    sourceName:"Jackson Care Connect",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"psychology-today-jackson",
    category:"therapy",
    section:"OHP, Insurance & Finding a Therapist",
    name:"Psychology Today — Jackson County Therapist Directory",
    helps:"Broad searchable directory for individual therapists serving Jackson County. Filter by city, age, concern, treatment type, insurance, gender, telehealth and other preferences. Always verify license, availability and insurance directly.",
    situations:["I want to compare individual therapists", "I need a specific specialty", "I want telehealth", "I need to filter by insurance"],
    audience:["Adults", "Children", "Teens", "Couples", "Families"],
    counties:["Jackson"],
    city:"Jackson County",
    cost:"Varies by therapist.",
    phone:"",
    address:"Online directory",
    website:"https://www.psychologytoday.com/us/therapists/or/jackson-county",
    labels:["DIRECTORY", "FIND A THERAPIST", "SPECIALTY FILTERS"],
    keywords:["Psychology Today", "Jackson County therapist", "Medford therapist", "Ashland therapist", "Central Point therapist"],
    sourceName:"Psychology Today",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"psychology-today-josephine",
    category:"therapy",
    section:"OHP, Insurance & Finding a Therapist",
    name:"Psychology Today — Grants Pass / Josephine Therapist Directory",
    helps:"Broad searchable directory for individual therapists serving Grants Pass and Josephine County. Filter by age, concern, treatment type, insurance, telehealth and other preferences. Always verify license, availability and insurance directly.",
    situations:["I want to compare individual therapists", "I need a specific specialty", "I want telehealth", "I need to filter by insurance"],
    audience:["Adults", "Children", "Teens", "Couples", "Families"],
    counties:["Josephine"],
    city:"Grants Pass + Josephine County",
    cost:"Varies by therapist.",
    phone:"",
    address:"Online directory",
    website:"https://www.psychologytoday.com/us/therapists/or/grants-pass",
    labels:["DIRECTORY", "FIND A THERAPIST", "SPECIALTY FILTERS"],
    keywords:["Psychology Today", "Josephine County therapist", "Grants Pass therapist", "Cave Junction therapist"],
    sourceName:"Psychology Today",
    lastVerified:"2026-09-04",
    scheduleChangesOften:true
  },
  {
    id:"oregon-license-lookup-mental-health",
    category:"therapy",
    section:"OHP, Insurance & Finding a Therapist",
    name:"Oregon Mental Health License Lookup",
    helps:"Before choosing a private therapist, use Oregon’s licensing boards to verify that a counselor, marriage and family therapist, social worker or psychologist has a current Oregon license and review public license information.",
    situations:["I want to verify a therapist’s license", "I am choosing between private therapists", "I want to check credentials"],
    audience:["Anyone Seeking Therapy", "Parents", "Families"],
    counties:["Jackson", "Josephine"],
    city:"Oregon",
    cost:"Free public lookup.",
    phone:"",
    address:"Online",
    website:"https://www.oregon.gov/oblpct/Pages/Licensee-Lookup.aspx",
    labels:["LICENSE LOOKUP", "VERIFY PROVIDER", "SAFETY"],
    keywords:["therapist license", "counselor license", "LMFT", "LPC", "psychologist", "social worker", "verify therapist"],
    sourceName:"Oregon Board of Licensed Professional Counselors and Therapists",
    lastVerified:"2026-09-04",
    scheduleChangesOften:false
  }
];
