/* Flourish Anyway Community Resource Hub
   TRANSPORTATION & DRIVER'S LICENSE
   File name after upload: transportation-data.js
   Jackson + Josephine Counties, Oregon
   Backbone: 211info + official local/state/provider sources
   Last researched: 2026-08-30
*/

window.FLOURISH_TRANSPORTATION_DATA = [
  {
    id:"rvtd-fixed-route",
    category:"transportation",
    name:"Rogue Valley Transportation District — Fixed-Route Bus Service",
    helps:"Public bus service connecting Medford, Ashland, Central Point, Talent, Phoenix, White City and Jacksonville.",
    audience:["Adults","Families","Youth","Seniors","Disability"],
    counties:["Jackson"],
    cost:"Current full fare $2; reduced fare $1 for qualifying riders",
    phone:"541-779-2877",
    address:"Front Street Station, 200 S Front St, Medford, OR 97501",
    website:"https://www.rvtd.org/service-information/",
    labels:["BUS","JACKSON","PUBLIC TRANSIT"],
    keywords:["RVTD","bus","Medford","Ashland","Phoenix","Talent","White City","Jacksonville"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-reduced-fare",
    category:"transportation",
    name:"RVTD — Reduced Fare Program",
    helps:"Discounted transit for eligible seniors, youth, Medicare cardholders, disabled veterans, Valley Lift riders and people with disabilities.",
    audience:["Seniors 62+","Youth 10-17","Medicare","Disabled Veterans","Disability"],
    counties:["Jackson"],
    cost:"Current reduced fare $1 single ride; reduced monthly pass $28",
    phone:"541-779-2877",
    address:"200 S Front St, Medford, OR 97501",
    website:"https://www.rvtd.org/fares-passes/",
    labels:["REDUCED FARE","SENIORS","DISABILITY","VETERANS"],
    keywords:["cheap bus","reduced fare","senior","disabled veteran","Medicare","youth fare"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-valley-lift",
    category:"transportation",
    name:"RVTD — Valley Lift Paratransit",
    helps:"Wheelchair-accessible origin-to-destination transportation for people whose disability prevents them from using regular RVTD fixed-route buses.",
    audience:["Disability","Mobility Limitations"],
    counties:["Jackson"],
    cost:"Current fare $4 per ride",
    eligibility:"ADA paratransit eligibility; professional verification may be required.",
    phone:"541-842-2080",
    address:"239 E Barnett Rd, Medford, OR 97501",
    website:"https://www.rvtd.org/accessible-transportation/valley-lift/",
    labels:["PARATRANSIT","WHEELCHAIR","ADA"],
    keywords:["Valley Lift","paratransit","wheelchair","disabled","ADA ride"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-valley-lift-scheduling",
    category:"transportation",
    name:"RVTD — Valley Lift Ride Scheduling",
    helps:"Schedule an approved Valley Lift paratransit ride.",
    audience:["Approved Valley Lift Riders"],
    counties:["Jackson"],
    cost:"Current fare $4 per ride",
    phone:"541-842-2050",
    address:"Jackson County service area",
    website:"https://www.rvtd.org/accessible-transportation/valley-lift/",
    labels:["PARATRANSIT","SCHEDULING"],
    keywords:["schedule Valley Lift","paratransit appointment","ride"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-translink",
    category:"transportation",
    name:"TransLink — OHP Medical Transportation",
    helps:"Non-emergency medical transportation for eligible Oregon Health Plan members in Southern Oregon, including rides to covered appointments and mileage reimbursement options.",
    audience:["OHP Members","Adults","Children","Families","Disability"],
    counties:["Jackson","Josephine"],
    cost:"Covered for eligible OHP members when approved",
    phone:"888-518-8160",
    address:"239 E Barnett Rd, Medford, OR 97501",
    website:"https://www.rvtd.org/accessible-transportation/translink/",
    source211:"https://www.211info.org/get-help/transportation/non-emergency-medical-transportation/",
    labels:["OHP","MEDICAL RIDES","MILEAGE REIMBURSEMENT"],
    keywords:["TransLink","medical transportation","OHP ride","doctor ride","mileage reimbursement"],
    lastVerified:"2026-08-30"
  },
  {
    id:"rvtd-translink-local",
    category:"transportation",
    name:"TransLink — Jackson County Local Scheduling Line",
    helps:"Local scheduling line for eligible Medicaid/OHP non-emergency medical transportation.",
    audience:["OHP Members"],
    counties:["Jackson"],
    cost:"Covered for eligible OHP members",
    phone:"541-842-2060",
    address:"239 E Barnett Rd, Medford, OR 97501",
    website:"https://www.rvtd.org/accessible-transportation/translink/",
    labels:["OHP","MEDICAL RIDES","LOCAL NUMBER"],
    keywords:["medical ride","TransLink","Jackson Care Connect","Medicaid"],
    lastVerified:"2026-08-30"
  },
  {
    id:"allcare-medical-transport",
    category:"transportation",
    name:"AllCare Health — Non-Emergency Medical Transportation",
    helps:"Transportation coordination for eligible AllCare Oregon Health Plan members traveling to covered health-care services.",
    audience:["AllCare OHP Members"],
    counties:["Jackson","Josephine"],
    cost:"No fee for eligible covered transportation",
    phone:"541-471-4106",
    address:"Southern Oregon service area",
    website:"https://www.211info.org/agency/24377/13028/",
    source211:"https://www.211info.org/agency/24377/13028/",
    labels:["OHP","MEDICAL RIDES","ALLCARE"],
    keywords:["AllCare","medical ride","OHP","Medicaid","transportation"],
    lastVerified:"2026-08-30"
  },
  {
    id:"jct-fixed-route",
    category:"transportation",
    name:"Josephine Community Transit — Fixed-Route Bus Service",
    helps:"Public bus service within Grants Pass and Josephine County, including fixed routes and regional connections.",
    audience:["Adults","Families","Youth","Seniors","Disability"],
    counties:["Josephine"],
    cost:"Fare varies by route/service",
    phone:"541-474-5452",
    address:"Grants Pass, OR",
    website:"https://www.grantspassoregon.gov/443/Transportation",
    labels:["BUS","JOSEPHINE","PUBLIC TRANSIT"],
    keywords:["Josephine Community Transit","JCT","bus","Grants Pass"],
    lastVerified:"2026-08-30"
  },
  {
    id:"jct-dial-a-ride",
    category:"transportation",
    name:"Josephine Community Transit — Dial-A-Ride",
    helps:"Demand-response transportation for eligible Grants Pass seniors and residents with disabilities who require accessible transportation.",
    audience:["Seniors","Disability"],
    counties:["Josephine"],
    cost:"Call for current fare and eligibility",
    phone:"541-474-5452",
    address:"Grants Pass, OR",
    website:"https://www.grantspassoregon.gov/443/Transportation",
    labels:["DIAL-A-RIDE","SENIORS","DISABILITY"],
    keywords:["Dial A Ride","senior transportation","disabled ride","Josephine"],
    lastVerified:"2026-08-30"
  },
  {
    id:"pacific-crest-regional",
    category:"transportation",
    name:"Pacific Crest Bus Lines — Southern Oregon Regional Service",
    helps:"Regional intercity bus service connecting Medford and Grants Pass with Roseburg, Eugene and other I-5 corridor communities.",
    audience:["Adults","Families","Students","Travelers"],
    counties:["Jackson","Josephine"],
    cost:"Ticket price varies",
    phone:"",
    address:"Medford + Grants Pass regional stops",
    website:"https://www.rvtd.org/regional-public-transit-services/",
    labels:["INTERCITY BUS","GRANTS PASS","MEDFORD"],
    keywords:["regional bus","Eugene","Roseburg","Grants Pass","Medford"],
    lastVerified:"2026-08-30"
  },
  {
    id:"golden-rule-dmv",
    category:"transportation",
    name:"Golden Rule ReEntry — DMV & License Help",
    helps:"Peer/case-management help with DMV situations, reentry, housing, employment and other barriers for people returning from incarceration.",
    audience:["Adults","Reentry","Formerly Incarcerated"],
    counties:["Jackson"],
    cost:"Free support",
    phone:"541-930-8933",
    address:"715 W Main St, Medford, OR 97501",
    website:"https://www.goldenrulereentry.org/our-services",
    labels:["DMV HELP","REENTRY","CASE MANAGEMENT"],
    keywords:["license","DMV","suspended","reentry","driving privilege","Golden Rule"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-dmv-suspension-info",
    category:"transportation",
    name:"Oregon DMV — Suspension, Revocation & Reinstatement Information",
    helps:"Official information about why driving privileges are suspended or revoked and what may be required before driving again.",
    audience:["Drivers"],
    counties:["Jackson","Josephine"],
    cost:"DMV fees may apply",
    phone:"503-945-5000",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odot/dmv/pages/driverid/suspreasons.aspx",
    labels:["DMV","SUSPENSION","REINSTATEMENT"],
    keywords:["suspended license","revoked","DMV","FTA","FTC","driving while suspended"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-license-reinstatement-program",
    category:"transportation",
    name:"Oregon Department of Revenue — License Reinstatement Program",
    helps:"May help eligible drivers clear qualifying Oregon circuit-court debt holds by making a down payment and entering a monthly payment plan.",
    audience:["Drivers with Qualifying Court Debt"],
    counties:["Jackson","Josephine"],
    cost:"Current program requires a $200 down payment plus monthly payment plan; DMV reinstatement fee may also apply",
    phone:"877-222-2346",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/dor/programs/Collections/Pages/license-reinstatement.aspx",
    labels:["LICENSE REINSTATEMENT","COURT DEBT","PAYMENT PLAN"],
    keywords:["license reinstatement","court debt","payment plan","suspended license","OAA"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-hardship-permit",
    category:"transportation",
    name:"Oregon DMV — Hardship Permit",
    helps:"A restricted driving permit may be available for some suspensions or habitual-offender revocations for approved purposes such as work, seeking work or medical treatment.",
    audience:["Drivers with Certain Suspensions"],
    counties:["Jackson","Josephine"],
    cost:"DMV application/reinstatement and insurance requirements may apply",
    phone:"503-945-5000",
    address:"Statewide Oregon",
    website:"https://www.oregon.gov/odot/dmv/pages/driverid/hardship.aspx",
    labels:["HARDSHIP PERMIT","WORK","MEDICAL"],
    keywords:["hardship license","work permit","medical driving","habitual offender","restricted license"],
    lastVerified:"2026-08-30"
  },
  {
    id:"oregon-dmv-status",
    category:"transportation",
    name:"Oregon DMV2U — Check Driver License Standing",
    helps:"Official DMV online tools can help drivers check their driving privilege status and complete some reinstatement-related transactions.",
    audience:["Drivers"],
    counties:["Jackson","Josephine"],
    cost:"Some transactions have fees",
    phone:"503-945-5000",
    address:"Statewide Oregon",
    website:"https://dmv2u.oregon.gov/",
    labels:["DMV2U","CHECK STATUS","ONLINE"],
    keywords:["license status","DMV2U","check suspension","reinstatement fee"],
    lastVerified:"2026-08-30"
  },
  {
    id:"grants-pass-dmv",
    category:"transportation",
    name:"Oregon DMV — Grants Pass Office",
    helps:"Local DMV office for licensing, identification and vehicle-related services.",
    audience:["Drivers","Residents"],
    counties:["Josephine"],
    cost:"DMV fees vary",
    phone:"541-474-3179",
    address:"162 NE Beacon Dr, Suite 127, Grants Pass, OR 97526",
    website:"https://www.grantspassoregon.gov/1810/Miscellaneous",
    labels:["DMV","GRANTS PASS"],
    keywords:["Grants Pass DMV","license","ID","vehicle"],
    lastVerified:"2026-08-30"
  },
  {
    id:"211-transportation-search",
    category:"transportation",
    name:"211info — Transportation Search",
    helps:"Search Oregon's larger live directory for medical rides, public transit, paratransit, gas help, volunteer transportation and other transportation resources not yet individually listed in the Flourish hub.",
    audience:["Everyone"],
    counties:["Jackson","Josephine"],
    cost:"Free information and referral",
    phone:"211",
    address:"Oregon statewide",
    website:"https://www.211info.org/",
    apply:"https://www.211info.org/get-help/transportation/",
    labels:["211","LIVE DIRECTORY","CATCH-ALL"],
    keywords:["211","transportation","ride","bus","gas","medical ride","paratransit"],
    lastVerified:"2026-08-30"
  }
];
